govuk-one-login/performance-testing

deploy/template.yaml
Updated template to copy the changes made to the sam-deploy-pipeline to allow the codebuild container to run within a VPC.
Breaking change, as requires a vpc parameter.
=> PLAT-909 Updated template to run perf in VPC

deploy/scripts/README.md
Adding info on configuring linting to the `README.md` file in the `deploy/scripts` directory for local dev setup.
=> [PLAT-1107] Add linting configuration information to local installation guide

deploy/Dockerfile
Pinning `k6` version in `Dockerfile` to `v0.44.0`
=> [QA-165] Pin k6 version in Dockerfile

deploy/otel-config-template.yaml, deploy/template.yaml
Adding a `kill` command in the post-build to send a `SIGTERM` signal to the OpenTelemetry collector, and wait for it to shutdown gracefully with a while loop
=> [QA-142] Shutdown OpenTelemetry collector at end of test

deploy/template.yaml
Removing references to CloudFormation stacks in Dev Platform environments
These stacks do not exist in the new performance test account
=> [QA-182] Remove Cloudformation stack references

.github/workflows/publish.yaml
- Removing the workflow action to publish to the legacy dev platform accounts
=> [QA-198] Remove legacy publish action

deploy/template.yaml
Changes:
- Removing Open Telemetry logging from CodeBuild post build actions.
- Have not changed the open telemetry logging configuration in the otel-config-template.yaml in case logging needs to be enabled again.
=> [QA-112]: Remove open telemetry logging

deploy/otel-config-template.yaml
Changes: Reducing the max batch processor size in OTEL config as recommended:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/dynatraceexporter#metric-batching
- https://www.dynatrace.com/support/help/dynatrace-api/basics/access-limit
=> [QA-142]: Reducing the max batch processor size in OTEL config

.github/CODEOWNERS
Adding a `CODEOWNERS` file to specify code owners for the repository.
=> [QA-201] Add CODEOWNERS file

deploy/Dockerfile
Changes
- Reducing `K6_STATSD_PUSH_INTERVAL` and `OTEL_METRIC_EXPORT_INTERVAL` to `100` milliseconds
Related:
- https://k6.io/docs/results-output/real-time/statsd/
- https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#periodic-exporting-metricreader
- #117
=> [QA-142] Reduce push intervals for StatsD and OTEL

deploy/Dockerfile
Reducing the push interval for StatsD and OTEL to 10ms
- K6_STATSD_PUSH_INTERVAL reduced to 10ms from 100ms
- OTEL_METRIC_EXPORT_INTERVAL reduced to 10 from 100
---
We are still observing a discrepancy between statistics (count) in the k6 end of test summary report and Dynatrace statistics. Previous test was conducted with the push interval as 100ms. So reducing this further to see if there will be any improvement.
=> [QA-142] Reduced push intervals of StatsD and OTEL to 10ms

deploy/Dockerfile
Investigation of the discrepancy between k6 and dynatrace statistics
- Increased K6_STATSD_BUFFER_SIZE to 100 (Default 20)
- Increased K6_STATSD_PUSH_INTERVAL and OTEL_METRIC_EXPORT_INTERVAL to 100 milliseconds.
---
No improvement observed in the results after reducing the push intervals from 100ms to 10ms.
Increasing the buffer size is to check if there is any difference.
Both the changes have been tested locally and we did not see any difference between the statistics in k6 and the statistics in dynatrace.
---
- [K6 Documentation](https://k6.io/docs/results-output/real-time/statsd/)
- #120 
- #118 
- #117 
- #114 
- #113 
- #110 
- #109 
- #100 
- #98
- #55
- #49
=> [QA-142]: Increasing StatsD buffer size and push intervals

deploy/scripts/src/accounts/test.ts
Updated the workload model of the account management scenarios
- Target load -  10 iterations per second
- Ramp up duration - 15 minutes
- Steady state - 30 minutes
---
This is the proposed workload model for initial performance tests for Accounts.
=> [QA-41]: Updated workload model for Account Management scenarios

deploy/scripts/src/common/test.ts
Changing the URL in the default test script to a non-production URL
- Changed URL from `https://account.gov.uk/` to `https://home.build.account.gov.uk/` in the default `deploy/scripts/common/test.js` test script
---
Performance test scripts should not be making calls against Production sites
=> [QA-215] Change default testing URL

deploy/template.yaml
Adding a debug statement to see if UDP packets are being dropped on localhost
- Add `ifconfig lo` statement to the post-build stage of the BuildSpec
---
To pinpoint the issue of some metrics being lost in the reporting pipeline
---
- #122
=> [QA-142] Network interface debug

deploy/Dockerfile
Bump `node` version in `deploy/Dockerfile` from `16-alpine3.16` to `16-alpine3.18`
=> [QA-234] Bump node from 16-alpine3.16 to 16-alpine3.18 in deploy/

.github/workflows/feature-branch-publish.yaml, deploy/template.yaml
Using the `di-devplatform-upload-action-ecr` without container signing to deploy to development environments
- `.github/workflows/feature-branch-publish.yaml` - Copied scripts from `di-devplatform-upload-action-ecr@1.0.2` and removed container signing
- `deploy/template.yml` - Added `dev` to the allowed values for environments
---
Deployments to development environment are currently failing as we cannot run container signing in dev environments
---
- #143 
- [di-devplatform-upload-action-ecr@1.0.2](https://github.com/alphagov/di-devplatform-upload-action-ecr/releases/tag/1.0.2)
=> [QA-224] Removing container signing

deploy/Dockerfile
Change the Dockerhub repository of the k6 image.
- `deploy/Dockerfile` - Changed the k6 image from `loadimpact/k6` to `grafana/k6`
---
The `loadimpact` Dockerhub repository is being deprecated in future releases in favour of the `grafana` org
=> [QA-237] Update k6 Docker repo

deploy/template.yaml
Adding a portion of the AWS stack ID to end of the test results S3 bucket name
> **Note** 
> This was deployed to development and the s3 bucket with the new name was created
>
> ![image](https://github.com/alphagov/di-devplatform-performance/assets/110121463/8e6caa4d-babf-48a3-a7b7-5915ad78ebf1)
- Changed bucket name:
- From: `${AWS::StackName}-test-results`
- To: `${AWS::StackName}-test-results-<twelve_digit_stack_id>`
---
Buckets deployed to production and non-production would end up with the same name, this adds a portion of the stack ID to the end of the bucket name for global uniqueness 
---
- #149
=> [QA-239] Make S3 bucket name globally unique

deploy/scripts/README.md
Minor documentation update
- Corrected the environment flag to `SCENARIO`
- Updated the location of the link to the `load-profiles.ts` utility
---
Typo in the scenario flag, and the link to the utility file was incorrect
=> [QA-240] Fix typo in SCENARIO flag documentation

deploy/template.yaml
Add a sleep time to the post-build to allow time for the latest OLTP metrics to flush
- Added a 2 minute sleep time to the post-build
---
The OpenTelemetry does not support a graceful shutdown, so when the `SIGTERM` is sent it immediately stops collecting/sending metrics. This means that any metrics at the end of the test are being lost, as the collector only exports every 1 minute at a minimum.
---
- #55
=> [QA-142] Add sleep time to post-build

deploy/scripts/.eslintrc.json, deploy/scripts/package-lock.json, deploy/scripts/package.json
Reverts alphagov/di-devplatform-performance#171
=> Revert "Bump eslint-config-standard-with-typescript from 35.0.0 to 36.0.0 in /deploy/scripts"

deploy/Dockerfile, deploy/otel-config-template.yaml, deploy/template.yaml
Reverts alphagov/di-devplatform-performance#124
The Dynatrace extension significantly impacted load injector performance:
| StatsD | xk6 Dynatrace Extension |
|--|--|
|![image](https://github.com/alphagov/di-devplatform-performance/assets/110121463/eafb64f6-a581-4f3f-97df-0bc3557a4d9e)|![image](https://github.com/alphagov/di-devplatform-performance/assets/110121463/ec28beb3-bf9c-40fc-8357-aaf4fc41cb83)|
CPU Utilisation for the Dynatrace Extension on the same load test was around 5x higher than using StatsD and OpenTelemetry combined, and memory utilisation was also slightly higher. Metrics also stopped being send to Dynatrace after 6 minutes into the test.
For these reasons, I propose we stick to StatsD output option for now
=> Revert "[QA-142] Replace Statsd with Dynatrace Output Extension"

.github/CODEOWNERS
Adding CODEOWNERS definition for the BTM and TxMA folders
- `/deploy/scripts/src/btm` – @alphagov/di-billing-and-transaction-monitoring
- `/deploy/scripts/src/txma` – @alphagov/digital-identity-txma
---
These are new team folders which do not currently have the code owners defined
---
- These folders were added in #162
=> [QA-248] CODEOWNERS for BTM and TxMA folders

deploy/scripts/src/cri-kiwi/test.ts
Added two new BE requests for covering the CIC journey
- Added B01_CIC_06_SendAuthorizationCode POST for obtaining the access_token
- Added B01_CIC_07_SendBearerToken POST for obtaining the JWT
---
To validate the CIC journey
---
[QA-250]: https://govukverify.atlassian.net/browse/QA-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QA-250] Added 2 BE requests for CIC 

deploy/scripts/README.md, deploy/scripts/src/cri-lime/test.ts, deploy/scripts/src/cri-orange/address/test.ts, deploy/scripts/src/cri-orange/kbv/test.ts, deploy/scripts/src/cri-orange/utils/config.ts, deploy/template.yaml
Updated the approach for using environment names in Orange and Lime CRI scripts
- Added single ENVIRONMENT variable which is used across each script instead of each scenario.
- Updated CF template to add the environment variable and remove the entries from parameter store section 
- Updated Readme to include instructions.
---
To simplify the usage of environment name across scripts and reduce the API calls to SSM parameter store in the perf test AWS account.
=> [QA-255]: Update the approach for using environment names

deploy/scripts/src/authentication/test.ts
Add a check if the new page to accept updated terms and conditions is displayed, and accept them.
- Added checks for the new page on SMS and Auth App branches
- Added an additional step to accept the updated terms and conditions
---
The sign-in journey has a new additional step
=> [QA-256] Accept new terms when signing-in in Authentication script

deploy/template.yaml
Removing noisy debug statements and adding some console prints to indicate stages in the post-build
- Removed `cat otel.log` and `ifconfig lo` debug statements for OpenTelemetry collector
- Added `echo` commands to show stages of uploading the file to s3 and shutting down the collector
---
The debug statements do not indicate any errors causing this issue, and are adding noise to the end of build logs
---
- #130 
- #100
=> [QA-142] Remove metrics debug statements

deploy/scripts/src/authentication/test.ts
Updated the load profile of sign up scenario
- Updated the load profile of sign up scenario as described in the volumetric plan,
---
To conduct initial stress tests for Auth based on the load profile defined in the NFRs
---
- [Performance Test Volumetric Plan](https://docs.google.com/spreadsheets/d/1N8-xvuj013E58T9mdrG5p0e78lEK2ks2U2QPrZ32HtY/edit?usp=sharing)
- [Performance Test NFRs](https://govukverify.atlassian.net/wiki/spaces/DID/pages/3295084564/Performance+SLAs+Performance+Efficiency+SLAs+Incident+Management+Recovery)
=> [QA-17] Updated load profile for Authentication scenarios

deploy/scripts/src/accounts/id-reuse.ts
Updated load target for ID - Reuse
- It will ramp up in 15 min to 1900 iterations/s and will have a steady state at 1900 iterations/s for 30mins
---
To respect the NFRs
---
=> [QA-265] Updated load target for ID - Reuse

deploy/template.yaml
Added a space between colon and quotation mark
- Added a space between colon and quotation mark in template yaml for one of the parameter in parameter-store
---
For the script to be run from CodeBuild
---
[QA-266]: https://govukverify.atlassian.net/browse/QA-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QA-266] Added a space between colon and quotation mark in template.yaml

.github/workflows/pre-merge-checks.yml
Adding a trigger to the pre-merge PR checks to also run on merge queues
- Added `merge_group:` trigger to `.github/workflows/pre-merge-checks.yml`
---
To enable the Merge Queue we need to run checks on the merge group temporary branches. This will simplify merging multiple pull requests at once.
---
- [GitHub Merge Queue Documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
=> [QA-270] Update PR Checks to Include Merge Queues

deploy/scripts/src/mobile/testSteps/backend.ts, deploy/scripts/src/mobile/testSteps/frontend.ts
Added transactionDuration equal with request endTime - startTime for FE E2E test
- all methods used in the FE E2E test: capturing startTime/endTime before/after request and if assertions are passing changed transactionDuration to equal request endTime - startTime for FE E2E test
---
We are interested in the total duration of all requests, including redirects, so in our scripts, we have been adding a custom response time duration metric to track this.
Duration:
=> DCMAW-6068: Mobile - add custom duration Trend for FE E2E script

deploy/scripts/src/mobile/testSteps/backend.ts
Added transactionDuration equal with request endTime - startTime for BE E2E test
- all methods used in the BE E2E test: capturing startTime/endTime before/after request and if assertions are passing changed transactionDuration to equal request endTime - startTime for BE E2E test
---
We are interested in the total duration of all requests, including redirects, so in our scripts, we have been adding a custom response time duration metric to track this.
Duration:
=> DCMAW-6068: Mobile - added duration trend metric to BE requests

deploy/scripts/src/accounts/id-reuse.ts, deploy/scripts/src/accounts/test.ts, deploy/scripts/src/authentication/test.ts, deploy/scripts/src/cri-kiwi/test.ts, deploy/scripts/src/cri-lime/test.ts, deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/kbv.ts, deploy/scripts/src/ipv-core/test.ts, deploy/scripts/src/mobile/testSteps/backend.ts, deploy/scripts/src/mobile/testSteps/frontend.ts
Changing the definition of the `duration` custom metric to specify that this is a time value (not unit-less)
**Before**
> ![image](https://github.com/alphagov/di-devplatform-performance/assets/110121463/abf9b943-743d-477c-8185-f21054549e2d)
**After**
> ![image](https://github.com/alphagov/di-devplatform-performance/assets/110121463/9484996f-a81d-45c5-90f1-525d6a644eb5)
- Replaced all `new Trend('duration')` with `new Trend('duration', true)`
---
The 'duration' metric measures response time and currently it is being recorded as a unit-less metric. This change specifies that this value is a time (and the unit is milliseconds)
---
- [k6 Trend Documentation](https://k6.io/docs/javascript-api/k6-metrics/trend/)
=> [QA-275] Specify unit for 'duration' custom metric

.github/workflows/pre-merge-checks.yml
Add a manual trigger to the the pre merge check github action
- Add a `workflow_dispatch trigger` to `.github/workflows/pre-merge-checks.yml`
---
Pre-commit caches the environments for use in the pre merge checks, but as this action has not been run on the main branch ever, it is not using the cache when running checks on new branches or merge queues. This is causing a slowdown in PR checks as cache misses result in pre-commit needing to create several new environments from scratch which can take 1-2 minutes. This PR adds a manual trigger to this action so we can trigger a cache save on main.
---
- [Github Caching Documentation](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
=> [QA-280] Add manual trigger for pre-merge-checks

deploy/template.yaml
Update build ID tags to use the CodeBuild build number in place of the CodeBuild build ID. This changes the tag we are using for metrics from an ID of the form `LoadTest-perftest:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` to just using the build incremental numbers (e.g. `42` or `128`)
- `deploy/template.yaml`: Change `CODEBUILD_BUILD_ID` to `CODEBUILD_BUILD_NUMBER`
---
This simplifies the metric tags from a very long UUID to a more memorable 2-4 digit number.
---
- [AWS CodeBuild Environment Variables Documentation](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html)
=> [QA-278] Update Build ID Metric Tag

deploy/template.yaml
Adding permissions to the Performance Test Execution role to be able to call SQS queues in the TxMA Event Processing Account
- `deploy/template.yaml`: Added TxMA account ID to mappings, and added the account's SQS queues to the SQS permissions on the execution role policy. (Also fixed a typo in the `PerformanceTesterPolicy` name)
---
These changes are being made to enable performance testing of SQS queues for TxMA
---
- #180 
- #220
=> [QA-281] Add TxMA SQS Permissions

deploy/template.yaml
Add permissions to call KMS in TxMA
- `deploy/template.yaml`:
- Added the TxMA KMS keys to the execution role permisssions
- Updated the TxMA SQS queue resource to enforce the `event-processing-` prefix
---
To facilitate testing of TxMA SQS queues
---
- #232 
- #220 
- #180 
- PLAT-2035
=> [QA-281] Add TxMA KMS Permissions

deploy/scripts/src/accounts/data/summariseSubjectID.csv, deploy/scripts/src/accounts/id-reuse.ts
Subject ID parameterization in ID reuse scripts
- Generating unique subject ID using uuid() in persist ID scenario.
- Using a test data file to use random subject IDs in the summarise VC scenario.
---
To ensure data used for each persist VC call is unique. Additionally, to ensure that the summarise VC call is retrieving VCs for multiple IDs.
---
=> [QA-273] : Subject ID parameterization for ID reuse scripts

deploy/Dockerfile, deploy/reporting/slack.sh, deploy/template.yaml
Add script to post notifications to Slack at the start and end of test. At the start of the test this script will post an initial 'In Progress' message, and after it will edit the message to update with the status of the build.
- `deploy/reporting/slack.sh` - Add a bash script which will either post an initial slack message, or update the message based on the current Build status
- `deploy/template.yaml` - Add commands to call the bash script (as source), and environment variables for the Slack OAuth token and the Slack channel to post into
- `deploy/Dockerfile` - Installed `curl` and `jq` to agent image to facilitate calling the Slack API from command line and parsing the result
---
To provide notifications of performance tests starting, and give quick links to monitoring dashboard to …
=> [QA-213] Add Slack notifications to build commands

deploy/template.yaml
Add an environment variable to specify the location of the slack bash script
- `deploy/template.yaml` - Add `REPORTING_DIR` environment variable for script location, and use it in the slack commands
---
The relative directory previously specified was incorrect
---
- #236
=> [QA-213] Fix Slack script path

deploy/scripts/src/mobile/authorize.test.ts
Added a load profile to the authorize test accordingly with the ones in the ticket:
- A 15 minutes volume ramp up from 1 request per second to 100 requests per second (0.1 t/s/s NFR)
- A 30 minutes period of sustained volume at 100 requests per second
- authorize.ts: added load profile
---
The full FE E2E test will test the performance of the FE endpoints, simulating concurrent users following the Frontend journey.
---
=> DCMAW-5597: Added load profile 

deploy/scripts/src/spot/requestGenerator/spotReqGen.ts
Fix audience ID and client ID values in SPOT request
- According to logic in SPOT validation function, the value of `out_audience` should be equal to the value of `log_ids.client_id`. 
---
To fix the errors in SPOT request processing in build environment.
=> [QA-287]: Fix Audience ID and Client ID

deploy/scripts/src/mobile/frontend-e2e.test.ts
Added a load profile to the frontend E2E test that adheres to the following volumes:
- A 15 minutes volume ramp up from 1 request per second to 100 requests per second (0.1 t/s/s NFR)
- A 30 minutes period of sustained volume at 100 requests per second
- update the list of profiles `frontend-e2e.test.ts` to include a load profile
- preAllocatedVUs was calculated by running the `smoke` profile 3 times and collecting an average from those runs
- maxVUs was calculated by using the value provided by the NFR (2.5 seconds per user-facing request) and multiplying that by the amount of user-facing requests made during the journey.
---
A full FE E2E test will test the performance of the FE endpoints, simulating concurrent users following the Frontend journey.
[DCMAW-5598]: …
=> DCMAW-5598: Add load profile for the frontend E2E journey

deploy/scripts/src/authentication/test.ts, deploy/template.yaml
Using `Response.submitForm()` in place of the `http.post()` where applicable
This has been validated with smoke tests locally
- Replaced `http.post()` instances with `Response.submitForm()` in places where we are submitting the form from the previous request response. Also removed any input values which are set to the default.
- Removed the now unused `ACCOUNT_BASE_URL` environment variable, the redirect from the stub handles this instead
- Removed unused `getCSRF()` and `getPhoneNumber()` utility functions
---
To simplify the test script and reduce unnecessary hard-coded form input values
---
- [`Response.submitForm()` documentation](https://k6.io/docs/javascript-api/k6-http/response/response-submitform/)
=> [QA-292] Use `submitForm()` in Authentication script

deploy/scripts/src/ipv-core/test.ts
Add name tag to all the HTTP requests
- Added tag for all the http.get and submitForm() requests in both the scenarios (passport and DL).
---
Without tagging, k6 generates considers all HTTP requests (with unique values in the URL) as unique time series. This resulted in high load injector utilisation causing the previous load test to fail.
=> [QA-297] : IPV core - Add name tag to HTTP requests

deploy/scripts/src/common/utils/request/static.ts
Add a parameter to static resource batch calls to discard the response body
- Added `responseType: 'none'` to the batch request definition
---
The responses are consuming large amounts of memory in each VU, and we are not using the response bodies for static resource calls 
---
- [k6 Params documentation](https://k6.io/docs/javascript-api/k6-http/params/)
=> [QA-299] Discard response bodies of static resource calls

deploy/scripts/src/common/utils/request/static.ts
Restrict the list of static resources to those in the `*.account.gov.uk` domain
- Filter resource URLs programmatically found for static resources only to those that include `.account.gov.uk` in the string
---
All systems under test will be under the `*.account.gov.uk` domain, so any other resources will be either inaccessible to the egress firewall rules, or will be inadvertently testing a third party system
=> [QA-301] Limit static resources to `.account.gov.uk`

deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/kbv.ts
Using `Response.submitForm()` in place of the `http.post()` where applicable in CRI Orange test scripts.
This has been validated with smoke tests locally
- Replaced `http.post()` instances with `Response.submitForm()` in places where we are submitting the form from the previous request response. Also removed any input values which are set to the default.
- Removed unused `getCSRF()` and `getAddressDetails()` utility functions
---
To simplify the test script and reduce unnecessary hard-coded form input values
---
- [`Response.submitForm()` documentation](https://k6.io/docs/javascript-api/k6-http/response/response-submitform/)
=> [QA-295] Use `submitForm()` in CRI Orange scripts

deploy/scripts/src/spot/test.ts
Added a stress profile for SPOT scenario.
- Added a stress profile for SPOT scenario with a target and steady state load of 500 iterations per second.
---
To conduct a stress test for SPOT at 500 iterations per second.
---
=> [QA-312]: Add stress profile for SPOT

deploy/scripts/src/common/unit-tests.ts, deploy/scripts/src/common/utils/request/static.ts
Updated the calls in `utils/request/static.ts` to use the `URL` constructor to handle resolving URLs
- `utils/request/static.ts` - Replaced the `resolveUrl()` function with calls to `URL()` constructor with the two arguments `url` and `base`
- `common/unit-tests.ts` - Removed the unit tests for `resolveUrl()` as these are now being handled by `URL` and the remaining functions in `utils/request/static.ts` do not provide an easy way to test without stubbing out the http calls
---
This simplifies the utility by not having to handle the URL resolution ourselves, and also handling the URLs as `URL` types and not strings reduces some of the conversion that was previously taking place
---
- [Mozilla URL documentation](https://developer.mozilla.org/en-US/docs/Web/API/URL)
=> [QA-311] Resolve URLs using `URL` when discovering static resources

deploy/template.yaml
Allow Production Control Tower Tester/PowerUser/Admin roles to assume the Performance Tester execution role
- `deploy/template.yaml` - Added the Tester/PowerUser/Admin role ARNs to the trust policy on the `PerformanceTesterRole` to allow them to be assumed
---
Control Tower users who have access to the production tester account or above need to be able to assume the Performance Tester role in order to test SQS scripts locally
=> [QA-310] Allow Control Tower roles to assume execution role

deploy/scripts/src/btm/test.ts, deploy/scripts/src/common/utils/jslib/aws-sqs.d.ts, deploy/scripts/src/cri-kiwi/ipvr.ts, deploy/scripts/src/spot/test.ts, deploy/scripts/src/txma/test.ts
Removed the Promise return types from the `SQSClient.sendMessage()` function, and updated the relevant tests scripts
These changes were tested locally for the SPOT test script
- `common/utils/jslib/aws-sqs.d.ts`: Removed `Promise<>` from return type of `SQSClient.sendMessage()` function
- `btm/test.ts`, `cri-kiwi/ipvr.ts`, `spot/test.ts`, `txma/test.ts`: Removed `Promise` from return types and removed `async/await`
---
Tests were throwing errors with message `Uncaught (in promise) TypeError: Value is not an object: null` when trying to call `SQSClient.sendMessage()` as a `Promise`, the function actually directly returns an object.
---
- [k6 jslib `SQSClient.sendMessage()` documentation](https://k6.io/docs/javascript-api/jslib/aws/sqsclient/sqsclient-sendmessage/)
=> [QA-313] Fix SQS call incorrect Promise types

deploy/template.yaml
Add permissions to the role to call SQS and KMS resources in the ipv return account
- `deploy/template.yaml`
- Added the IPVR AWS Account ID to the map
- Added IPVR KMS ARN wildcard to the execution role permissions
- Added IPVR SQS ARN wildcard to the execution role permissions
---
To allow testing of IPVR journeys
---
- #220 
- #232 
- #233 
- #234
=> [QA-315] Add IPVR SQS permissions

deploy/template.yaml
Updating Control Tower role names in the CloudFormation template
- `deploy/template.yaml` - Updated the Control Tower roles names from `...-power-user_...` to `...-poweruser_...` and `...-tester_...` to `...-testers_...`
---
The actual Control Tower role ARNs are different to those specified in the template and need to be updated for the assume role to work for those two Control Tower roles
---
- #290
=> [QA-310] Fix Control Tower Role ARNs

deploy/template.yaml
Fix the ARN of the IPVR SQS queue in the template
- `deploy/template.yaml`: `kms` -> `sqs`
---
The SQS arn mistakenly has KMS in it. Fixes the bug introduced in #293 
---
- #293
=> [QA-315] Fix IPVR SQS ARN permissions

deploy/scripts/src/accounts/test.ts
Updated load profile for Accounts - Validate User scenario to carry out low volume test
Load profile:
- Max VUs: 300
Ramp up stage:
- Target: 10
- Duration: 3 minutes
Steady State:
- Target: 10
- Duration: 6 minutes
---
To carry out low volume tests to test to test the concurrent user production issue
---
- [OLH-1093](https://govukverify.atlassian.net/browse/OLH-1093)
[OLH-1093]: https://govukverify.atlassian.net/browse/OLH-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated load profile for Validate User scenario for low volume test

deploy/template.yaml
Add permissions to execution role invoke the contra-indicators lambda
- `deploy/template.yml`: Added `lambda:InvokeFunction` permissions to the execution role for the contra-indicators build account
---
In order to performance test the CIMIT system
---
- #180
=> [QA-334] Add permissions to invoke contra-indicators lambda

deploy/scripts/src/ipv-core/test.ts
Reduced the think time between groups and increased max VUs in IPV core script
- Reduced the think time between groups to a random value between 0 - 2 seconds (0-3 seconds previously).
- Increased the maximum VUs to 7500
---
Load injector ran out of memory during previous stress so the idea is to reduce the think time to allow higher volumes. Additionally, we saw maximum VUs initialised for last test so increasing that to generate higher load.
=> [QA-335] IPV Core - Reduce think time and increase max VUs

deploy/scripts/src/cri-kiwi/ipvr.ts, deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts, deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
Updated IPVR script for smoke test of all three events
- Updated the user ID creation approach to ensure same user ID is added for all 3 events in the `allEvents` scenario.
- Updated `timestamp` type to `number`
---
Smoke test for IPVR was failing as `timestamp` was assigned `string` type. Additionally, each VU was generating same user ID  in every iteration. Changes have been done to tackle both the issues.
=> [QA-338] : Updated IPVR scripts for smoke tests

deploy/template.yaml
Add permissions to send messages to BTM Staging SQS queue
- `deploy/template.yml`: Added BTM Staging account ID to mapping, and added SQS permissions for that Account for the execution role
---
In order to test BTM at the SQS queue entrypoint
---
- #220
- #232 
- #293
- #295
=> [QA-342] Add BTM SQS permissions

deploy/scripts/src/spot/test.ts
Add a low volume profile for SPOT scenario.
- Added a low volume profile with target load of 50 iterations per hour.
---
To conduct a low volume test before and after merging the changes in [QA-346](https://govukverify.atlassian.net/browse/QA-346)
---
- [QA-346](https://govukverify.atlassian.net/browse/QA-346)
[QA-346]: https://govukverify.atlassian.net/browse/QA-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QA-346]: https://govukverify.atlassian.net/browse/QA-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QA-347]: Add low volume profile for SPOT

deploy/Dockerfile, deploy/template.yaml
Replacing the k6 default image with xk6 with the statsd output extension
- `deploy/Dockerfile`: Added xk6 build using the output-statsd extension to create the k6 binary
- `deploy/template.yaml`: Updated the output flag on the `k6 run` command
---
In the k6 [v0.47.0 release](https://github.com/grafana/k6/releases/tag/v0.47.0) the statsd output option is now deprecated, and planned to be removed in a future release. This has now been moved to a xk6 extension, this PR ensures future releases will be compatible with our current reporting pipeline
---
- #175 
- #124 
- #29
=> [QA-346] Use xk6 extension for statsd output

.github/CODEOWNERS
Add the new `@govuk-one-login/performance-testers` to the CODEOWNERS file
- `.github/CODEOWNERS`: Add `@govuk-one-login/performance-testers` in addition to existing `@alphagov/digital-identity-performance-test` team
---
This is in preparation for repository migration to govuk-one-login
=> [QA-350] Update CODEOWNERS with new organisation team

.github/CODEOWNERS, .github/workflows/feature-branch-publish.yaml, README.md, deploy/README.md, deploy/scripts/package.json, deploy/template.yaml
Update all references from `alphagov/di-devplatform-performance` to `govuk-one-login/performance-testing`
- `.github/CODEOWNERS`: Removed old `@alphagov/digital-identity-performance-test` team
- `.github/workflows/feature-branch-publish.yaml`: Updated references in comments
- `README.md` & `deploy/README.md`: Updated references in hrefs
- `deploy/scripts/package.json`: Updated repo name
- `deploy/template.yaml`: Updated repo name used in value
---
Repository was migrated between GitHub organisations and renamed
---
- #353
=> [QA-351] Update references from `alphagov/di-devplatform-performance` to `govuk-one-login/performance-testing`

.github/CODEOWNERS
Updating teams CODEOWNERS file
- `.github/CODEOWNERS`: Updated team names
---
After the migration from the `alphagov` organisations, there is a different set of teams
---
- #358 
- #353
=> [QA-352] Update CODEOWNERS teams

.github/workflows/publish.yaml
Switch over github action to new organisation repo
- `.github/workflows/publish.yaml`:
- Updated action from [`alphagov/di-devplatform-upload-action-ecr`](https://github.com/alphagov/di-devplatform-upload-action-ecr) to [`govuk-one-login/devplatform-upload-action-ecr`](https://github.com/govuk-one-login/devplatform-upload-action-ecr)
- Bump action version from `v1.0.2` to `v1.0.4`
---
Action repository has migrated organisations
---
- #358
=> [QA-358] Update `devplatform-upload` action location

deploy/scripts/src/btm/test.ts
Updated Timestamp type in the BTM script payloads
- Timestamp used in the BTM payload should be a number. In the current script, this is being sent as a string resulting in message failure in Lambda function processing.
---
To fix the error in clean Lambda function.
=> [QA-364]: Update timestamp type in BTM script

deploy/scripts/src/btm/test.ts
…functions
Removed iteration counter for individual events in BTM script
- (btm/test.js) Removed iterationsStarted.add(1) and iterationsCompleted.add(1) for sendEvent functions
---
Iterations Started and Iterations Completed metrics were being counted twice due to them being counted in both the sendEvent functions and the sendSQSMessage function, so one of these needed to be removed
---
=> [QA-366]: BTM - Removed Iteration Started and Completed counts from event type

deploy/scripts/src/spot/test.ts
Increase the target volume of SPOT stress test
- Increase the target volume of SPOT stress test to 1200 requests per second
---
To conduct the stress test in SPOT at 1200 per second.
=> [QA-367]: Increase SPOT stress test target to 1200

deploy/scripts/src/txma/test.ts
Edited the TxMA script to contain five load profiles with new volumetrics
[deploy/scripts/src/txma/test.ts]
Created five profiles with the following volumetrics:
• Smoke (1 iteration/second for 60 seconds).
• Low volume (ramping up to 30 iterations/second).
• Load (ramping up to 500 iterations/second).
• Stress (ramping up to 2000 iterations/second).
• Peak stress (ramping up to 5000 iterations/second).
---
To test the performance of TxMA against the NFRs.
=> [QA-368]: Updated profiles and volumetrics for txma/test.ts

deploy/scripts/src/accounts/test.ts
Update workload volumetric for load profile in OLH scenarios
- Reduce the target volume for OLH scenarios to 30 iterations per second.
- Removed unnecessary whitespaces.
---
To evaluate the performance of OLH scenarios at a lower volume since there are no relevant volumetric targets available.
=> [QA-369]: Update workload volumetric for OLH scenarios

deploy/scripts/src/cimit/test.ts
Added iteration count metric in CIMIT scenarios
- Added iteration started and iteration completed metrics in the 3 CIMIT scenarios (`putContraIndicators`, `getContraIndicatorCredentials`, `postMitigations`)
---
To count the number of started and completed iterations of CIMIT scenarios in performance tests.
=> [QA-376]: Added iteration count metric in CIMIT scenarios

deploy/scripts/.eslintrc.json, deploy/scripts/README.md, deploy/scripts/build.js, deploy/scripts/build.mjs, deploy/scripts/package.json
Enabling minification and removing source maps of transpiled test scripts. Also updated `build.js` to an `*.mjs` file
- Enabled esbuild `minify`
- Disabled esbuild `sourcemap`
- Converted `build.js` to `build.mjs`
---
These changes reduce the size of the output test script files, these files are copied into memory for every virtual user so it is important that these are as small as possible to reduce the memory usage on the load injector. The previous total `dist` output was about `~4.8MB` and now this has been reduced to `~2.7MB` with these changes.
---
- [esbuild minify](https://esbuild.github.io/api/#minify)
- [esbuild sourcemap](https://esbuild.github.io/api/#sourcemap)
=> [QA-377] Minify test scripts

.github/CODEOWNERS
Update the code owners team for Mobile
- `.github/CODEOWNERS`: Update mobile team from `@govuk-one-login/mobile-narwhal-team` to `@govuk-one-login/mobile-id-check`
---
Mobile's team name has changed on Github
---
- #104
=> [QA-383] Update Mobile codeowners

deploy/scripts/src/ipv-core/test.ts
Add a load profile to the IPV Core script for canary deployments and deployment testing
- `deploy/scripts/ipv-core/test.ts`: Added a `deployment` load profile, with targets for `passport`, `drivingLicence` and `idReuse` of `2`, `2` and `20` per second respectively over `30` mins (including `5` minutes ramp-up and ramp-down each)
---
To facilitate testing of canary deployments, we need to send volumes of traffic to the development environment using the IPV Core script for ~30 mins at a time
---
- #425
=> [QA-390] Load profile for canary testing

deploy/scripts/src/accounts/id-reuse.ts
Update Max VUs for Summarise VC stress profile
- Reduced Max VUs for Summarise VC stress profile from 20000 to 5000.
---
20000 VUs on a single load generator was causing resource contention on the load generator. Additionally, as per NFR calculations, the max VUs for this scenario should be 5000.
=> [QA-391]: Update Max VUs for Summarise VC stress profile

deploy/scripts/src/cri-lime/test.ts
Updated `deploy/scripts/src/cri-lime/test.ts` Drivers License scenario to increase the target stress test volume from 14 to 55.
[deploy/scripts/src/cri-lime/test.ts]
- increased the target stress test volume for the drivers license scenario from 14 to 55
---
to conduct a stress test of CRI-Lime Drivers License at a similar volume to CRI-Lime Passport.
---
=> [QA-392] Updating Target Volume for Stress Test of Lime-CRI Drivers License

deploy/scripts/src/cri-lime/test.ts
Updated the MaxVUs for the drivingLicence scenario of the stress test for CRI-Lime.
[deploy/scripts/src/cri-lime/test.ts]
- changed the MaxVUs for drivingLicence stress test from 411 to 1500.
---
To support the increase in target iterations from 14 to 55 to perform a performance stress test. 
---
=> [QA-393] Updating MaxVUs for CRI-Lime drivingLicence stress test

deploy/scripts/src/accounts/test.ts
Updated load profile of OLH Contacts Page scenario.
- Ramp up duration increased to 5 minutes.
- Steady state increased to 30 minutes.
---
To validate the fix provided for live incident through an extended duration volume test.
=> [QA-396]: Updated load profile of Contacts Page scenario in OLH

deploy/scripts/src/mobile/backend-e2e.test.ts, deploy/scripts/src/mobile/frontend-e2e.test.ts
The smoke scenario details for the FE E2E mobile scripts. 
- target of 1 request per second 
- 25m sustained volumes at 1 requests per seconds
- preAllocated VUs decreased to 15 
---
Migrate a Frontend stack in the Dev account from the DCMAW to Dev Platform VPC whilst a performance test is running. It is suggested that this performance test runs at low volumes, aiming at 1TPS per journey
---
- [DCMAW-7817](https://govukverify.atlassian.net/browse/DCMAW-7817) 
EVIDENCE:
[DCMAW-7817]: https://govukverify.atlassian.net/browse/DCMAW-7817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-7817: Added deploy scenario for mobile FE tests

deploy/scripts/src/mobile/README.md, deploy/scripts/src/mobile/backend-e2e.test.ts
Added the `deploy` profile to the BE journey mobile scripts. 
- added `deploy` profile to the `backend-e2e.test.ts` file. This profile is a `constant-arrival-rate` with 1 rate per second and a total duration of 25 minutes.
- readme file with the latest names of the environment variables.
Understand if our BE Lambda’s work with the Dev platform VPC, without making changes to our egress implementation.
- [DCMAW-7830](https://govukverify.atlassian.net/browse/DCMAW-7830) 
EVIDENCE:
[DCMAW-7830]: https://govukverify.atlassian.net/browse/DCMAW-7830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-7830: Added deploy scenario for mobile BE tests 

deploy/scripts/src/mobile/frontend-e2e.test.ts
Added the `incrementalLoad` profile to the FE journey mobile scripts. 
- added `incrementalLoad` profile to the `frontend-e2e.test.ts` file. This profile reflects the incremental ramp-up from the below picture:
Understand how our system is performing on different loads.
- [DCMAW-7830](https://govukverify.atlassian.net/browse/DCMAW-7830) 
EVIDENCE:
[DCMAW-7858]: https://govukverify.atlassian.net/browse/DCMAW-7858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCMAW-7830]: https://govukverify.atlassian.net/browse/DCMAW-7830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-7858: Added incremental load scenario

deploy/scripts/src/mobile/backend-e2e.test.ts, deploy/scripts/src/mobile/frontend-e2e.test.ts
Addition of a load profile
- Targets 6TPS at sustained load after a ramp up period
---
- To support a new performance test using new forecasted volumes
---
=> Add new load profile for the mobile tests

deploy/scripts/src/mobile/backend-e2e.test.ts, deploy/scripts/src/mobile/frontend-e2e.test.ts
A change to the volumetrics in the load profile
- Change from 6 to 10 TPS for the selfAsessement load profile
- Reduction of peak load from 30 mins to 10 mins for earlier feedback
---
---
=> Mobile: increase load profile TPS

deploy/scripts/src/mobile/backend-e2e.test.ts, deploy/scripts/src/mobile/frontend-e2e.test.ts
Changed load profile from 100 to 40 TPS and raised the load window to full 30m
- changed BE and FE load profile TPS to 40
- changed BE and FE load profile maxVUs and preallocatedVUs
- raised BE and fe load profile window to full 30 m
---
Target a lower NFR, given this will give us short-term benefits we can deliver sooner into Production.
---
- [DCMAW-7858](https://govukverify.atlassian.net/browse/DCMAW-7858) to any relevant documentation or relevant pull requests
[DCMAW-7858]: https://govukverify.atlassian.net/browse/DCMAW-7858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-7858: Changed the load profile from 100 to 40 TPS and raised load window

deploy/scripts/src/mobile/frontend-e2e.test.ts
Added the `incrementalSmallVolumes` profile to the FE journey mobile scripts. 
- added `incrementalSmallVolumes` profile to the `frontend-e2e.test.ts` file. This profile reflects the incremental ramp-up from the below picture:
Understand how our system is performing on different normal loads.
- [DCMAW-7830](https://govukverify.atlassian.net/browse/DCMAW-7830) 
EVIDENCE:
[DCMAW-7858]: https://govukverify.atlassian.net/browse/DCMAW-7858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCMAW-7830]: https://govukverify.atlassian.net/browse/DCMAW-7830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-7858: Added incremental small volumes scenario

deploy/scripts/src/cimit/test.ts
Updated the load profile for `putContraIndicators` scenario in the CIMIT script
- updated the load profile of `putContraIndicators` scenario in `src/cimit/test.ts` to have maxVUs of 1200 and target load of 400 iterations per second.
---
to perform a load test for CIMIT with volumes according to the NFRs.
---
=> [QA-409] Updating the load profile for putContraIndicators scenario in CIMIT

.pre-commit-config.yaml
Bump pre-commit hook versions: `pre-commit autoupdate`
- [`pre-commit/pre-commit-hooks`](https://github.com/pre-commit/pre-commit-hooks): from `v4.2.0` to `v4.5.0`. [Release notes](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v4.5.0)
- [`Yelp/detect-secrets`](https://github.com/Yelp/detect-secrets): from `v1.2.0` to `v1.4.0`. [Release notes](https://github.com/Yelp/detect-secrets/releases/tag/v1.4.0)
- [`Lucas-C/pre-commit-hooks`](https://github.com/Lucas-C/pre-commit-hooks): from `v1.1.13` to `v1.5.4`. [Release notes](https://github.com/Lucas-C/pre-commit-hooks/releases/tag/v1.5.4)
- [`alessandrojcm/commitlint-pre-commit-hook`](https://github.com/alessandrojcm/commitlint-pre-commit-hook): from `v8.0.0` to `v9.11.0`. [Release …
=> [QA-415] Update pre-commit dependencies

.pre-commit-config.yaml, deploy/template.yaml
Reverting the Access Control changes made to the s3 results bucket to prevent deployment failures
- Revert s3 bucket `AccessControl` setting 
- Added ignore warning `W3045` to cfn-lint pre-commit hook
---
Updates to the cfn-lint hook have added a warning for an access control setting which has been moved to legacy. The s3 bucket we have was created with these legacy settings, so this cannot be removed from the IaC and updated in place without a deployment error. Ignoring the warning and reverting the access control setting to it's legacy configuration fixes this deployment issue.
---
- #480
- [AWS Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-accesscontrol)
=> [QA-418] Revert s3 Bucket ACL settings

deploy/scripts/src/ais/data/retrieveInterventionUser.csv, deploy/scripts/src/ais/requestGenerator/aisReqGen.ts
Script updates for AIS smoke testing
- Corrected the value for `event_id` field in the payload.
- Added 5 records for smoke testing of the `RetrieveIV` scenario in the pipeline
---
To conduct smoke testing of both Persist and Retrieve IV scenarios.
=> [QA-408]: Script updates for AIS smoke testing

deploy/scripts/src/cri-lime/test.ts
Add two load profiles for the Passport CRI script 
- Added `bau1x` load profile
- 5 min ramp ⤴ 1x prod vol
- 10 min steady @ 1x prod vol
- 5 min ramp ⤵ 0
- Added `bau5x` load profile
- 5 min ramp ⤴ 1x prod vol
- 5 min steady @ 1x prod vol
- 10 min ramp ⤴ 5x prod vol
- 5 min steady @ 5x prod vol
- 5 min ramp ⤵ 0
- Changed `lowVolumeTest` load profile name to `lowVolume`
---
Testing BAU load for observability monitoring.
---
- [Confluence Approach Documentation](https://govukverify.atlassian.net/l/cp/pM0ABy0o)
=> [QA-412] Add BAU load profiles for Passport CRI

deploy/scripts/src/spot/test.ts
Increased the SPOT stress test to a target volume of 2000 iterations per second with MaxVUs to 6000.
- changed target volume to 2000r/s in SPOT stress test
- changed MaxVUs to 6000 in SPOT stress test
---
to conduct a stress test of SPOT at 2000r/s
=> [QA-423] - Increasing SPOT stress test volume to 2000r/s

.github/workflows/feature-branch-publish.yaml, .github/workflows/pre-merge-checks.yml, .github/workflows/publish.yaml
Pin GitHub Actions to specific SHAs
- Changed all GitHub Action versions using to semver to pin to specific SHAs instead with the semver tag as a comment
---
Improve security of GitHub Actions and prevent malicious code from executing by changing the tag to a different commit. Align to the GDS way.
---
- [GDS Way documentation](https://gds-way.digital.cabinet-office.gov.uk/standards/source-code/use-github.html#using-github-actions-and-workflows)
- [GitHub documentation](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-release-management-for-your-custom-actions)
=> [QA-425] Pin GHAs to specific SHAs

deploy/scripts/src/authentication/test.ts
Split OIDC and Auth calls in `sign-up` and `sign-in` scenarios
- Split OIDC and Auth calls in `sign-up` and `sign-in` scenarios.
- Modified tag names.
- Corrected the position of the `iterationCompleted` metric 
---
To evaluate the performance metrics of both Orchestration and Authentication calls separately.
=> [QA-424]: Split OIDC and Auth calls in Auth scenarios

deploy/scripts/src/authentication/test.ts
Increases the Authentication SignIn scenario low volume test profile to 30 iterations per second from 8 iterations per second. 
- increase target volume for the low volume test profile to 30r/s
---
to run a low volume test for Auth SignIn at 30r/s
=> [QA-427] Increasing Auth SignIn low volume test to 30r/s

deploy/scripts/src/accounts/test.ts
Updated `Change Email` scenario based on latest changes.
- Added `formSelector` in each `submitForm()` call
- Modified the `sign-out` to a `submitForm()`
---
`sign-out` is now a form so the response of each page contains this additional form. We need to use `formSelector` to accurately call the correct form for each page.
=> [QA-431]: Updated script for change email scenario

deploy/scripts/src/ais/test.ts
changes the AIS retrieveIV scenario, lowVolumeTest target volume from 100 iterations per second to 1000 iterations per second; and increase the maxVUs to 3000. 
- change the target volume for lowVolume test to 1000 iterations per second for AIS retrieveIV scenario.
- change the maxVUs to 3000.
---
To conduct a low volume test for AIS retrieveIV scenario at 1000r/s. 
---
=> [QA-434] Update low volume AIS retrieveIV scenario target volume to 1000r/s

deploy/scripts/src/accounts/id-reuse.ts, deploy/scripts/src/ipv-core/test.ts
Added data creation load profiles for IPV core and ID reuse scripts
- IPV Core - Data creation load profile to run `passport` scenario and generate 50k user ids for which identity has been proven. These 50k user ids will be used in the IPV core `IDReuse` scenario.
- Bravo - Data creation load profile to run `Persist VC`scenario for 50k users. These 50k users will be used for `Summarise VC` load test. 
---
To use these profiles for bulk test data creation for load tests.
=> [QA-436]: Added data creation profiles for IPV core and Bravo scripts

deploy/scripts/src/accounts/vc-storage.ts
Remove Retrieve VC step from Persist scenario
- Remove Retrieve VC step from Persist scenario
---
Retrieving a VC immediately after creating it is not a real world behaviour and is leading to HTTP-404 errors in high volume tests.
=> [QA-440]: Remove Retrieve VC step from Persist scenario

deploy/scripts/src/cri-kiwi/BAV.ts
Change workload of BAV CRI load test for next test run
- Increased ramp up to 15m and steady state time to 30m for test target 10 (new NFR)
- Removed load profile of test target 30 (old NFR)
---
The next test run should have an increased ramp up time as 10j/s is the NFR (based on the expected volume of 6.2% of new identity attempts using BAV CRI)
=> BAV CRI - Increase ramp up time

deploy/scripts/src/ais/test.ts
Increased stress test target to new NFR value for AIS
- Increased stress test target volume from 3,800 to 5,700 in AIS script
---
To carry out a stress test at the new NFR value target load
---
=> AIS - Increased stress test target to new NFR

deploy/scripts/src/ais/test.ts
Added tag to step in AIS test to reduce logging
- Added tag to step in AIS Retrieve Intervention script
---
The results.gz file from the last stress test was too large to open so we could not get the summary metrics. Adding the tag will hopefully decrease the size of the logs.
=> [QA-448] AIS - Add name tags to metrics

deploy/scripts/src/authentication/test.ts
increase the target volume from 200r/s to 500r/s in the load profile for Auth signIn. 
- increase the target volume in the Auth signIn load profile to 500r/s
- increase the maxVUs to 15,000
---
to run a performance test of Auth signIn at 500r/s. 
---
=> [QA-453] Increasing target volume of Auth sign-in load test to 500r/s

deploy/scripts/src/accounts/test.ts, deploy/scripts/src/accounts/vc-storage.ts, deploy/scripts/src/ais/test.ts, deploy/scripts/src/authentication/test.ts, deploy/scripts/src/btm/test.ts, deploy/scripts/src/cimit/test.ts, deploy/scripts/src/common/unit-tests.ts, deploy/scripts/src/common/utils/config/environment-variables.ts, deploy/scripts/src/common/utils/jslib/aws-sqs.d.ts, deploy/scripts/src/cri-kiwi/BAV.ts, deploy/scripts/src/cri-kiwi/f2f-cic.ts, deploy/scripts/src/cri-kiwi/ipvr.ts, deploy/scripts/src/cri-lime/test.ts, deploy/scripts/src/cri-orange/kbv.ts, deploy/scripts/src/cri-orange/nino-check.ts, deploy/scripts/src/cri-orange/utils/config.ts, deploy/scripts/src/examples/dev-platform.ts, deploy/scripts/src/ipv-core/test.ts, deploy/scripts/src/mobile/utils/config.ts, deploy/scripts/src/spot/test.ts, deploy/scripts/src/txma/test.ts
Adds a utility function called `getEnv()` that is used to get environment variables.
- `deploy/scripts/src/common/utils/config/environment-variables.ts`: Added the new `getEnv()` utility function
- `deploy/scripts/src/common/unit-tests.ts`: Added unit tests for the new function to verify it is working as intended and documented
- `deploy/scripts/src/**/*.ts`: Updated all test scripts which retrieved environment variables to use this function
---
Environment variables were previously being accessed directly from the `__ENV` object. When the environment variable didn't exist in the context it was running, the variable would have an `undefined` value. This resulted in un-intuitive error messages later whenever this variable was used, or even fail a functional assertion as the system under …
=> [QA-450] Handle environment variables with a utility function

.github/workflows/typedoc-publish.yml, deploy/scripts/src/common/utils/README.md
Fix issue with TypeDoc documentation publishing.
- `.github/workflows/typedoc-publish.yml`: Updated the `path` parameter to account for that it is run in the root, also removed unused workflow dispatch trigger.
- `deploy/scripts/src/common/utils/README.md`: Added URL of github pages site to the README
---
The previous [workflow](https://github.com/govuk-one-login/performance-testing/actions/runs/8391858781) failed due to the `upload-pages-artifact` action `path` parameter using the root directory of the repository as the working directory 
---
- #543
=> [QA-454] Fix TypeDoc documentation publishing

deploy/scripts/src/cri-orange/kbv.ts
Changed KBV stress test profile to use full load profile
- Changed KBV stress test load profile type to full
---
The KBV stress test should be run with a 15,30,5 load profile
---
=> KBV - Changed stress test load profile to use full

deploy/scripts/src/authentication/test.ts, deploy/template.yaml
Two changes which may address memory usage
- `deploy/scripts/src/authentication/test.ts`: Added the `options.tags.name` to be a blank string
- `deploy/template.yaml`: Removed unused system tags in the k6 command
---
After a recent test run which ended with k6 out-of-memory killed, I suspect that a recent change has introduced a memory leak into the injector. After some local smoke testing it seems that when the `options.tags.name` flag is not set then the memory usage of the application increases over time, even though the system tags flag should ensure that `name` is not being used, and when is it set to a blank string the memory usage appears constant.
This needs some more testing and investigation but making these changes to see if it makes a material difference at higher volumes.
--- …
=> [QA-459] Reduce memory usage

deploy/otel-config-template.yaml
This change filters out some k6 metrics in the OpenTelemetry processing.
Specifically these metrics:
- `k6.http_req_blocked`
- `k6.http_req_connecting`
- `k6.http_req_tls_handshaking`
- `k6.http_req_sending`
- `k6.http_req_waiting`
- `k6.http_req_receiving`
- `deploy/otel-config-template.yaml`: Added a filter processor to drop the above metrics
---
To reduce the memory usage of the OpenTelemetry collector to stop it crashing. These metrics were not currently being used in monitoring/graphing and can alternatively be found in the HTML report uploaded to s3.
Smoke tests of the authentication script showed the following analysis
|Dimension|Count without filter|Count with filter|
|--|--|--|
|`resource metrics`|3|2|
|`metrics`|2083|851|
|`data points`|2083|851|
This was tested using only the …
=> [QA-459] Filter out unused metrics in OpenTelemetry Collector

deploy/template.yaml
Uploads the OpenTelemetry collector log file to s3
- `deploy/template.yaml`: Add an `aws s3 cp` command to upload the otel.log file
---
To debug issues with the OpenTelemetry collector
---
- #550 
- #559
=> [QA-459] Save OpenTelemetry collector log to s3

deploy/scripts/src/cri-kiwi/BAV.ts, deploy/scripts/src/cri-kiwi/f2f-cic.ts
Update Kiwi scripts to use pageContectCheck utility.
- Updated couple of instances in the BAV and F2F/CIC scripts to use the pageContectCheck utility.
---
To ensure consistency across all the scripts.
=> [QA-474]: Update Kiwi scripts to use pageContentCheck utility

deploy/reporting/create-summary.sh
Add instructions on how to use reporting utility
- Added the instructions to use reporting utility as comments in the script.
- There are separate instructions on [querying the test result file](https://github.com/govuk-one-login/performance-testing/blob/main/deploy/scripts/README.md#querying-the-test-result-file) so did not create a separate readme document.
---
Documenting the steps to use the utility.
=> [QA-432]: Add instructions on how to use reporting utility

deploy/Dockerfile, deploy/scripts/src/accounts/test.ts, deploy/scripts/src/accounts/vc-storage.ts, deploy/scripts/src/ais/test.ts, deploy/scripts/src/authentication/test.ts, deploy/scripts/src/cimit/test.ts, deploy/scripts/src/common/unit-tests.ts, deploy/scripts/src/common/utils/authentication/totp.ts, deploy/scripts/src/common/utils/config/load-profiles.ts, deploy/scripts/src/common/utils/request/timing.ts, deploy/scripts/src/cri-kiwi/BAV.ts, deploy/scripts/src/cri-kiwi/f2f-cic.ts, deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts, deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts, deploy/scripts/src/cri-kiwi/utils/authorization.ts, deploy/scripts/src/cri-lime/test.ts, deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/kbv.ts, deploy/scripts/src/cri-orange/nino-check.ts, deploy/scripts/src/examples/dev-platform.ts, deploy/scripts/src/ipv-core/test.ts
Addresses code smells from SonarCloud.
- `deploy/Dockerfile`:
- Replaced `RUN cd` command with `WORKDIR`
- Added `--ignore-scripts` to `npm install` command
- Capitalised `AS` commands
- `deploy/scripts/src/common/utils/request/timing.ts`:
- Added new `timeGroup` function which replaces the previous pattern of `group(name, () => timeRequest(function, checks)` with `timeGroup(name, function, checks)`. Simplifying code and addressing code smells of nested functions being too deep
- `deploy/scripts/src/**/*.ts`:
- Used new `timeGroup()` function
- `deploy/scripts/src/common/utils/config/load-profiles.ts`:
- Replaced ternary with if/else statement
-  `deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts`:
-  Changed interface names to PascalCase
- …
=> [QA-482] Address SonarCloud code smells

deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/utils/config.ts
Added the static assets to a `http.batch()` request in the Address CRI script.
Added an `if` flag to the first request in the Address CRI script, with a `http.batch()` of the static assets.
---
To only parse the static asset URLs once in the user journey to potentially improve performance.
=> [QA-484] Adding static assets in a http.batch() request to the Address CRI script

deploy/scripts/src/authentication/test.ts, deploy/scripts/src/common/utils/request/timing.ts, deploy/scripts/src/cri-lime/test.ts, deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/kbv.ts, deploy/scripts/src/cri-orange/nino-check.ts, deploy/scripts/src/ipv-core/test.ts
Removes empty objects declarations for when calling `timeGroup()` and `timeRequest` without any checks to run
- `deploy/scripts/src/common/utils/request/timing.ts`: Update the `checks` parameters to default to an empty object `{}`
- `deploy/scripts/src/*/*.ts`: Removed empty object parameters `{}` from function calls
---
Simplify code and improve maintainability
=> [QA-485] Remove empty object declarations in check set parameters for `timeGroup()` and `timeRequest()`

.github/workflows/koa-stub-main.yaml, .github/workflows/koa-stub-pr.yaml
Pin the commit SHAs of specific github actions used in deploying and testing changes to the koa-stub
- Replaced version tags with commit SHAs for koa-stub github actions steps
---
Improve security
---
- #492
=> [QA-425] Pin `koa-stub` GitHub actions versions

.github/workflows/pre-merge-checks.yml, .github/workflows/typedoc-publish.yml
Add `setup-node` step in Github actions workflow to fix node version
- `.github/workflows/pre-merge-checks.yml` & `.github/workflows/typedoc-publish.yml`:
- Added `setup-node` workflow
- Updated `npm i` to `npm ci`
---
More control over node versions
=> [QA-486] Use `setup-node` workflow to set node version

koa-stub/template.yaml
Increase max concurrency on mock lambda.
https://govukverify.atlassian.net/wiki/spaces/DID/pages/4113694905/24-04-12+Authentication+SignIn+Load+Test
=> QA-483 Increase reserved concurrency for mock to cope with 4x traffic load than seen in perf test

deploy/scripts/src/authentication/test.ts
Corrected transaction name in sign-in scenario.
- `B02_SignIn_01_InitializeJourney::01_RPStub` was incorrect
---
To ensure correct transaction name is used in the scenarios.
=> [QA-487]: Corrected transaction name in sign-in scenario

deploy/scripts/src/cri-orange/address.ts
Assigns the new response to the `res` variable in the address CRI script
change `timeGroup(` to  `res = timeGroup(`
---
For successful completion of the Address CRI user journey.
=> [QA-490] Updating the Address CRI script with the res variable

deploy/scripts/src/authentication/test.ts
Added load profiles for testing Sign In and Sign Up at 10% of NFR volumes
- Added load profile for Sign In and Sign Up journey
---
The Auth team has asked us to conduct a combined test for Sign In and Sign Up with a target load of 10% of the NFR
---
=> Auth - Add load profiles for testing Sign In and Sign Up at 10% of NFR

deploy/scripts/src/cri-lime/test.ts
- Splits the first call of the passport CRI user journey into 2, the CoreStubCall and CRICall. 
- Add a `http.batch()` of static assets behind an `if` flag to the passport CRI script.
- Split `B03_Passport_01_PassportCRIEntryFromStub` into two separate calls:   `B03_Passport_01_PassportCRIEntryFromStub::01_CoreStubCall` and    `B03_Passport_01_PassportCRIEntryFromStub::02_CRICall`. 
- Add a `http.batch()` of all the passport CRI static assets behind an `if` flag.
---
To allow static asset testing of passport CRI
---
=> [QA-494] Static Asset testing of Passport CRI

deploy/scripts/src/common/utils/config/load-profiles.ts, deploy/scripts/src/cri-lime/test.ts
Added a new loadProfile with an extended ramp-up and reduced steady state for static asset testing
Added a new LoadProfile for static asset testing of:
- Target volume: 30 iterations per second 
- Ramp-up: 15 minutes
- Steady-state: 5 minutes
- Ramp-down: 5 minutes
---
To allow for more accurate static asset testing
---
=> [QA-496] New Loadprofile for Static Asset Testing

deploy/scripts/src/cri-lime/test.ts
Fixes the new LoadProfile name in `cri-lime/test.ts` script 
- changes the new LoadProfile name from extendedRampUp to rampOnly in the `cri-lime.test.ts` script. 
---
To correctly execute a rampOnly test for passport CRI
---
=> [QA-497] Fixing LoadProfile name in cri-lime/test.ts

deploy/scripts/src/authentication/test.ts, deploy/template.yaml
Adds static asset testing the the Auth SignUp journey, and adds the new `rampOnly` LoadProfile. 
- Adds the new `rampOnly` LoadProfile to Auth SignUp
- Adds a `http.batch()` of the static assets behind an `if` flag
---
To run static asset testing on Auth SignUp
=> [QA-499] Adding static asset testing to the Auth SignUp Journey

deploy/reporting/slack.sh, deploy/template.yaml
Adds a link to the ECS Dynatrace dashboard in the Slack notifications
- `deploy/template.yaml`:
- Adds `DYNATRACE_ECS_ID` dashboard ID variables
- Renamed some variables with `K6` in the name which were not related to K6
- Sort variables alphabetically
- `deploy/reporting/slack.sh`:
- Add extra bullet point in message with a link to the ECS dashboard
---
Make it easier to see relevant information for Front End monitoring
---
- #236
=> [QA-500] Link to ECS dashboard in Slack notifications

.vscode/settings.json, deploy/Dockerfile, deploy/template.yaml
After a fix in k6 v0.51 we can now use an environment variable rather than a command line flag to specify system tags
- `.vscode/settings.json`: Added Docker formatter setting
- `deploy/Dockerfile`: Updated xk6 build command to v0.51 and added the `K6_SYSTEM_TAGS` environment variable
- `deploy/template.yaml`: Removed `--system-tags` CLI flag
---
Easier to see config when specified as environment variables
---
- #550
=> [QA-501] Specify System Tags in environment variable

deploy/scripts/src/common/utils/config/load-profiles.ts
Reduces the steady state duration of the `LoadProfile.full` load profile from 30 minutes to 15 minutes
- `deploy/scripts/src/common/utils/config/load-profiles.ts`: `LoadProfile.full` steady state duration from `30m` to `15m`
---
The last 15 minutes of steady state is not currently providing us with any more information that we aren't already capturing in the first 15 minutes. This change will reduce request volume and hence cloud costs and log volumes by roughly 40%.
---
- #532
=> [QA-503] Reduce `full` load profile steady state duration to 15m

deploy/template.yaml
Update the ID of the ECS dashboard for slack notifications
- `deploy/template.yaml`: Update value of `DYNATRACE_ECS_ID`
---
Dashboard has been updated and the ID has changed
---
- #638
=> [QA-500] Update ECS dashboard ID

.github/workflows/pre-merge-checks.yml, .pre-commit-config.yaml
Evergreening pre-commit versions with `pre-commit autoupdate` and pinning the python version in the beautysh pre-commit virtual environment to `v3.11`
- `.pre-commit-config.yaml`:
- Linting changes
- [pre-commit/pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v4.6.0) `v4.5.0` ↦ `v4.6.0`
- [Yelp/detect-secrets](https://github.com/Yelp/detect-secrets/releases/tag/v1.5.0) `v1.4.0` ↦ `v1.5.0`
- [Lucas-C/pre-commit-hooks](https://github.com/Lucas-C/pre-commit-hooks/releases/tag/v1.5.5) `v1.5.4` ↦ `v1.5.5`
- [mattlqx/pre-commit-search-and-replace](https://github.com/mattlqx/pre-commit-search-and-replace/releases/tag/v1.1.2) `v1.0.5` ↦ `v1.1.2`
- [alessandrojcm/commitlint-pre-commit-hook](https://github.com/alessandrojcm/commitlint-pre-commit-hook/releases/tag/v9.16. …
=> [QA-504] Pre-commit evergreening and beautysh fix

deploy/scripts/src/authentication/test.ts
Removes duplicated steps in the `signIn` and `signUp` functions to separate functions so they are only defined in one place.
- creates the new function `initializejourney()` to replace the `B01_SignUp_01_InitializeJourney` and `B02_SignIn_01_InitializeJourney` duplicated steps.
- creates the new function `MFAEnterOTP()` to replace the `B02_SignIn_05_AuthMFA_EnterTOTP` and `B02_SignIn_07_SMSMFA_EnterOTP` duplicated steps.
- creates the new function `logout()` to replace the `B01_SignUp_12_Logout` and `B02_SignIn_09_Logout` duplicated steps.
---
So these steps are only defined once for neater code.
=> [QA 452] Removing duplicated steps in the authentication script 

deploy/template.yaml
Update permissions for PerformanceTesterRole to allow AssumeRole
- Updated the condition in PerformanceTesterRole to reflect correct prefix of power user role.
---
Perf team are not able to assume Performance Tester role due to the condition. This PR should fix this issue.
=> [QA-513]: Update permissions for PerformanceTesterRole to allow AssumeRole

deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts, deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts, deploy/scripts/src/txma/test.ts
- Removes the `AUTH_AUTHORISATION_INITIATED` event 
- Updated the `sendSingleEvent` function to use `AuthAuthorisationReqParsed() `
- Removed the interface and function for `AUTH_AUTHORISATION_INITIATED`
- Updated the `sendSingleEvent` scenario to use `AuthAuthorisationReqParsed()`
---
To run a successful TxMA Shared Signals `sendSingleEvent` test
=> [QA-514] Updating TxMA sendSingleEventScenario

deploy/scripts/src/ipv-core/test.ts
Adhoc load profile added for passport scenario in IPV core
- Adhoc load profile added for passport scenario in IPV core with 30 minutes steady state.
---
Previous IPV core tests have shown FE scaling completion in 20-25 minutes thereby impacting the results of the first half of the steady state. The steady state is being increased to maintain consistency in this regression test with previous tests.
=> [QA-517]: Adhoc load profile added for passport scenario in IPV core

deploy/scripts/src/accounts/vc-storage.ts
Updated token generation call for Summarise VC
- Modified the body of the POST request to generate mock token from build environment.
---
Summarise VC calls are failing due to HTTP-401 errors as the tokens are being generated incorrectly.
=> [QA-522]: Updated token generation call for Summarise VC

.github/workflows/publish.yaml
Update the trigger on the `publish` github action to also trigger when changes are made to the action file itself.
- `.github/workflows/publish.yaml`: Update trigger to include changes to itself
---
To trigger builds also when the action is updated
=> [PSREDEV-1157] Update publish action trigger

deploy/scripts/src/mobile/frontend-e2e.test.ts, deploy/scripts/src/mobile/testSteps/frontend.ts
Updates a response assertion using the page content within the mobile/frontend-e2e.test.ts script
Removes requests to /flashingColours and /workingCamera
Aligning test script with recent changes to the user journey
Passing when running locally:
---
=> DCMAW-8764: Updates mobile fe test following changes to routing and content

.github/workflows/pre-merge-checks.yml
Updates the pre-merge checks github action to use the docker image for running the k6 unit test script, rather than using an external action
- `.github/workflows/pre-merge-checks.yml`: Replaced the `grafana/k6-action` step with a `docker build` then a `docker run` step
---
This adds additional checks to ensure that the Docker image can be built and is working correctly and that the k6 version in this image is working correctly.
=> [QA-241] Use local docker image for CI unit tests

deploy/scripts/src/cri-orange/otg.ts
Corrects the env variable name in the OTG script
-changes the env variable name from IDENTITY_ORANGE_BUILD_OTG_URL to IDENTITY_BUILD_OTG_URL 
---
To run a successful OTG perf test
=> [QA-528} Correcting the environment variable name for OTG 

deploy/scripts/src/cri-orange/otg.ts
Adds a pageContentCheck to the `otg.ts` script
Adds `...pageContentCheck('goodToken')` to `cri-orange/otg.ts`
---
To check the page content of OTG to validate the journey
=> [QA-529} Adding pageContentCheck to OTG script

.github/workflows/pre-merge-checks.yml
Add Github Actions cache to docker build
- `.github/workflows/pre-merge-checks.yml`: Add a `docker buildx` setup step and add settings to use the GHA cache
---
To speed up CI checks
---
- #713
=> [QA-241] Add cache to docker build

deploy/scripts/src/cri-orange/otg.ts
Adds an additional load profile for stress testing of OTG
- Adds a 'stress' load profile at a target volume of 44 iterations per second. 
---
To run a stress test for OTG at a target of 44 iterations per second.
=> [QA-531] Adding a stress test load profile for OTG

deploy/scripts/src/authentication/test.ts
Updating the Auth load profile to 20% of the NFR volumes
Creates a `load20` load profile for Auth with a target volume of 20j/s for `signUp` and 380j/s for `signIn`. 
---
To run a combined load test for Auth at a target volume of 20% of the NFR volumes.
=> [QA-537] Updating Auth load profile to 20% of NFR volume

deploy/scripts/src/authentication/test.ts
Updated the Auth `load20` profile to a full profile not short 
- Updates the `load20` profile to `LoadProfile.full`
---
To run a test for Auth at 20% NFR volume for a full test duration
=> [QA-538] Updating the Auth load20 profile to full

koa-stub/src/package-lock.json, koa-stub/src/package.json
Remove redundant `@eslint/js` dependency, covered by `eslint`
- Removed `@eslint/js` from `package.json`
- `npm update` minor package-lock bumps
---
Dependency maintenance / evergreening
=> [QA-540] Remove redundant package dependency

deploy/scripts/src/ipv-core/test.ts
Reduce steady state duration of the IPV core adhoc tests in dev
- Reduce steady state duration of the IPV core adhoc tests to 5 minutes for testing in dev environment
---
To run a smaller load test in dev environment
=> [QA-546]: Reduce steady state duration of the IPV core adhoc tests in dev

deploy/scripts/src/accounts/test.ts
Changes the OLH user journeys to include the new stubs page
Adds in the `ClickDefaultScenario` step for the `changeEmail`, `changePassword`, `ChangePhone`, and `DeleteAccount` scenarios to navigate through the new stubs page.
---
To run a successful performance test for the OLH journeys using the new stubs page.
=> [QA-539] Updating the OLH scripts to include the new stubs page

deploy/scripts/src/cri-orange/kbv.ts
- Changes the `groupMap` name to match the scenario name
- Changes the `groupMap` name to 'kbv' from 'kbvScenario1'
---
- To correctly record HTTP request duration under `groupMap` names
=> [QA-549] Updating the groupMap name to match the scenario name for kbv

.github/CODEOWNERS
Adds `fraud-ssf-team` to `fraud` test script directory
- `.github/CODEOWNERS`: Add `@govuk-one-login/fraud-ssf-team` team to `/deploy/scripts/src/fraud`
---
Allow teams to manage own test scripts
=> [QA-552] Add Fraud SSF team to `CODEOWNERS`

deploy/Dockerfile
Resolve SonarCloud security alerts in Dockerfile
- `deploy/Dockerfile`:
- Replace `ADD` with `COPY`
- Sort `RUN` arguements alphebetically
---
Resolve security alerts and code smells
=> [QA-551] SonarCloud Dockerfile security alert fixes

.github/CODEOWNERS, deploy/scripts/src/fraud/test.ts
Reduces the volumes of calls to AWS Cognito by only calling cognito once at the beggining of the test
- `deploy/scripts/src/fraud/test.ts`: Moved cognito step to `setup` function
---
To better simulate real world behaviour
---
- #693
=> [FPAD-3128] Reduce number of calls to Cognito

deploy/scripts/src/fraud/test.ts
Add debug logging to initial cognito call
- `deploy/scripts/src/fraud/test.ts`:
- Removed unused `timeGroup` call
- Added `console.log` debug statements for Cognito response
---
To debug Cognito errors
---
- #788
=> [FPAD-3128] Cognito debugging

deploy/scripts/src/accounts/test.ts
Add debug logging to the OLH `changeEmail` test script
- Add and `if` statement where if the `pageContentCheck` fails, the unexpected page content will be returned.
---
- If we get response validation failures, we will be able to see the content of the incorrect page returned to help with debugging.
=> [QA-550] Add debug logging to OLH changeEmail

koa-stub/src/utils/onelogin.util.js, koa-stub/template.yaml
Changes stub lambda timeout and oidc timeouts to 30s.
- Template change to lambda
- Client change to oidc lib in app
Gives orchestration a chance to succeed, even if sub-optimal.
=> QA-535 Increase stub and lambda timeout to 30 to allow orchestration a chance to succeed

deploy/scripts/src/accounts/test.ts
Removed the sign-out step from the OLH `changeEmail` scenario
Removes `B01_ChangeEmail_08_Signout` from the `changeEmail` scenario
---
To run a successful OLH `changeEmail` test, as currently when one user signs-out, all other concurrent users sign-out, resulting in 99% user journey failure.
=> [QA-561] Removing the sign-out step in the OLH changeEmail scenario

deploy/scripts/src/accounts/test.ts
Adds the logout step back into the OLH scenarios 
- Adds the `B01_ChangeEmail_08_Logout`, `B02_ChangePassword_07_SignOut`, and `B03_ChangePhone_08_SignOut`steps back into the `changeEmail`, `changePassword`, and `changePhone` scenarios of the OLH test script.
---
The OIDC stub has been updated to use unique session IDs for each user so only the singular user will be logged out. This should provide a fix for the response validation errors while still allowing the sessions to be deleted from the Session store during the logout step.
=> [QA-564] Adding the logout step back into OLH scenarios.

deploy/scripts/src/accounts/test.ts
Updating the `changeEmail` load profile to 30 iterations per second.
Updating the target volume of the OLH `changeEmail` load profile to 30 iterations per second from 15.
---
To run a load test for OLH changeEmail at the current NFR volume we are working to, 30 iterations per second.
=> [QA-566] Updating the changeEmail OLH load profile to 30 iterations per second

deploy/Dockerfile
Combines consecutive Docker `RUN` commands
- `deploy/Dockerfile`: Combine consecutive `RUN` commands
---
This reduced the number of layers in the Docker image
=> [QA-568] Combine consecutive Docker RUN commands

koa-stub/src/controllers/callback.controller.js, koa-stub/src/tests/app.test.js
Fixes the /userinfo retry mechanism
- `koa-stub/src/controllers/callback.controller.js`: Add a loop to the `getUserInfo()` function to retry failures up to 2 times (up to 3 calls in total), implementing the original intended functionality
- `koa-stub/src/tests/app.test.js`: Added a restore of the console.warn and updated the expected call count to 3
---
The previous code would only retry once and would not handle a second error gracefully. The previous code intended to have up to 3 retries, and this fixes that.
---
- #765
=> [QA-567] Fix koa-stub userinfo retry mechanism

.github/dependabot.yml
Groups certain dependabot updates
- `.github/dependabot.yml`: 
- Groups `eslint`, `esbuild` and `k6` updates for the `/deploy/scripts` npm project
- Groups `aws-sdk`, `axios`, `koa` and `supertest` updates for the `/koa-stub/src` npm project
---
Reduce number of dependabot PRs
=> [QA-571] Group Dependabot updates

deploy/scripts/src/olh/test.ts
Updated the OLH scenarios to use the new `userPerformanceTest` user instead of the `default` user in the OIDC stub.
- Updated the OIDC scenario to `userPerformanceTestUser` from `default` in `changeEmail`, `changePhone`, `changePassword`, and `deleteAccount` scenarios. 
---
So the OLH team can see activity history from the performance test.
=> [QA-569] Updating the OLH scenarios to use the 'userPerformanceTest' user.

deploy/scripts/src/cri-orange/address.ts
Reduced the low volume target for Address CRI to 15
- Reduced the low volume target for Address CRI to 15 journeys/second
---
To conduct a baseline test for address CRI
=> [QA-573]: Reduced the low volume target for Address CRI to 15

.github/workflows/pre-merge-checks.yml, .github/workflows/typedoc-publish.yml
Add github npm package registry
- Add github registry to node setup for github workflows
---
To enable use of github npm packages
=> [QA-543] Add github npm package registry

deploy/scripts/src/cri-orange/address.ts
Changes the Address CRI `lowVolume` test scenario to have a target volume of 5 iterations per seocnd. 
- Changes the target volume for the `lowVolume` profile of the `cri-orange/address.ts` test script to 5 iterations per second from 15.
=> [QA-577] Changing the Address CRI lowVolume profile to 5 j/s

deploy/scripts/src/ipv-core/test.ts
Combines the Passport, Driving Licence and Orch Stub test scenarios
- `deploy/scripts/src/ipv-core/test.ts`:
- Environment variables use `getEnv()` function over `__ENV` object directly
- Combined passport and driving licence scenarios into one `identity` scenario with a 80/20 split in favour of passport
- Orch Stub Only Journey changed to used main test scenario
---
To reduce code duplication and make scripts easier to maintain, as well as improving test coverage.
=> [QA-542] Combine IPV Core Scenarios

deploy/scripts/src/common/utils/config/load-profiles.ts, deploy/scripts/src/mobile/authorize.test.ts, deploy/scripts/src/mobile/backend-e2e.test.ts, deploy/scripts/src/mobile/frontend-e2e.test.ts, deploy/scripts/src/mobile/testSteps/backend.ts, deploy/scripts/src/mobile/testSteps/frontend.ts, deploy/scripts/src/mobile/utils/test-client.ts
Aligns ID check scripts to central approach, including load profile definition and adding response time thresholds for groups
- `deploy/scripts/src/common/utils/config/load-profiles.ts`: Added new `LoadProfile.incremental` load profile - a load profile which slowly ramps up in 25% of the load target every 14 minutes.
```mermaid
xychart-beta
title "Incremental load profile"
x-axis "Minutes" 0 --> 56
y-axis "Load (%)" 0 --> 100
line [0, 12.5, 25, 25, 25, 25, 25, 25, 37.5, 50, 50, 50, 50, 50, 50, 62.5, 75, 75, 75, 75, 75, 75, 87.5, 100, 100, 100, 100, 100, 100]
```
- `deploy/scripts/src/mobile/authorize.test.ts`: 
- Add response time thresholds
- Add iterations started and iterations completed metric counters
- `deploy/scripts/src/mobile/backend-e2e.test.ts`:
- Update load profiles to use …
=> [QA-581] Align ID Check Scripts

deploy/scripts/src/cri-kiwi/f2f-cic.ts
Removes the duration from the `load` load profile of the `CIC` scenario.
Removes the duration value of 3 from the `load` load profile of the `CIC` scenario 
---
To run a successful load test for CIC CRI
=> [QA-599] Removing the duration metric from the load profile of the CIC scenario

deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts, deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts, deploy/scripts/src/txma/test.ts
Updated primer and regular event payloads based on the latest changes in the approach.
- Updated primer event (`AUTH_CREATE_ACCOUNT`) and regular event (`AUTH_LOG_IN_SUCCESS`) to use same user ID and email ID and different event IDs.
---
To fix the errors identified in the TxMA smoke testing.
=> [QA-627]: Update TxMA payloads based on latest changes

deploy/scripts/src/cri-lime/test.ts
Updates the `DrivingLicence` `lowVolume` scenario to have a target volume of 15 iterations per second. 
Changes the `DrivingLicence` `lowVolume` scenario's target volume to 15 iterations per second. 
---
To run a low volume test at 15 iterations per second.
=> [QA-609] Updating the DL lowVolume scenario to 15 iterations per second

deploy/scripts/src/txma/test.ts
Add a low volume load profile for TxMA regular event scenario
- Add a low volume load profile for TxMA regular event scenario with  a target volume of 30 journeys per second.
---
To conduct a low volume test for TxMA.
=> [QA-632]: Add a low volume load profile for TxMA

deploy/scripts/src/cri-orange/nino-check.ts
Updates the low volume profile for NINO CRI to 5 iterations per second.
Updates the `lowVolume` load profile for `ninoCheck` in `cri-orange/nino-check.ts` from 15 to 5 iterations per second. 
---
To run a low volume test for NINO CRI at 5 iterations per second
=> [QA-631] Updating the low volume profile for NiNO CRI to 5 iterations per second

deploy/scripts/src/cri-lime/test.ts
Updates the DL CRI low volume load profile to 20 iterations per second. 
Updates the DL CRI `lowVolume` load profile from 15 to 20 iterations per second. 
---
To run a low volume test at 20j/s for DL CRI.
=> [QA-642] Updating the DL CRI low volume profile to 20j/s

deploy/scripts/src/ipv-core/test.ts
Fixes a `pageContentCheck` for the IPVCore Identity scenario
- fixes the pageContentCheck for `B01_Identity_10_KBVDataContinue::02_CoreCall`
---
To run a successful performance test for the IPV Core Identity scenario.
=> [QA-651] fixing a pageContentCheck for the IPVCore Identity scenario

deploy/scripts/src/authentication/test.ts, deploy/scripts/src/common/utils/config/load-profiles.ts
Added load profiles for March 2025 PT for Auth scenarios
Added below load profiles for March 2025 PT for Auth sign up and sign in scenarios
- Load
- Soak
- Spike NFR
- Spike Sudden
---
To conduct performance tests for Auth at March 2025 volumes
=> [QA-664]: Added load profiles for March 2025 PT for Auth scenarios

deploy/scripts/src/authentication/test.ts, deploy/template.yaml
This pull request enables seamless switching between ORCH and RP stubs for the SignUp, SignIn, and UISignIn journeys using a single environment variable, improving flexibility and maintainability.
- Introduced a new environment variable `ROUTE` to specify either "ORCH" or "RP" for stub selection.
- Modified the `env` object to use distinct environment variables for `orchStubEndpoint` and `rpStubEndpoint`, dynamically selected based on the `ROUTE` value.
- Updated the `groupMap` included transaction names for rpStubSubmit and added index in the rpStubSubmit accordingly.
- Added conditional logic in the `SignUp` and `SignIn` and `UISignIn` functions to call the appropriate stub submission function (`orchStubSubmit` or `rpStubSubmit`) based on the `ROUTE` value.
- Included error handling in …
=> [QA-633] Auth - Dynamic Stub Selection for Sign-Up, SignIn and UISignIn Journey

deploy/scripts/src/bravo/vc-storage.ts
Removed debug statement from EVCS script
- Removed debug statement from vc-storage.ts
---
Debug statement no longer necessary
=> QA-653 Removed debug statement EVCS

deploy/scripts/src/cri-lime/test.ts
This pull request adds a new load profiles for the CRI-Lime `fraud` and `passport` scenarios based on the Mar 2025 level 1 Revised targets.
Added four new load profiles: loadMar2025, soakMar2025, spikeNFR, and spikeSudden.
---
Simulate expected March 2025 traffic and assess system performance.
=> [QA-676] feat: Add Mar 2025 load profiles for CRI-Lime

deploy/scripts/src/cri-orange/address.ts
Added new profiles for March 2025 Volumes to the existing Orange(Address) script
- Added loadMar2025, soakMar2025, spikeNFR & spikeSudden profiles
---
For the March 2025 Volumes
=> [QA-677] Updated AddressCRI load profiles

deploy/scripts/src/ipv-core/test.ts
Edits the `dataCreationForIDReuse` profile to reflect the scenario name change from `passport` to `identity`
- changes the `exec` in `dataCreationForIDReuse` to reflect the new scenario name of `identity` from `passport`
---
To enable data creation for the ID Reuse Scenario.
=> [QA-663] Updating the dataCreationForIDReuse profile

deploy/scripts/src/authentication/test.ts
This pull request adds new load profiles to the authentication performance test script to simulate Level 2 traffic targets for March 2025.
- Added four new load profiles: `loadMar2025_L2`, `soakMar2025_L2`, `spikeNFR_L2`, and `spikeSudden_L2`.
- Configured these profiles to target 90 and 120 iterations per second for `signUp` and `signIn` scenarios respectively.
- Updated Level1 profile names with suffix as `L1`.
---
To evaluate the performance at level2 targets.
---
=> [QA-678]: Add load profiles for March-25 L2 targets

deploy/scripts/src/authentication/test.ts
To enhance the `rpStubSubmit` function in the authentication performance test suite to accurately capture and report the response time of the `OIDC` call.
- Added a timeGroup block specifically around the http.get request for the `OIDC` call within the `rpStubSubmit` function.
- This change ensures that the response time of the `OIDC` call is measured and reported separately in the k6 test results.
---
- Isolate and measure the performance of the OIDC call
=> [QA-680] Capture OIDC call response time in rpStubSubmit function

deploy/scripts/src/txma/test.ts
Increase TxMA load profile to 500 messages per second
- Increase the load profile for `sendRegularEvent` scenario to 500 messages per second.
---
To conduct perf tests for TxMA shared signals at 500 messages per second.
=> [QA-682]: Increase TxMA load profile to 500/s

deploy/scripts/src/cri-orange/utils/config.ts
Update Orange CRI script config to remove dependency on `K6_NO_STATIC_RESOURCES`
- Remove calling the `getEnv()` for `K6_NO_STATIC_RESOURCES` 
---
This is so that the the value of this environment variable does not have to be provided for each test and just for the tests involving static resources.
=> [QA-683]: Update Orange config to remove dependency on K6_NO_STATIC_RESOURCES

deploy/scripts/src/cri-lime/test.ts
Adds an `addressCountry` with value GB to the Fraud CRI Payload
- Adds an `addressCountry` with value GB to the Fraud CRI Payload
---
To run a successful test for Fraud CRI and align the payload with international addresses.
=> [QA 695] Adding addressCountry to the FraudCRI payload

deploy/scripts/src/authentication/test.ts, deploy/scripts/src/cri-lime/test.ts, deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/ipv-core/test.ts
Adds a maximum duration to the March 2025 volume load profiles for all scenarios
- Adds a maximum duration value (of 4 * no. of steps) to each March 2025 volume loadProfiles for Auth, IPV Core, Address CRI, Passport CRI, and Fraud CRI. 
---
To correct the number of maxVUs allocated during a test
=> [QA-700] Adding a max duration for the maxVUs calculation to March 2025 tests

deploy/scripts/src/common/utils/config/load-profiles.ts, deploy/scripts/src/ipv-core/test.ts
Add Level 2 load profiles into configuration, Include level 2 load profiles in IPV test script
- Add 2 Level 2 load profiles into load profile configuration, 
- Include 4 level 2 load profiles in IPV test script
---
To enable load, soak, spike, sudden spike tests against Level 2 targets for IPV core
---
=> QA-722 Add L2 load profs, Include in IPV test

deploy/scripts/src/cri-lime/test.ts
Added L2 profiles for Fraud&Passport CRI.
Included the L2 Load profiles for Fraud CRI (26) and Passport CRI (22)
---
To allow us to run L2 test for Fraud&Passport CRI
---
=> [QA-728] Added L2 profiles for Fraud&Passport CRI

deploy/scripts/src/cri-orange/address.ts
Updates the low volume target volume for the `address` and `internationalAddress` scenarios to 10j/s and 5j/s respectively
- Updates the low-volume load profile target volume for the `address` and `internationalAddress` scenarios to 10j/s and 5j/s respectively.
---
To run a combined low volume test for `address` and `internationalAddress`.
=> [QA-741] updating target volumes for address CRI

deploy/scripts/src/cri-lime/test.ts
Updated the Load profile for the Fraud CRI SpikeSudden_L2 scenario.
- Changed from 26j/s to 27j/s 
---
To accommodate for the 33% ramp up
---
=> [QA-740] Fraud - Updated SuddenSpike_L2 profile

deploy/scripts/src/cri-lime/test.ts
Update Lime for L2 Spike tests
- Update Lime script for L2 Spike tests to use the spikeNFRSignUpL2 load profile
---
To match the test approach for L2 tests
---
=> QA-714 Update Lime for L2 Spike tests

deploy/scripts/src/cri-orange/address.ts
Added an adhoc scenario for Address to test with consistent virtual user count.
- Added the function `addressAdhocScenario()`.
- Removed `sleep()` after all the steps in the above scenario to evaluate max support performance.
- Removed the final stub call to the `/callback` endpoint.
---
To conduct performance test of Address CRI under a load of 10 concurrent virtual users.
=> [QA-726]: Adhoc address scenario with consistent virtual user count

deploy/scripts/src/mobile/frontend-e2e.test.ts
Load profile addition to run the test with NFR target
- Added load profile `nfrload` to execute the load test with a target throughput of 95 iteration per second
---
To conduct the load test for Mobile FE against NFR target throughput.
---
=> [QA-746] Mobile FE - Added load profile to run test with 95 Iteration per second

deploy/scripts/src/common/utils/request/timing.ts, deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/utils/config.ts
Add a separate profile for Address scenario
- Added a separate load profile for Address scenario with the `ramping-arrival-rate` executor with the `timeUnit` as **10 seconds**. Adjusted the `target` load accordingly and updated the `preAllocatedVU` and `maxVUs` count to match baseline.
- Updated the `timeRequest` function to return the HTTP error status and body if an assertion fails.
---
To conduct a performance test for Address scenario with the updated config.
=> [QA-744]: Add a separate profile for Address scenario

deploy/scripts/src/txma/test.ts
Increases the TxMA `sendRegularEvent` target volume to 2000j/s
- Increases the target volume for the `sendRegularEvent` load profile in the TxMA script to 2000j/s.
---
To run a load test for TxMA at 2000j/s
=> [QA-748] Increasing TxMA sendRegularEvent target volume

deploy/scripts/src/ipv-core/test.ts
Added load profiles to the IPV Core script for low volume tests.
- Added a low volume Perf test for the identity scenario
- Added a low volume Perf test for the IDRe-use scenario
---
In order to run low volume performance tests as part of the Performance testing initiative.
---
=> Added Low Volume Profiles

deploy/scripts/src/cri-lime/test.ts
Add low volume load profiles for Lime CRI scenarios
- Add low volume load profiles for Fraud, Driving Licence and Passport CRI scenarios.
---
To run low volume performance tests for Lime CRIs
=> [QA-755]: Add Lime CRI low volume load profiles

deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/kbv.ts, deploy/scripts/src/cri-orange/nino-check.ts
Add low volume load profiles for Orange CRI scenarios.
- Add low volume load profiles for Address, KBV and NiNO Check scenarios.
---
To run low volume performance tests for Orange CRIs
=> [QA-756]: Add low volume load profiles for Orange CRI

deploy/scripts/src/cri-orange/nino-check.ts
Update the load profile to execute NiNo test with 1 Journey per minute throughput target
- Start rate is 1 user per 1m 
- Ramp-up is 1 journey in 60 seconds and steady state target is 1 journey per minute.
---
To run the test with flat volume.
---
=> [QA-761]: Updated load profile for lowVolPERF007Test

deploy/scripts/src/ipv-core/test.ts
Decreased the preAllocatedVU Count for the `idReuse` scanerio.
- decreases the preAllocatedVUs for the `idReuse` scenario to 20 (below the maxVU Count)
---
To successfully run a `perf006Iteration1` test for IPV Core
=> [QA-774] Decreasing preAllocatedVU Count for idReuse.

deploy/scripts/src/mobile/frontend-e2e.test.ts
Updates the MobileFE scenario with the new lowVolPerf007Test profile.
- Adds the lowVolPerf007Test load profile to MobileFE scenario at a target volume of 2j/s.
---
To run flat load profile test for MobileFE
---
=> [QA-775] - Added lowVolumePerf007Test load profile in MobileFE

deploy/scripts/src/authentication/test.ts
Added a perf-006 load profile to the auth script.
- Adds the perf006Iteration1 load profile for the sign-up & sign-in journeys.
---
To run a combined Auth test in the pipeline at PERF-006 volumes.
=> Added Perf006 load profile for auth

deploy/scripts/src/cri-lime/test.ts
Add Iteration 1 test targets for Lime scenarios
- Fraud - 15 journeys per second
- DL - 2.5 journeys per second
- Passport - 2 journeys per second.
---
To execute iteration 1 tests for Lime products
=> [QA-778]: Add Iteration 1 targets for Lime scripts

deploy/scripts/src/cri-lime/test.ts
Increase steady state duration for lime scripts
- Increase steady state duration for lime scripts to 15 minutes
---
To run performance test for lime products
=> [QA-778]:Increase steady state duration for lime scripts

deploy/scripts/src/fraud/test.ts
Reduces the Fraud SSF Inbound target volume to 3 messages per second
Reduces the Fraud SSF Inbound target volume to 3 messages per second
---
To run a performance test for Fraud SSF Inbound at 3 messages per second.
=> [QA-779] Reducing the Fraud SSF Inbound target volume

deploy/scripts/src/fraud/test.ts
Changes the duration from 3 to 4 so the `preAllocatedVUs` is an integer n the Fraud SSF Inbound script.  
Changes the duration from 3 to 4 so the `preAllocatedVUs` number is calculated is an integer in the Fraud SSF Inbound script.  
---
To successfully run a performance test for Fraud SSF Inbound.
=> [QA-779] Changing duration for preAllocatedVU calculation in Fraud SSF Script

.github/CODEOWNERS
Updates codeowners for the mobile pod scripts
---
The old github team is being retired
Note the Github teams need to be updated in the settings page:
=> Update mobile pod codeowners

deploy/scripts/src/cri-orange/nino-check.ts
For NiNO check ppdated target in  PERF006 iteration 1 load profile
- Target value updated from 5 to 50 in perf006Iteration1 load profile.
---
To achieve the target throughput of 5 journey per second, since time unit is 10s hence to target value will be translated to 5 as a target throughput for ramp-up and steady state.
---
=> [QA-777] PERF006Iteration1 load profile target corrected

deploy/scripts/src/cri-orange/kbv.ts
Add a profile for Experian KBV PERF006 iteration 1
- Added a profile to the Experian KBV scenario named PERF006 iteration 1.
---
To conduct a performance test for Experian KBV at the PERF 006 Targets.
=> Update Orange KBV scenario with PERF006 profiles

deploy/scripts/src/ipv-core/test.ts
Lowers the IPV Core PERF0006 volumes 
- Lowers the `identity` PERF006 target volume to 14 j/s, and therefore changing the ramp-up duration to 410s and `maxVU` count to 504 (12 * 3 * 14)
- Lowers the `idReuse` PERF006 target volume to 3j/s, and therefore changing the ramp-up duration to 3s, `maxVU` Count to 18 (2 * 3 * 4), and `preAllocatedVUs` to 15. 
---
to run a PERF006 volume test at lower volumes
=> [QA-785] Updating the IPV Core PERF006 volumes

deploy/scripts/src/ipv-core/test.ts
Changing Load profile to the PERF006 Iteration2 targets which accommodate Spike tests
...createScenario('identity', LoadProfile.spikeI2HighTraffic, 35, 44),
...createScenario('idReuse', LoadProfile.spikeI2HighTraffic, 32, 8)
}
---
As part of PERF006 Iteration2 targets which accommodate Spike tests
---
=> QA-788 Load profile changes for IPV core

deploy/scripts/src/authentication/test.ts, deploy/scripts/src/common/utils/config/load-profiles.ts
Updates the `spikeI2HighTraffic` load profile to use `target` for 100% not `step` (`target` / 3 rounded) * 3.
- changes the target volume for the 100% volume spikes in the `spikeI2HighTraffic` load profile, to the value of the `target` variable, instead of `step` *3, where `step` = `target`/3 rounded. 
---
To ensure our 100% target volume is the same value as our `target` variable.
=> [QA-790] Updating the target for PERF006 I2 Spike tests

deploy/scripts/src/common/utils/config/load-profiles.ts, deploy/scripts/src/fraud/test.ts
Adds in a new steady-state only load profile for the `fraud/test.ts` script
- Adds in the `steadyStateOnly` profile to `load-profiles.ts `, which ramps up to 100% volume in 1 second and maintains it for 6 minutes. 
---
To run a test for Fraud at 250 messages per second for only a 6 minute steady state period.
=> [QA-793] Adding a new load profile for Fraud.

deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/kbv.ts
[QA-794](https://govukverify.atlassian.net/browse/QA-794)
What?
CRI Address & KBV scenarios will be tested for spike and peak load profiles
Changes:
Added the below profiles
Address
...createScenario('address', LoadProfile.spikeI2HighTraffic, 35, 20)
},
address: {
startRate: 1,
preAllocatedVUs: 100,
maxVUs: 400,
stages: [
{ target: 120, duration: '121s' },
{ target: 120, duration: '30m' }
],
exec: 'address'
}
}
KBV
spikeI2LowTraffic: {
...createScenario('kbv', LoadProfile.spikeI2LowTraffic, 4) //rounded to 4 from 3.5
},
kbv: {
startRate: 1,
preAllocatedVUs: 100,
maxVUs: 400,
stages: [
{ target: 12, duration: …
=> QA-794 : CRI Address & KBV profile updates for Perf006 Iteration 2

deploy/scripts/src/cri-lime/test.ts
SPIKE Test Load test profile changes
...createScenario('drivingLicense', LoadProfile.spikeI2HighTraffic, 4, 9),
...createScenario('drivingLicenceAttestation', LoadProfile.spikeI2HighTraffic, 7, 9)
}
---
To perform PERF006 Iteration2 SPIKE test
---
=> QA-799..DL and DL Attestation PERF 006 Iteration 2 Spike test changes

deploy/scripts/src/cri-lime/test.ts
PEAK and SPIKE profile for DL,DLAttest&Fraud for PERF006 Iteration2
...createScenario('drivingLicense', LoadProfile.spikeI2HighTraffic, 4, 9),
...createScenario('drivingLicenceAttestation', LoadProfile.spikeI2HighTraffic, 7, 9),
...createScenario('fraud', LoadProfile.spikeI2HighTraffic, 35, 6)
},
drivingLicense: {
startRate: 1,
preAllocatedVUs: 9,
maxVUs: 9,
stages: [
{ target: 15, duration: '16s' },
{ target: 15, duration: '30m' }
],
exec: 'drivingLicense'
},
drivingLicenceAttestation: {
startRate: 1,
preAllocatedVUs: 14,
maxVUs: 14,
stages: [
{ target: 23, duration: '24s' },
{ target: 23, duration: '30m' }
],
exec: …
=> QA-800 PEAK and SPIKE profile for DL,DLAttest & Fraud

deploy/scripts/src/cri-lime/test.ts
QA-800 corrected load profiles for spike and peak
...createScenario('drivingLicence', LoadProfile.spikeI2HighTraffic, 4, 9),
...createScenario('drivingLicenceAttestation', LoadProfile.spikeI2HighTraffic, 7, 10),
...createScenario('fraud', LoadProfile.spikeI2HighTraffic, 35, 6)
},
drivingLicence: {
startRate: 1,
preAllocatedVUs: 9,
maxVUs: 9,
stages: [
{ target: 15, duration: '16s' },
{ target: 15, duration: '30m' }
],
exec: 'drivingLicence'
},
drivingLicenceAttestation: {
startRate: 1,
preAllocatedVUs: 14,
maxVUs: 14,
stages: [
{ target: 23, duration: '24s' },
{ target: 23, duration: '30m' }
],
exec: 'drivingLicenceAttestation'
},
fraud: …
=> QA-800 corrected loadprofiles for spike and peak

deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts, deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts, deploy/scripts/src/txma/test.ts
- Removes the outdated `pairwiseMappingClientEnrichment` scenario and replaces it with the new `sendRegularEventWithEnrichment` scenario. 
- alters the `AUTH_AUTHORISATION_REQUEST_PARSED` and `AUTH_LOGIN_SUCCESS` payload to contain new correct values for this scenario. 
- Removes the `pairwiseMappingClientEnrichment` scenario
- Creates a new `sendRegularEventWithEnrichment` scenario which send the `AUTH_LOGIN_SUCCESS` event with no clientID.
- Alters the setup() function to send 2 primer events for the `sendRegularEventWithEnrichment` scenario.
- Changes all journeyIDs to a static value of "journeyID"
- Alters the `AUTH_LOGIN_SUCCESS` payload to remove the clientID value
- Alters the `AUTH_AUTHORISATION_REQUEST_PARSED` to contain only necessary details
---
To enable testing of …
=> [QA-805] Adding a new clientEnrichment, SSF Outbound scenario for TxMA

deploy/scripts/src/olh/test.ts
changed the spike test load profile for OLH
- The previous 'spikeI2LowTraffic' profile was changed to 'spikeI2HighTraffic'
---
To run Tests against PERF006 iteration 2 for OLH.
---
=> Changed OLH profile for PERF006 i2 tests

deploy/scripts/src/olh/test.ts
Changed the highTraffic Iteration 2 spike profile to a lowTraffic profile
- Changed the highTraffic Iteration 2 spike profile to a lowTraffic profile
- Durations at the side of the target have been changed to properly reflect the duration for the individual scenarios
---
To Run a spike test using the low traffic profile instead of the high traffic profile
---
=> changed OLH I2 peak profile to lowTraffic

koa-stub/src/package-lock.json
npm audit fix of the dependencies inside the koa-stub/ package
- npm upgrade to the package-lock.json to ensure all security updates are in place.
---
Some automated dependabot updates broke the stub, so doing a bulk-update to remove that issue.
---
=> QA-803 Updating the Koa Stub to remove dependabot alerts

deploy/scripts/src/cri-lime/test.ts
Add an overview of what this pull request changes
- spikeI2HighTraffic: {
...createScenario('passport', LoadProfile.spikeI2HighTraffic, 4, 6)
}
- perf006Iteration2PeakTest: {
passport: {
startRate: 1,
preAllocatedVUs: 20,
maxVUs: 72,
stages: [
{ target: 12, duration: '13s' },
{ target: 12, duration: '30m' }
],
exec: 'passport'
}
}
---
to perform PERF006-Iteration2
---
=> QA-813 PERF006-IT2 profile for passport-limeCRI

deploy/scripts/src/txma/clientEnrichment.ts
Adds the peak and spike PERf006 Iteration 1 load profiles for the TxMA `sendRegaularEventWithEnrichment` scenario.
- Adds the `perf006Iteration2PeakTest` and `spikeI2HighTraffic` profiles for the TxMA `sendRegaularEventWithEnrichment` scenario.
- Removes the `sendSingleEvent` and `sendRegularEvent` Load profiles as they're no longer relevant to this script.  
---
To run PERF006 Iteration 2 spike and peak tests for the TxMA Event-Streaming-Platform.
=> [QA-814] Adding PERF006 I2 Load Profiles for TxMA

deploy/scripts/src/bravo/vc-storage.ts
The EVCS load profile(vc-storage.ts) has been updated to test spike and peak, 
refer the below 
```
...createScenario('persistVC', LoadProfile.spikeI2HighTraffic, 35, 15),
...createScenario('summariseVC', LoadProfile.spikeI2HighTraffic, 35, 15),
...createScenario('updateVC', LoadProfile.spikeI2HighTraffic, 32, 15)
},
persistVC: {
startRate: 1,
preAllocatedVUs: 100,
maxVUs: 576,
stages: [
{ target: 120, duration: '121s' },
{ target: 120, duration: '30m' }
],
exec: 'persistVC'
},
summariseVC: {
startRate: 2,
preAllocatedVUs: 100,
maxVUs: 264,
stages: [
{ target: 120, duration: '121s' },
{ target: 120, duration: '30m' }
],
exec: …
```
=> QA-816: Updated EVCS load profile for Perf006 Iteration 2 tests

deploy/scripts/src/ais/test.ts
Added the load profiles for the PERF006 Iteration2 Peak test for PersistIV & RetrieveIV scenarios.
- Peak Test Iteration2 profile was added for the PersistIV & RetrieveIV scenarios.
---
To run PERF006 iteration 2 peak tests for AIS
---
=> Update AIS script to include PERF006 I2 tests

deploy/scripts/src/fraud/test.ts
Adds the `peakTest` load profile to the fraud script, which starts at 50j/s and ramps up to 250j/s in 4s, which is then maintained for 6 minutes. 
- adds the `PeakTest` load profile for the `fraud/test.ts` script
---
to run a test for Fraud SSF Inbound ramping from 50j/s to 250j/s in 4 seconds, and maintaining that load for 6 minutes.
=> [QA-818] Adding a load profile for Fraud SSF Inbound

deploy/scripts/src/fraud/test.ts
Adds 3 new load profiles to the `fraud/test.ts` script
Adds 3 load profiles of the below to the `fraud/test.ts` script:
1. maintain 50j/s for 6 minutes
2. maintain 100j/s for 6 minutes
3. maintain 380j/s for 6 minutes
---
To run the 3 above tests
=> [QA-818] Adding load profiles to the fraud SSF script

deploy/scripts/src/fraud/test.ts
Adds three new load profiles to the `fraud/test.ts` script
Adds 3 new load profiles to the `fraud/test.ts` script to test the following:
- 50j/s for 8 seconds 
- 150j/s for 3 minutes 
- 200j/s for 3 minutes 
---
To run the above three tests for fraud SSF inbound
=> [QA-818] adding new load profiles for the Fraud SSF script

deploy/scripts/src/ais/test.ts
Changed the target for the retrieveIV peak test.
- The target of the retrieveIV scenario was increased from 33rps to 303rps.
- the MaxVU was increased to 909.
- the ramp up time was increased to 139 seconds.
---
AIS has been able to handle large amounts of traffic (5700rps). 33rps is too low and would be a waste of time and resources.
---
=> Changed the target for AIS peak test

deploy/scripts/src/ais/test.ts
Update the pageContentCheck for the retrieveIV scenario.
- pageContentCheck changed from 'Perf Testing' to 'intervention'
---
The previous string used was incorrect and causing the Test being run for AIS to fail.
---
=> Update pageContentCheck in AIS script

deploy/scripts/src/bravo/vc-storage.ts
Load profile changes for Perf006 Iter2 Spike Test
...createScenario('persistVC', LoadProfile.spikeI2HighTraffic, 35, 16),
...createScenario('updateVC', LoadProfile.spikeI2HighTraffic, 35, 16),
...createScenario('summariseVC', LoadProfile.spikeI2HighTraffic, 32, 15)
},
To update the spikeI2HighTraffic load profile
=> QA-827 : Load Profile updates -  EVCS for PERF006 Iteration2- Spike Test

deploy/scripts/src/cri-orange/otg.ts
Load profile updated for OTG similar to hmrc check
spikeI2LowTraffic: {
...createScenario('otg', LoadProfile.spikeI2LowTraffic, 1) //rounded to 1 from 0.4 based on the iteration 2 plan
},
ninoCheck: {
startRate: 1,
preAllocatedVUs: 100,
maxVUs: 400,
stages: [
{ target: 1, duration: '1s' },
{ target: 1, duration: '30m' }
],
exec: 'otg'
}
}
---
PERF006 Iteration2
---
=> QA-828-2 Load profile updated for OTG similar to hmrc check

deploy/scripts/src/fraud/test.ts
Reduces the duration of the `load100` profile for the fraud script. 
- Reduces the duration to 3 minutes for the `load100` load profile in the `fraud/test.ts` script. 
---
To run a test at a target volume of 100 messages per second for 3 minutes
=> [QA-818] Reducing the duration for the 100j/s fraud load profile.

deploy/scripts/src/fraud/test.ts
Adds a `load75` profile to the `fraud/test.ts` script
- reduces the `load50` duration from 6m to 3m
- adds a `load75` which has a target volume of 75j/s for 3 minutes. 
---
To run tests with the above load profiles.
=> [QA-818] Adding more load profiles to the fraud script

deploy/scripts/src/cri-kiwi/BAV.ts, deploy/scripts/src/cri-kiwi/f2f-cic.ts
Add an overview of what this pull request changes
- spikeI2LowTraffic: {
...createScenario('FaceToFace', LoadProfile.spikeI2LowTraffic, 1), //rounded to 1 from 0.4 based on the iteration 2 plan
...createScenario('CIC', LoadProfile.spikeI2LowTraffic, 1)
},
spikeI2LowTraffic: {
...createScenario('BAV', LoadProfile.spikeI2LowTraffic, 1) //rounded to 1 from 0.4 based on the iteration 2 plan
},
PEAK Tests
BAV: {
startRate: 1,
preAllocatedVUs: 10,
maxVUs: 100,
stages: [
{ target: 1, duration: '1s' },
{ target: 1, duration: '30m' }
],
exec: 'BAV'
}
}
FaceToFace: {
startRate: 1,
preAllocatedVUs: 10,
maxVUs: 100,
stages: [
{ target: 3, …
=> QA-837 Spike and Peak load profiles for CRI KIWI

deploy/scripts/src/fraud/test.ts
Adds the `load250` load profile to the `fraud/test.ts` script
- Adds the `load250` load profile to the `fraud/test.ts` script which runs at a target volume of 250 iterations per second for a 6 minute steady-state duration. 
---
To run a test for Fraud SSF Inbound at a target volume of 250j/s for 6 minutes.
=> [QA-818] Adding the load250 profile for fraud SSF inbound

deploy/scripts/src/txma/clientEnrichment.ts
Adds the PERF006 Iteration 3 peak load profile to the `txma/clientEnrichment.ts` script, for Iteration 3 peak testing of TxMA ESP & Audit-Service
- Adds in a new `perf006I3PeakTest` load profile with a target of 1,136 and a ramp-up duration of 518s. 
---
To run an Iteration 3 peak test for TxMA ESP & Audit-Service
=> [QA-846] Adding the I3 peak load profile for TxMA ESP & Audit-Service

deploy/scripts/package-lock.json, deploy/scripts/package.json
Remove `data-vocab` dependency to unblock deployment
- Remove `data-vocab` from `package.json` to unblock deployment
---
data-vocab dependency is causing the build and push workflow to fail upon merging. This blocks all deployments in performance testing. Hence this is being removed to unblock perf test deployments.
---
- [Failed Github action](https://github.com/govuk-one-login/performance-testing/actions/runs/14220717766)
=> [QA-848]: Remove data-vocab dependency to unblock deployment

deploy/scripts/src/ipv-core/test.ts
Adds in the Iteration 3 peak load profiles for IPV Core `identity` and `idReuse`
- Adds the `perf006Iteration3PeakTest` load profile for the `identity` and `idReuse` scenarios with target volumes of 16 and 24 respectively. 
---
To run Iteration 3 peak tests for IPV Core.
=> [QA-850] Adding Iteration 3 peak profiles for IPV Core

.github/workflows/publish.yaml, deploy/scripts/package-lock.json, deploy/scripts/package.json
Add data vocab dependency
- Added the `data-vocab` package dependency.
- Update the `Docker Build and Push` github workflow to allow permissions to access the package
---
To use `data-vocab` package in the `performance-testing` scripts
---
- Guidance in the [https://github.com/govuk-one-login/performance-testing/blob/main/.github/workflows/publish.yaml](url) repo to allow permissions
=> [QA-849]: Add data vocab dependency

deploy/scripts/src/bravo/vc-storage.ts
Adds the Iteration 3 peak load profiles for EVCS.
- Adds the `perf006Iteration3PeakTest` load profiles to the `bravo/vc-storage.ts` script for the `persistVC`, `updateVC`, and `summariseVC` scenarios. 
---
to run Iteration 3 peak tests for EVCS.
=> [QA-859] Adding I3 peak load profiles to EVCS.

deploy/scripts/src/cri-lime/test.ts
Peak Load profile changes for Lime CRI scenarios
Load profiles for `drivingLicence`, `drivingLicenceAttestation`, `fraud`, `passport` scenarios 
---
To conduct Perf006 iteration 2 peak tests - `perf006Iteration3PeakTest`
---
=> QA-866 - Peak load profile updates for Lime CRI

deploy/scripts/src/cri-kiwi/ipvr.ts
Adds Iteration 2 peak and spike load profiles for IPVR.
- Adds the `perf006Iteration2PeakTest` and `spikeI2HighTraffic` load profiles to `cri-kiwi/ipvr.ts` with volumes of:
- peak test: `authEvent` - 11j/s, `allEvents` - 0.3j/s
- spike test: `authEvent` - 32j/s, `allEvents` - 1j/s
---
To run iteration 2 peak and spike tests for IPVR
=> [QA-826] Adding Iteration 2 load profiles to IPVR

deploy/scripts/src/cri-kiwi/BAV.ts
Adding PEAK Load profile to BAV
* Adds the perf006Iteration3PeakTest  load profiles to cri-kiwi/BAV.ts with volumes of:
* peak test: BAV- 0.16 per sec  (9.6 Journeys/min)
---
To Run PERF006-IT3 
---
NA
=> [QA-876] Adding PEAK Load profile to BAV

deploy/scripts/src/cri-kiwi/ipvr.ts, deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts, deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
adds in a wait time to the IPVR script, and adds the issuing country to the `F2F_YOTI_START` payload.
- adds a sleep of 5 seconds between each TxMA event being sent to the IPVR SQS queue
- Adds the issuing country to the `F2F_YOTI_START` payload.
---
So the IPVR scenario reflects the real-world scenario more, ensuring `AUTH_IPV_AUTHORISATION_REQUESTED` is sent before `F2F_YOTI_START`.
=> [QA-826 Adding wait time into the IPVR script.

deploy/scripts/src/cri-kiwi/ipvr.ts
Updates the timeunit of the `perf006Iteration2PeakTest` `allEvents` scenario.
Updates the timeunit of the `perf006Iteration2PeakTest` `allEvents` scenario to '10s'
---
- Run run an `allEvents` `perf006Iteration2PeakTest` test with a target of 0.3 iterations per second.
=> [QA-826] Updating the allEvents PERF006I2 timeunit.

deploy/scripts/src/ipv-core/test.ts
Add M1C peak test load profile for IPVCore
- Add identityM1C peak test load profile for IPVCore using PERF006 Iteration 3 peak test volumes
---
To test Fraud Resilience M1C changes on IPV Core at PERF006 Iteration 3 peak test volumes
---
=> QA-886 Add M1C peak test load profile for IPVCore

deploy/scripts/src/cri-lime/test.ts
Lime(Fraud) load profile updates/correction with right Pre & Max vusers
The PreAllocated & Max vusers were incorrectly mentioned during the last test and hence couldnt achieve the targeted TPH. This PR is raised to update the preAllocatedVUs to 48 & maxVUs to 96
Pre & Max vusers were incorrect to reach the throughput of 16 iterations per second
=> QA-908 : Lime(Fraud) load profile updates/correction with right Pre & Max vusers

deploy/scripts/src/ipv-core/test.ts
Add in idReuse load profile for identityM1CPeakTest
- Add idReuse load profile for identityM1CPeakTest
---
To test a Combined idReuse and identityM1CPeakTest
---
=> Add idReuse load profile for identityM1CPeakTest

deploy/scripts/src/cri-orange/address.ts
Address CRI load profile changes for Perf006 I3 
---
Address CRI load profile will be updated to simulate 16 iters/sec. The test will run for 30 mins, after the rampup in 161s
---
To peak test Address CRI against I3 volume
---
=> QA-917:Address(Orange CRI):Perf006-I3 Peak test load profile update

deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/data/addressMEData.csv
Add Address Manual Entry scenario
- Added a separate `addressME` scenario to mimic the manual address entry scenario.
- Added a separate test data file `addressMEData.csv` with the test data to be used for manual entry scenario.
---
To test the manual entry scenario alongside the happy path scenario.
=> [QA-933]: Add Address Manual Entry scenario

.github/workflows/publish.yaml
Update working directory in Docker build and push
- Update working directory to `./deploy/scripts` in Docker build and push workflow
---
Correcting the path of the working directly to fix the workflow failures.
=> [QA-849]: Update working directory in Docker build and push

deploy/scripts/src/authentication/test.ts, deploy/scripts/src/common/utils/config/load-profiles.ts
Added load profiles for iteration 3 spike test
- Added a common load profile for signUp,ID proving, CRIs etc. called `createI3SpikeSignUpScenario`
- Added a common load profile for ID reuse, Sign in scenarios called `createI3SpikeSignInScenario`
- Updated Authentication script to include these load profiles at Iteration 3 target.
---
To conduct Iteration 3 spike tests
=> [QA-937]: Added load profiles for iteration 3 spike tests

deploy/scripts/src/cri-lime/test.ts
Adds the PERF006 Iteration3 Spike Test profiles for CRI-Lime `passport`, `fraud`, `drivingLicence`, and `drivingLicenceAttestation`. 
- Adds the `perf006Iteration3SpikeTest` profile for CRI-Lime `passport`, `fraud`, `drivingLicence`, and `drivingLicenceAttestation`. 
---
To run Iteration 3 spike tests
=> [QA-939] Adding CRI-Lime I3 Spike profiles

deploy/scripts/src/ipv-core/test.ts
Update IPV core script with Iteration 3 spike test profiles
- Add `createI3SpikeSignUpScenario` for `identity` scenario.
- Add `createI3SpikeSignInScenario` for `idReuse` scenario. 
---
To conduct spike tests for IPV core scenarios based on Iteration 3 plan.
=> [QA-941]: Update IPV core script with Iteration 3 spike test profiles

deploy/scripts/src/common/utils/config/load-profiles.ts
Fix createI3SpikeSignUpScenario load prrofile.
- The 33% load step is incorrectly divided by 10 which reduces it further.
---
To conduct load test at correct load profiles.
=> [QA-937]: Fix sign up spike load profile

deploy/scripts/src/cri-orange/kbv.ts
PERF006 Iteration3 Spike Test profiles for CRI-Orange` KIWI`
- Adds the perf006Iteration3SpikeTest profile for CRI-Orange `KIWI`
KBV Target is 4.9 per sec
Iteration Duration is 12
RampupNFR is 50 
---
To Perform Perf006 Iteration3 Spike Tests
---
=> [QA-942] Add CRI-Orange KBV I3 spike profile

deploy/scripts/src/common/utils/config/load-profiles.ts, deploy/scripts/src/olh/test.ts
Creates an iteration 3 spike load profile specific for OLH.
- creates the `createI3SpikeOLHScenario` function in `load-profiles.ts` to enable OLH scenarios to ramp at 2t/s/s while still maintaining load during 33% volume steady-states.
- imports the `createI3SpikeOLHScenario` into `olh.ts` with relevant target volumes, iteration durations, and ramp-up durations. 
---
=> [QA-948] Adding OLH iteration 3 spike profiles

deploy/scripts/src/cri-orange/nino-check.ts, deploy/scripts/src/cri-orange/otg.ts
PERF006 I3 Spike Test Load profiles for NINO_CHECK and OTG
-  For NinoCheck
target : 5/10 (0.49 Iterations/Sec)
iterationDuration : 6 Sec
rampUpNFR: 6
-  For OTG
target : 5/10 (0.49 Iterations/Sec)
iterationDuration : 3 Sec
rampUpNFR: 6
---
To perform PERF006 I3 Spike Tests
---
=> [QA-951] Perf006 I3 load profiles for HMRC-check and OTG 

deploy/scripts/src/cri-kiwi/BAV.ts
Spike Test Profile for BAV(CRI KIWI)
-   SPIKE Test Load profile for I3 changes as below
target : 5/10 (0.49 Iterations/Sec rounded to 0.5)
iterationDuration : 21 Sec ( 7 Steps in a Iteration)
rampUpNFR: 6 ( RampupNFR time for 0.5 J/sec)
---
To perform PERF006-I3 Spike testing
---
=> [QA-955]: PERF006-I3 Spike Test Profile for BAV(CRI KIWI)

deploy/scripts/src/cri-kiwi/f2f-cic.ts
Adds the `FaceToFace` and CIC Iteration 3 spike test load profiles 
- Adds the `perf006Iteration3SpikeTest` load profile to `cri-kiwi/f2f-cic.ts` for the `FaceToFace` and `CIC` scenarios.
---
To run Iteration 3 Spike tests for CIC and F2F.
=> [QA-956] Adding CIC & F2F I3 Spike Test Load Profiles

deploy/scripts/src/txma/clientEnrichment.ts
Adds Iteration 3 spike load profiles for the `sendRegularEventWithEnrichment` scenario to test TxMA ESP & Audit-service
- Adds the `createI3SpikeSignInScenario` load profiles to `txma/clientEnrichment.ts` for the `sendRegularEventWithEnrichment` scenario
---
To run an iteration 3 spike test for TxMA ESP & Audit-Service
=> [Qa-961] Adding Iteration 3 spike load profiles to TxMA ESP & Audit-service

deploy/scripts/src/cri-orange/address.ts
This pull-request is to add Iteration 3 spike load profile for Orange Address CRI
---
Adds `perf006Iteration3SpikeTest` load profile to cri-orange/address.js. The load profile has two scenarios - address & addressME
Spike steady state volumes
address : 10 iters/sec
addressME : 39 iters/sec
---
To run an iteration 3 spike test for Orange Address CRI
---
=> QA-960 : Address CRI Iteration3 Spike Test - Load profile update

deploy/scripts/src/cri-kiwi/ipvr.ts
Add spike test profile for IPVR BE
- Auth Event (Target - 71/s, Ramp Up - 7 seconds)
- All Events (Target - 1.2/s, Ramp Up - 13 seconds)
---
To run a spike test for IPVR BE scenario.
=> [QA-962]: Add spike test profile for IPVR BE

deploy/scripts/src/cri-kiwi/f2f-cic.ts
Removes the invalid 'BRP' path from the CRI-Kiwi Face to Face performance test script
- Removed 'BRP' from the `paths` array in the performance test script.
---
The script was attempting to process a 'BRP' path which did not have a corresponding case statement, leading to errors and impacting throughput. Removing this invalid path ensures the script only processes valid paths, improving the accuracy and reliability of performance test results.
---
=> [QA-963]: Remove 'BRP' path from F2F script

deploy/scripts/src/authentication/test.ts
Add regression load profile to Auth & Orch script
- Update Auth & Orch script with regression load profile of 5X production volume during march
---
To conduct Perf006 Iteration 3 regression tests
---
=> QA-968: I3 Regression load profile update to Auth & Orch scripts

deploy/scripts/src/common/utils/config/load-profiles.ts, deploy/scripts/src/cri-lime/test.ts, deploy/scripts/src/cri-orange/address.ts
Load profile for PERF006 - regression testing
-  created  a load profile function for createI3RegressionScenario
Ramp up  to rampupNFR and Steady State 5 minutes
---
To Perform PERF006-Regression tests
---
=> [QA-972]: Adding regression Load profiles for Address and Fraud

deploy/scripts/src/authentication/test.ts
Updates the soak test volumes for auth & orch `signIn` and `signUp` to 3 and 2 iterations per second respectively. 
Updates the `perf006Iteration3SoakTest` volumes for `authentication/test.ts` `signIn` and `signUp` to 3 and 2 iterations per second respectively. 
---
To run an auth & orch soak test at the above target volumes.
=> [QA-970] Updating the soak test volumes for Auth & Orch.

deploy/template.yaml
Updates the TiCF SQS Queue build name in the CloudFormation template. 
- Updates the SQS Queue name for TiCF Build environment in `template.yaml`
---
To enable us to send messages to the TiCF Build SQS Queue during performance tests.
=> [QA-971] Updating The TiCF Build SQS Queue name in CF Template

deploy/Dockerfile
Update k6 version in the Dockerfile
- Update k6 version in xk6 build using the output-statsd extension to create the k6 binary
---
To fix compatibility issues with the latest crypto module used in the repo.
=> [QA-978]: Update k6 version to build the output-statsd extension

deploy/scripts/src/mobile/mobile-backend/testSteps/backend.ts, deploy/scripts/src/mobile/mobile-backend/utils/appCheckToken.ts, deploy/scripts/src/mobile/mobile-backend/utils/config.ts, deploy/scripts/src/mobile/utils/crypto.ts, deploy/scripts/src/mobile/utils/signatureV4.ts, deploy/scripts/src/mobile/v2-mobile-backend-get-client-attestation.ts
- Adds `getClientAttestation.ts` script for getting a client attestation from the Mobile Backend. This simulates a user logging in to the 'V2 app' and client attestation that is needed to get tokens from STS.
- Script for getting a client attestation from the Mobile Backend. This includes only the calls to the Mobile Backend as part of a login journey and does not make any calls to STS.
---
Adds scripts for STS performance tests.
---
=> DCMAW-12496: Mobile Backend performance tests

deploy/scripts/src/authentication/test.ts
To add load profile for iteration 4 peak test
Updated deploy/scripts/src/authentication/test.ts with SignIn & SignUp load profiles for iteration 4 peak test
---
To execute iteration 4 peak tests
---
=> QA-988 : Add I4 Peak test Load profiles to Authentication script

deploy/scripts/src/ipv-core/test.ts
Update Iteration 4 IPVCore load profiles
- Update Iteration 4 IPVCore load profiles
---
to enable Iteration 4 peak test on IPV Core
---
=> QA-989 Update Iter 4 IPVCore load prof

deploy/scripts/src/cri-lime/test.ts
This adds peak test load profiles for CRI Lime (Passport, DL CRI, DL Attestation, and Fraud) for Perf006 Iteration 4.
Passport: 4.7 requests/second, 48s ramp-up
DL CRI: 5.9 requests/second, 60s ramp-up
DL Attestation: 4.7 requests/second, 48s ramp-up
Fraud: 47 requests/second, 471s ramp-up
---
These profiles are needed to execute the Iteration 4 peak performance tests.
---
=> [QA-1028]: Add Perf006 Iteration 4 Peak Test Profiles for CRI Lime

deploy/scripts/src/txma/clientEnrichment.ts
Adds a load profile with a target of 2000j/s for TxMA `sendRegularEventWithEnrichment`
`
- Adds in the `PeakTest2000` load profile with a target of 2000j/s and growth-rate of 2.2j/s/s for the `sendRegularEventWithEnrichment` scenario.
---
To run a test for TxMA SS at 2000j/s
=> [QA-1026] Adding a 2000j/s load profiles for TxMA

deploy/scripts/src/mobile/v2-sts-get-service-access-token.ts
mobile V2 STS Peak load profile for I4
- Target Load 45 J/Sec
- Rampup time 451 sec
- Peak Test Duration - 30 min
---
to Perform PERF006-Iteration4 testing
---
=> [QA-1032]: mobile V2 STS PEAK load profile for I4

deploy/scripts/src/cri-lime/test.ts
To add Lime DL & DLA I4 peak test profile
DL CRI : `5.9 iters/sec`
DLA CRI : `9.9 iters/sec`(rounded from 9.87) 
Added DL & DLA I4 Peak test profile `perf006Iteration4PeakTest`
---
To test Lime DL & DLA I4 peak scenario
---
=> QA-1031: Load Profile update for Lime DL & DLA I4 Peak tests

deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
This adds peak test load profiles for DCMAW -Mobile (FE+BE) for Perf006 Iteration 4.
- Mobile(FE=BE): 45 requests/second, 451s ramp-up
---
This profile is needed to execute the Iteration 4 peak performance tests.
=> [QA-1055]: Add Perf006 I4 PeakTestProfile for DCMAW -Mobile (FE+BE)

deploy/scripts/src/common/utils/config/load-profiles.ts
Update I4 PeakTest SignUp Load Profile to adjust the VU counts
- Target for pre Allocated VUs should not be 10x hence the change is `const preAllocatedVUs = Math.round(((target / 10) * iterationDuration) / 2)`
- Target for Max VUs should not be 10x hence the change is `const maxVUs = Math.round((target / 10) * iterationDuration)`
---
To initiate the right number of pre-allocated and max virtual users during the peak test for iteration 4.
=> [QA-1060]: Update I4 PeakTest SignUp and Sign In Load Profile to adjust the VU counts

deploy/scripts/src/cri-orange/kbv.ts
Experian KBV I4 Peak load profile
- Target Peak Load - 4.7 J/sec
- Ramp up duration 48 sec
---
to perform PERF006 Iteration4 testing
---
=> [QA-1067]: Address CRI - Experian KBV I4 Peak load profile

deploy/scripts/src/cri-kiwi/BAV.ts
Adds the peak test load profile for CRI-KIWI-BAV in Perf006 Iteration 4.
- BAV: 0.5 requests/second, 6s ramp-up
---
To execute the Iteration 4 peak performance test
---
=> [QA-1070]: Add Load Profile for I4 PeakTest

deploy/scripts/src/cri-orange/nino-check.ts
To add I4 Peak test load profile to ninoCheck script and conduct the test
- ninoCheck load profile has been updated to target .5 iters/second
---
To conduct CheckHMRC I4 Peak Test
---
=> QA-1077: Add I4 Peak test Load profile to CheckHMRC(ninoCheck)

deploy/scripts/src/cri-kiwi/f2f-cic.ts
Adds the peak test load profile for CRI-KIWI-CIC and F2F in Perf006 Iteration 4.
- CIC: 1.2 requests/second, 13s ramp-up
- F2F: 1.2 requests/second, 13s ramp-up
---
To execute the Iteration 4 peak performance test
---
=> [QA-1079]:Add Load Profile for I4 PeakTest

deploy/scripts/src/cri-kiwi/ipvr.ts
Adds the peak test load profile for CRI-KIWI-IPRV BE in Perf006 Iteration 4.
- All Events: 1.2 requests/second, 13s ramp-up
- Auth Event: 43 requests/second, 21s ramp-up
---
To execute the Iteration 4 peak performance test
---
=> [QA-1080]: Add Load Profile for I4 PeakTest

deploy/scripts/src/common/requestGenerator/txmaReqFormat.ts, deploy/scripts/src/common/requestGenerator/txmaReqGen.ts, deploy/scripts/src/fraud/ticf.ts
Adds in and eventID to the `signInSuccess` TiCF payloads
- Adds in an `event_id` to the `AUTH_CODE_VERIFIED` and `AUTH_AUTHORISATION_INITIATED` TxMA payloads
---
To send complete payloads with eventIDs in the TiCF `signInSuccess` scenario
=> [QA-563] Adding eventIDs to TiCF payloads

deploy/scripts/src/common/requestGenerator/txmaReqFormat.ts, deploy/scripts/src/common/requestGenerator/txmaReqGen.ts, deploy/scripts/src/fraud/ticf.ts, deploy/scripts/src/txma/clientEnrichment.ts, deploy/scripts/src/txma/test.ts
Adds in eventIDs to all the TxMA payloads used in the TiCF CRI script
- Adds event_id into the TxMA payloads in the `txmaReqGen.ts` and `txmaReqFormat.ts` files.
- Adds eventIDs into the `txma/test.ts`, `txma/clientenrichment.ts`, and `fraud/ticf.ts` scripts where they use the above payloads. 
---
To ensure we're sending the correct payloads to TiCF CRI.
=> [QA-563] Adding eventIDs to all TxMA Payloads used in TiCF

deploy/scripts/src/txma/clientEnrichment.ts
This pull request adds the Iteration 4 peak load profile to the `txma/clientEnrichment.ts` performance test script. This profile will be used for Iteration 4 peak testing of the TxMA ESP and Audit-Service.
Adds the `perf006Iteration4PeakTest` load profile with:
- Target throughput: 2,423 journeys per second
- Ramp-up: 66 seconds
---
To execute an Iteration 4 peak test for TxMA ESP & Audit-Service
---
=> [QA-1091]:Adding the I4 peak test load profile for TxMA ESP & Audit-Service

deploy/scripts/src/cimit/test.ts
CIMIT - Correct the load test target
- Updated the load test target to 1880 as we are using the `createI4PeakTestSignUpScenario`
---
To run a performance test of CIMIT at 188 j/s
=> [QA-1096]: CIMIT - Correct the load test target

deploy/scripts/src/cimit/test.ts
CIMIT -  Move Get Contra Indicator call at the end
- `GetContraIndicator` call moved at the end to view the status of `PutContraIndicator` and `PostMitigation` API calls.
---
To conduct CIMIT performance tests
=> [QA-1100]: CIMIT -  Move Get Contra Indicator call at the end

deploy/scripts/src/bravo/vc-storage.ts
This pull request adds the Iteration 4 spike load profile to the `bravo/vc-storage.ts` performance test script for testing the VC Storage service.
The following load profiles are introduced for the specified capability:
* **PersistVC:**
* Target throughput: 113 iterations per second
* Ramp-up time: 1131 seconds
* **UpdateVC:**
* Target throughput: 113 iterations per second
* Ramp-up time: 1131 seconds
* **SummariseVC:**
* Target throughput: 129 iterations per second
* Ramp-up time: 60 seconds
---
This change enables execution of the Iteration 4 spike performance test for the VC Storage service.
=> [QA-1107]: Account(Bravo)-VC Storage-Add Load Profile for I4 SpikeTest

deploy/scripts/src/cri-lime/test.ts
Adding Iteration 4 Spike Test Load profile for LIME CRI (passport, DL, DL attest and Fraud)
- Passport : Target 11.3 j/sec  and ramp-up 114sec
- DL : Target 14.1 j/sec and ramp-up 142 sec
- Dl attest : Target 11.3 j/sec  and ramp-up 114 sec
- Fraud: Target 1130 j/sec  and ramp-up 1131 sec
---
To Perform PERF006-Iteration 4 testing
---
=> [QA-1106]: I4 Spike test Load profiles for LIME cri

deploy/scripts/src/fraud/ticf.ts
Creates one single function, `ticf()`, in the `fraud/ticf.ts` script that executes all four scenarios (`signInsuccess`, `signUpSuccess`, `identityProvingSuccess`, and `identityReuseSuccess`) inside it.
- changes the loadProfile and groupMap for the new `ticf()` function
- creates a new single function, `ticf()`, which calls the `signUpSuccess`, `signInsuccess`, `identityProvingSuccess`, and `identityReuseSuccess` functions in order, maintaining a constant userID between them. 
---
To ensure all four scenarios are being executed with the same userID in the correct order, for a successful performance test.
=> [QA-1109] TiCF Script changes

deploy/scripts/src/cimit/test.ts
Add I4 spike test target for CIMIT
- Add I4 spike test target for CIMIT at a target of 452 j/s (4 X ID proving)
---
To run a spike test for CIMIT
=> [QA-1112]: Add I4 spike test target for CIMIT

deploy/scripts/src/fraud/ticf.ts
Adds a longer smoke test, an I4 peak test, and I4 Spike test load profiles to the `ticf` script. 
- Adds a smoke test with a 5 minute duration for the `ticf` scenario 
- Adds an iteration 4 peak test profile with a target of 47j/s for the `ticf` scenario 
- Adds an iteration 4 spike test profile with a target of 129j/s for the `ticf` scenario 
---
So we can run `ticf` performance tests at desired volumes.
=> [QA-1118] Adding load profiles to the TiCF Script

deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/kbv.ts
Add I4 Spike profiles to Address and Address Manual Entry (ME)
- KBV - Target Throughput 11.3 j/sec and Ramp up 114 Sec
---
---
=> [QA-1120]: I4 Spike profile for (Orange CRI ) KBV

deploy/scripts/src/fraud/ticf.ts
Adds a 2 second wait time between the payload generation in each function.
- Adds a `sleep(2)` wait time between the payload generation functions in the TiCF script.
---
To ensure TxMA event payloads are being send with different timestamps.
=> [QA-1109] Adding a wait between payload generation in the TiCF script

deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
Edits the date formats in the TxMA events used in the `ticf` script
- changes the date formats from 'xxxxxxxx' to 'xxxx-xx-xx' in the `IPV_ADDRESS_CRI_VC_ISSUED` and `IPV_DL_CRI_VC_ISSUED` payloads.
---
To send the correct payloads during a `ticf` performance test.
=> [QA-1109] changing the TxMA Event Date Formats for the TiCF Script.

deploy/scripts/src/cri-orange/address.ts, deploy/scripts/src/cri-orange/nino-check.ts
I4 Spike Test load profile update for Address & CheckHMRC CRIs
Based on the iteration 4,
- Total Address spike target is 113 iters/sec
- Address happy path : 10 iters/sec
- Address Manual entry : 103 iters/sec
-   CheckHMRC : 1.1 iters/sec
---
To Perform Iteration 4 spike tests
---
=> QA-1125 : Orange I4 Spike Test profile update for Address & CheckHMRC

dns/acm-certificate.yaml, dns/dns.yaml
Switch the base stacks to use CFN Exports & !ImportValue instead of SSM.
SSM triggers Security Alerts, and isn't needed for these stacks; as the core template doesn't depend on the SSM params either.
- Remove the SSM parameter resource from ACM
- Switch ACM to use the same !ImportValue as the deploy/template.yaml syntax for its dependency on DNS Zone ID.
- Remove the SSM parameter resource from DNS
---
The SSM parameters didn't resolve in the correct order to work for the core template; therefore in reverting to CFN Export / !ImportValue - it keeps the pattern consistent across the repo.
---
=> QA-1086 Remove SSM parameters, in favour of CFN Imports.

deploy/scripts/src/ipv-core/test.ts
This pull request adds soak and stress test load profiles for the IPV Core (`identity` and `id-reuse` scenarios).
* **Added two load profiles:**  `perf006Iteration4SoakTest` and `perf006Iteration4StressTest` in `ipv-core\test.ts` script.  Each profile defines configurations for both `identity` and `id-reuse` scenarios.
* **Soak Test Profile (`perf006Iteration4SoakTest`):**
* **`identity`:**
* Start Rate: 1
* Time Unit: 10s
* Pre-allocated VUs: 54
* Max VUs: 108
* Stages: Ramp up to 3 VUs over 31 seconds, then hold at 3 VUs for 6 hours.
* **`idReuse`:**
* Start Rate: 2
* Time Unit: 1s
* Pre-allocated VUs: 12
* Max VUs: 24
* Stages: Ramp up to 4 VUs over 3 seconds, then hold at 4 VUs for 6 hours.
* **Stress Test Profile (`perf006Iteration4StressTest`):**
* **`identity`:**
* Start Rate: 1
* …
=> [QA-1132]: IPV Core - Add Load Profile for I4 Soak and Stress Test

deploy/scripts/src/fraud/ticf.ts
Edits the order in which payloads are generated and messages are sent to SQS queues for the TiCF script.
- changes each function in the TiCF script so that the payloads are generated and then the event is sent to SQS 1 by 1, instead of all the payloads being generated, and then all the events being sent to SQS.
---
To ensure the timestamps of the events generated are different.
=> [QA-1133] Editing the order of SQS send messages and payload generation in TiCF CRI.

deploy/scripts/src/olh/test.ts
I4 Smoke & Peak test(re-run) have reported failures in changeEmail, changePassword, changePhone & deleteAccount. These scenarios have updated to reflect the same request & response as seen in browser
- Get request query parameters have changed for transactions
- B01_ChangeEmail_04_ClickChangeEmailLink
- B02_ChangePassword_04_ClickChangePasswordLink
- B03_ChangePhone_05_EnterCurrentPassword
- B04_DeleteAccount_04_ClickDeleteAccountLink
- Page Content validation text at B04_DeleteAccount_06_DeleteAccountConfirm transaction has changed to `You’ve deleted your GOV.UK One Login`
---
To update the changes observed in browser to the script
---
=> QA-1123: OLH Script changes for changeEmail, changePassword, changePhone & deleteAccount scenarios

deploy/scripts/src/mobile-id-check-async/test.ts
Add Spike Test Profile for mobile ID Check async v2
- Target Throughput : 107. 4 journeys/Sec
- Ramp up time 1075 sec
---
To perform PERF006 Iteration 4 testing
---
=> [QA-1135]: Spike Test Profile for mobile ID Check async v2

deploy/scripts/src/fraud/ticf.ts
Updated the `identityProvingSuccess` request payload and removes the `AUTH_CODE_VERIFIED` event from `signInSuccess`.
- Edits the `vtr` of the `identityProvingSuccess` request payload
- Removes the `AUTH_CODE_VERIFIED` event from `signInSuccess` function.
---
To ensure the correct events and request payloads are being sent for each scenario.
=> [QA-1136] Updating the identityProvingSuccess& signInSuccess in TiCF.

deploy/scripts/src/ipv-core/test.ts
This pull request fixes a script at the `B01_Identity_02_GoToFullJourneyRoute` scenario, specifically the `02_CoreCall` step. The issue was caused by a change in the page content, which broke the existing page content check.
Updated the `pageContentCheck` in the `02_CoreCall` of the `B01_Identity_02_GoToFullJourneyRoute` step.  The expected text has been changed from "Do you live in the UK, the Channel Islands or the Isle of Man?" to "Where do you live?"
To fix the script execution and execute the Regression test.
---
=> [QA-1148]: IPV-Core - Script Update - page content check

deploy/scripts/src/txma/clientEnrichment.ts
Add spike test profile for TxMA client enrichment scenario
- Add spike test profile for TxMA client enrichment scenario (Target 6261 events/s, Ramp up - 169 s & Estimated maximum iteration duration - 3s)
---
To run iteration 4 spike test for TxMA
=> [QA-1153]: Add spike test profile for TxMA client enrichment scenario

deploy/template.yaml
Increases the `MaxSessionDuration` of `PerformanceTesterRole`
- Increases the `MaxSessionDuration` of `PerformanceTesterRole` to 5400 seconds (default 3600 seconds)
---
The maximum session duration of the PerformanceTester role is 3600 seconds. This results in HTTP-403 errors (due to token expiry) after 1 hour for tests where this role is assumed and of those tests are longer than 1 hour. This PR is to increase the Maximum Session Duration to 5400 seconds.
=> [QA-1155]: Increase the MaxSessionDuration of PerformanceTesterRole

deploy/scripts/src/mobile/mobile-backend.ts, deploy/scripts/src/mobile/sts.ts
Profile change for  Mobile wallet Credential Issuance for BE and STS 
- Mobile Wallet Backend Credential Issuance
Ramp up 18 sec and Steady state duration is 55 min
- Mobile Wallet STS Credential Issuance
Ramp up 18 sec and Steady state duration is 55 min
---
To perform Peak testing for Wallet
---
=> [QA-1160] Profile change for  Mobile wallet Credential Issuance for BE and STS 

deploy/scripts/src/ipv-core/test.ts
- This pull request corrects the URL used for the redirect in the `02_CoreCall` step of IPVCore identity scenario test script.
- Removed `env.ipvCoreURL` from the `http.get` call in `02_CoreCall` and used `res.headers.Location` directly.
---
- The previous code was prepending `env.ipvCoreURL` to the redirect URL obtained from `res.headers.Location`, resulting in a duplicated URL and causing the redirect to fail.  This change uses the complete redirect URL directly from the `Location` header, resolving the URL duplication issue.
---
=> [QA-1162]:Correct redirect URL in 02_CoreCall

deploy/scripts/src/cri-lime/data/ClaimsTextPayload.ts
Update DVLA test data to extend expiry dates
- Update DVLA test data to extend expiry dates
---
To prevent data rejections
---
=> QA-1106 Update test data for DVLA

deploy/scripts/src/mobile/mobile-backend.ts
- Removes the test step which sends the `WALLET_CREDENTIAL_CONSENT_GIVEN` event as this will no longer be sent in the Mobile Backend Wallet journey. 
---
=> Remove WALLET_CREDENTIAL_CONSENT_GIVEN event from Mobile Backend Wallet test

deploy/scripts/src/cri-lime/test.ts
---
This PR is to add iteration 5 peak test load profiles to Lime CRIs
---
- Added perf006Iteration5PeakTest for the following scenarios
- Passport: 5.7 iters/sec, rampup - 58secs
- Driving Licence: 7 iters/sec, rampup - 71 secs
- Driving Licence Attestation: 12 iters/sec, rampup - 121 secs
- Fraud : 57 iters/sec, rampup - 571 secs
---
To conduct Passport CRI test
=> QA-1174: Add Perf006 Iteration 5 Peak profiles for Lime(passport, DL, DLA & Fraud)

.github/CODEOWNERS
Replace references to `spot-team` with `trust-and-reuse-team` in `CODEOWNERS`.
- Replace references to `spot-team` with `trust-and-reuse-team` in `CODEOWNERS`.
---
The SPOT team have rebranded as Trust and Reuse and have new Github teams, the old teams are going to be removed.
=> SPT-1518: Update CODEOWNERS to reflect SPOT team name change

deploy/scripts/src/mobile-id-check-async/test.ts
Removes the first request to the ID Check async JWKS endpoint.
This endpoint is called by the sts-mock /token endpoint for this part of the journey. i.e. the mock is already making this request and we don't need to call it directly from K6.
---
=> DCMAW-13943: Remove duplicate test step from id check async

deploy/scripts/src/cri-orange/nino-check.ts
Add Iteration 5 peak test load profile to Check HMRC script
- Use createI4PeakTestSignUpScenario to add Iteration 5 load profiles
---
Run performance tests against Iteration 5 targets
---
=> QA-1195 Check HMRC Add I5 Peak prof

deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
This PR is to add I5 peak test profile to DCMAW - Mobile (FE+BE) script
Added `perf006Iteration5PeakTest` profile with throughput 54 iters/sec and rampup 541 secs
---
To conduct I5 peak test
---
=> QA-1200 : Add Perf006 I5 PeakTestProfile to DCMAW -Mobile (FE+BE) script

deploy/scripts/src/fraud/ticf.ts
Adds the iteration 5 peak and spike load profiles to the TiCF CRI script
- Adds the `perf006Iteration5PeakTest` and `perf006Iteration5SpikeTest` load profiles to the `fraud/ticf.js` script.
---
To run iteration 5 tests for TiCF CRI
=> [QA-1201] Adding TiCF CRI I5 load profiles

deploy/scripts/src/cri-kiwi/f2f-cic.ts
This PR is to add I5 peak test profile to KIWI CIC & F2F cri scripts
---
- Added `perf006Iteration5PeakTest` profile to both CIC & F2F scripts, with throughput 1.4 iters/sec and rampup 15 secs
---
To perform Iteration 5 peak tests
---
=> QA-1203: Add Perf006 I5 PeakTestProfile to KIWI CIC & F2F scripts

deploy/scripts/src/mobile-id-check-async/test.ts
- This pull request adds a new load profile, `perf006Iteration5CombinedPeakTest`, to the `test.ts` performance script, to  execute the I5 combined peak test for both the `idCheckAsyncSignUp` and `idCheckAsyncSignIn` scenarios.
- Added `perf006Iteration5CombinedPeakTest` to the `profiles`.
- Configured `perf006Iteration5CombinedPeakTest` with :
- `idCheckAsyncSignUp`: Target throughput = 54 TPS and ramp-up = 541s .
- `idCheckAsyncSignIn` :Target throughput = 65 TPS and ramp-up = 30s .
- To execute the iteration 5 combined peak test for Mobile-idCheckAsync.
=> [QA-1205]: Mobile:IdCheckAsync: Add profile for I5 Peak test

deploy/scripts/src/mobile/sts.ts
Adds the I5 peak load profile to the Mobile STS script for the `authentication` scenario.
- Adds the `perf006Iteration5PeakTest` profile for the `authentication` scenario in the mobile STS script.
---
To run an I5 peak test for mobile STS
=> [QA-1214] Adding the I5 peak load profile to Mobile STS.

deploy/scripts/src/ipv-core/test.ts
This pull request adds a new load profile, `perf006Iteration5SpikeTest`, to the ipv-core.ts performance script, to execute the I5 spike test for IPV Core.
- Added `perf006Iteration5SpikeTest` to the profiles with a Target throughput and ramp-up of 
-- 113 TPS for Identity proving with a ramp-up of 1131s
-- 162 TPS for Id Reuse with a ramp-up of 74s 
---
- To execute the iteration 5 spike test for Mobile-backend.
---
=> [QA-1218]: IPVCore: Add profile for I5 Spike test

deploy/scripts/src/spot/test.ts
Adds the I5 Spike profile for SPOT
- adds the `perf006Iteration5SpikeTest` load profile for `spot` in the `spot/test.js` script.
---
To run an I5 SPOT spike test.
=> [QA-1223] Adding the I5 SPOT spike load profile.

deploy/scripts/src/cri-orange/address.ts
Add I5 Spike Test profile for Address
-    address - Target throughput is 10 j/s, Rampup is 101 sec
address Manual Entry - Target throughput is 101.8 J/s, Rampup is 1019 sec),
internationalAddress - Target throughput is 1.2 J/sec, Rampup is 13 sec)
---
To Perform PERF006 - I5 Testing
---
=> [QA-1230]: I5 Spike Test profile for Address

deploy/scripts/src/mobile/mobile-backend.ts
To add Mobile backend Iteration 5 spike profile to the script
- Created a new profile `perf006Iteration5SpikeTest` with `getClientAttestation` scenario for Iteration 5 spike volume
---
To conduct Iteration 5 spike tests
---
=> QA-1248: Add Mobile BE- I5 Spike Profile to the script

deploy/scripts/src/authentication/test.ts
Add I5 spike test profile for Auth & Orch
- Iteration 5 spike test profile with targets as - Sign Up (113 j/s) and Sign In (162 j/s)
---
To run the I5 spike test for Auth & Orch
=> [QA-1246]: Add I5 spike test profile for Auth

deploy/scripts/src/authentication/test.ts
This pull request modifies the authentication script to **prevent the downloading of static content** .
- Updated the `env.staticResources` variable logic within the k6 scripts to disable static content fetching by default.
---
- To prevent downloading static content.
=> [QA-1258] Authentication: Disable static content downloads

deploy/scripts/src/ais/test.ts
This PR is to add Perf006 Iteration 6 peak profile into AIS script
- Added perf006Iteration6PeakTest profile in the ais/test.ts script to target the peak volume of
- persistIV : 30 iters/sec, rampup 15 seconds
- retrieveIV : 312 iters/sec, rampup 48 seconds
---
To conduct Iteration 6 peak test
---
=> QA-1282 : Add Perf006 Iteration 6 peak profile to AIS script 

deploy/scripts/src/txma/clientEnrichment.ts
This pull request updates the `txma/clientEnrichment.ts` performance test script. It adds new load profiles for Iteration 6 peak and spike tests for the TxMA ESP and Audit-Service.
The following load profiles have been added:
- perf006Iteration6PeakTest: Targets a throughput of 3,820 journeys per second with a 571-second ramp-up.
- perf006Iteration6SpikeTest: Targets a throughput of 6,472 journeys per second with a 571-second ramp-up.
---
To execute Iteration 6 peak and spike tests and to assess the performance of the TxMA ESP & Audit Service.
=> [QA-1301]: TxMA ESP & Audit-Service: Add Iteration 6 Peak and Spike Test Load Profiles

deploy/scripts/src/mobile/mobile-backend.ts
QA-1300 I6 Regression Load profile for MobileBE
- Mobile BE getClientAttestation- 54 TPS 
- Mobile BE WalletCredentialIssuance- 38 TPS
---
to perform PERF006 Iteration 6 testing
---
=> [QA-1300]: I6 Regression Load profile for MobileBE

deploy/scripts/src/spot/test.ts
This pull request adds the Iteration 6 Spike test load profile to the spot/test.ts performance test script.
- A new profile, `perf006Iteration6SpikeTest`, has been created for SPoT with the following target throughput:
- Target throughput: 317 iterations per second
---
This change enables execution of the Iteration 6 Spike test for SPoT
=> [QA-1308] SPOT: Add I6 Spike test load profile

deploy/scripts/src/authentication/test.ts
Adds I6 spike test load profile in `deploy/scripts/src/authentication/test.ts`
Adds the perf006Iteration6SpikeTest with the following target throughput:
- For **signUp** scenario the target throughput is 183 iterations per seconds with a ramp-up of 1831 seconds.
- For **signIn** scenario the target throughput is 260 iterations per seconds with a ramp-up of 119 seconds.
---
To execute the Iteration 6 spike test for Auth&Orch.
=> [QA-1320] Authentication: Add I6 Spike test profile

deploy/scripts/src/ipv-core/test.ts
Adding IPVcore I6 spike test profile
- Identity': Target Throughput is 570 Journeys/sec, Ramp up is 571 sec
-  IdReuse', Target Throughput is 260 Journeys/sec, Ramp up is 119 sec
---
To perform PERF006 testing
---
=> [QA-1323]: IPVcore I6 spike test profile

deploy/scripts/src/ais/test.ts
AIS - Corrected the ramp up duration for Retrieve IV scenario.
- Corrected the ramp up duration for Retrieve IV scenario to 119 seconds.
---
To run a spike test for AIS
=> [QA-1326]: Correct ramp up duration for Retrieve

deploy/scripts/src/mobile/sts.ts
PR to update the Re-Auth test data(persistentSessionId) and conduct combined peak test
- Created a new set of test data(persistentSessionId) and uploaded into mobile/data folder
- Created a new profile perf006Iteration6PeakTest for authentication, reauthentication & walletCredentialIssuance peak tests
---
To conduct combined peak test
---
=> QA-1303a: Mobile Combined(STS Auth, Re-Auth & Cred Issuance) - Update re-auth test data & conduct combined peak test
