govuk-one-login/performance-testing

- deploy/template.yaml
VpcConfig was incorrectly indented one level too deep.
> PLAT-909 Fixed property bad indentation

- deploy/template.yaml
Syncing changes made for `di-accounts-performance` to fix VPC config.
Also some minor linting changes were picked up.
> [QA-163] Sync VPC template from di-accounts-performance

- .github/dependabot.yml
Adding a `dependabot.yml` file to allow Dependabot to raise PRs for version updates weekly
> [QA-168] Add dependabot.yml to manage versions

- .github/workflows/post-merge.yaml
Reverts alphagov/di-devplatform-performance#60
> Revert "Bump alphagov/di-devplatform-upload-action-ecr from 1.0.2 to 1.0.3"

- .github/workflows/post-merge.yaml
Update to publish to new non-prod performance account.
> PLAT-1505 Update post-merge.yaml

- deploy/template.yaml
- Added production to support the new environment.
> PLAT-1505 Added production as allowed Environment Value

- .github/workflows/push.yml
- deploy/otel-config-template.yaml
- deploy/performance-tester-permissions.yaml
- deploy/scripts/src/data/changePhoneNumber_TestData.csv
- deploy/scripts/src/test-accountManagement.ts
- deploy/scripts/src/testLoginCheck.ts
- deploy/template.yaml
Adding changes from [`di-accounts-performance`](https://github.com/alphagov/di-accounts-performance)
> [QA-184] Add changes from di-accounts-performance

- deploy/scripts/src/data/addressStub.json
- deploy/scripts/src/data/drivingLicenceStub.json
- deploy/scripts/src/data/fraudStub.json
- deploy/scripts/src/data/kbvData.json
- deploy/scripts/src/data/passportStub.json
- deploy/scripts/src/testIPVCore.ts
- deploy/template.yaml
Adding changes from [`di-ipv-core-performance`](https://github.com/alphagov/di-ipv-core-performance)
> [QA-186] Add changes from di-ipv-core-performance

- .gitignore
- deploy/scripts/src/test-auth-journey.ts
- deploy/template.yaml
Adding changes from [di-authentication-performance](https://github.com/alphagov/di-authentication-performance)
> [QA-183] Add changes from di-authentication-performance

- .github/dependabot.yml
- deploy/scripts/src/testIPVCore.ts
To investigate the discrepancy in dynatrace stats
> [QA-142]: Debug statement for custom metric

- deploy/scripts/src/testIPVCore.ts
Removing debug statements from IPV core script
> [QA-142]: Remove debug statements

- deploy/scripts/src/test-accountManagement.ts
- deploy/template.yaml
Eliminated from variables: ORCH_STUB_URL, CORE_URL, RP_STUB, BASE_URL, EMAIL_OTP, PHONE_OTP
Added in parameter-store: CORE_URL, ORCH_STUB_URL, RP_STUB, BASE_URL, PHONE_OTP
[QA-194](https://govukverify.atlassian.net/browse/QA-194)
[QA-194]: https://govukverify.atlassian.net/browse/QA-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-194]: Updated repo for consistency in environment variables

- deploy/scripts/src/testIPVCore.ts
Updated the IPV core workload model based on the latest updates in the below NFRs - 
PERF006v1.0
PERF008v1.0
> [QA-200]: Update IPV Core workload model

- deploy/scripts/README.md
Updating the role name in the `deploy/scripts/README.md` to reflect the new performance testing role.
> [PLAT-1601] Update Tester Role Name

- deploy/template.yaml
Changes:
Enable debug OTEL logging to investigate the latest errors.
> [QA-142]: Debug OTEL logging for investigation

- deploy/otel-config-template.yaml
Changes done
- Updated send_batch_size as 1000 in OTEL config to match with the send_batch_max_size config.
> [QA-142]: Update OTEL config

- deploy/template.yaml
Changes:
- Remove additional logging statement for otel.log
> [QA-142]: Remove additional OTEL logging

- .github/pull_request_template.md
Adding a template file for pull requests
Changes:
- Added `.github/pull_request_template.md` with an initial template for new pull requests
---
To ensure important information including links to tickets and description of changes is added to new pull requests, to help reviewers understand the context of changes
> [QA-203] Add Pull Request Template

- deploy/scripts/src/accounts/test.ts
Updated account management script based on latest changes in the application
- Form data in the SMS login journey (POST request to `/enter-code`) has changed. 
- The endpoint for the GET request after successful login has changed to `/security` from `/settings`
- Page content has changed in the response of the POST request to `/enter-password` while following the SMS OTP authentication path.
- Above changes have been done in the Email change, Password change, Delete account and phone number change scenarios.
---
Scripts are being updated based on the latest changes in the application.
> [QA-214]: Updated Account Management scripts

- deploy/scripts/src/mobile/test.ts
- deploy/scripts/src/mobile/utils/README
- deploy/scripts/src/mobile/utils/functions-mobile-journey.ts
Added a test for calling only the /start and /authorize with corresponding volumes from AC2.
- README.md file
- test.ts file -> added dcmawStartAuthorizeRequest test.
- test.ts file -> added volumes inside profiles
- Targeting this starting point of the user journey in an isolated test scenario
- on the getSessionId() function we are calling /authorize and  postToVerifyURL() function (which is calling the /start)
> DCMAW-5592: Performance Testing | Create performance test script for FE Authorize Journey

- deploy/scripts/src/cri-kiwi/test.ts
Updated the payloads for some requests
- Payload for B02_FaceToFace_02_Continue 
- Payload for B02_FaceToFace_05_NationalIDEEA_CurrentAddress 
- Payload for B02_FaceToFace_05_EUDL_CurrentAddress
- Value for B02_FaceToFace_05_NonUKPassport_WhichCountry
- Value for B02_FaceToFace_06_EUDL_WhichCountry
- Value for B02_FaceToFace_06_NationalIDEEA_WhichCountry
---
For having an up to date journey
[QA-219]: https://govukverify.atlassian.net/browse/QA-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-219] Updated the journey

- .github/workflows/feature-branch-publish.yaml
Add a new github workflow to test and publish changes to the development environment from feature branches
- Added `.github/workflows/feature-branch-publish.yaml` which publishes can publish a branch of choice to the development environment
---
To test changes to the infrastructure and CloudFormation before creating pull requests
---
- [Github Environment Documentation](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment)
> [QA-224] Feature branch testing workflow

- deploy/scripts/src/cri-lime/data/drivingLicenceDVAData.csv
- deploy/scripts/src/cri-lime/data/drivingLicenceDVLAData.csv
- deploy/scripts/src/cri-lime/test.ts
Updated the Driving Licence happy path
- Removed data from csv file because it was not consistent
- Updated accordingly payload and endpoint for some of the request
---
To validate the Driving Licence happy path scenario k6 script.
[QA-235]: https://govukverify.atlassian.net/browse/QA-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-235] Updated the happy path for Driving Licence

- deploy/scripts/src/mobile/README.md
Fix readme formatting error and update run command guidance.
- Removed erroneous -e flag in readme
- Added backticks to close code block in readme
---
Formatting/typo fixes.
> DCMAW-5594: Fix readme code block

- deploy/scripts/src/mobile/utils/test-client.ts
Added BE URL to the test client request
- added backend URL to the postTestClientStart() function
---
build is failing due to the allowed domains specified in the egress rules in the performance test account. Adding the BE URL to the test client request will return the ApiLocation with an allowed domain.
---
> DCMAW-5611: Smoke test journeys in Build

- deploy/scripts/src/cri-kiwi/test.ts
Updated the text from the verify page content
- What is your name? -> Enter your name exactly as it appears on your photo ID
- What is your date of birth -> Enter your date of birth
- Check your details -> Confirm your details
---
For validating the happy path
[QA-249]: https://govukverify.atlassian.net/browse/QA-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-249] Updated CIC happy path script

- deploy/scripts/src/cri-lime/test.ts
- deploy/template.yaml
Updated passport CRI script
- Updated the passport scenario based on the updated steps in the user journey
- Updated CF template to include the required environment variable.
---
Previous script of passport CRI was based on the old user journey using Orchestrator stub. Current approach with all Lime and Orange CRIs is to start with IPV core stub.
---
- [Passport CRI scenario](https://govukverify.atlassian.net/wiki/spaces/DID/pages/3346661421/Performance+Test+Scenarios#Passport-CRI---Build-Environment)
> [QA-236]: Updated Passport script

- deploy/scripts/src/cri-kiwi/test.ts
Added BE requests and updated the verify response body 
- Added IPV stub request
- Added POST /checkdetails
- Added POST /token
- Added POST /userinfo
- Updated the verify response body
---
To achieve 100% coverage on the BE requests and validate the journey
---
[QA-257]: https://govukverify.atlassian.net/browse/QA-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-257] Updated F2F script

- deploy/scripts/src/ipv-core/test.ts
Update the core script to include changes to the start page.
- Update page content checks wherever applicable.
- Updated step 2 and 3 of the user journey to reflect the latest changes.
---
To update the scripts based on the latest changes in the user journey.
---
- [IPV Core happy path scenario](https://govukverify.atlassian.net/wiki/spaces/DID/pages/3346661421/Performance+Test+Scenarios#IPV-Core-Full-Journey---Build-Environment-Using-Stubs)
> [QA-263]: Updated IPV score script

- deploy/scripts/src/mobile/testSteps/frontend.ts
- deploy/scripts/src/mobile/utils/test-client.ts
Added tag to authorize request 
- added tag name to authorize the request
- changed existing tag name for postTestClientStart method
---
Relevant request name in dynatrace
---
> DCMAW-6068: Update request tag for mobile authorize script

- deploy/reporting/create-summary.sh
Updated reporting script to create a CSV for http_req_duration statistics
- Added a section in the reporting script to create a separate CSV for http_req_duration statistics
---
To include http_req_duration in reporting.
---
> [QA-271]: Output http_req_duration stats from JSON to CSV

- deploy/scripts/src/mobile/testSteps/backend.ts
Changed tags name to <Method> <endpoint> for all the groups used in the BE E2E test.
Format Document
- backend.ts: changes all the tags name
---
Relevant and consistent request name in dynatrace
> DCMAW-6068: added tags for BE requests

- deploy/scripts/src/ipv-core/test.ts
Updated IPV core script based on the latest page content changes
- Page content changed for the request in the group `B01_Core_04_DCMAWContinue_2_Core`.
---
The script has been updated to accommodate the page content changes.
> [QA-279]: IPV core script update

- deploy/scripts/src/accounts/test.ts
Updated Account Management scripts based on OIDC stub changes
- Updated `Change Email`, `Change Password` and `Delete Account` scenarios in account management script based on updates in the user journey
- Replaced `http.post` requests with `submitForm() `in all the 3 scenarios.
-` Change Phone Number` is blocked as the dummy phone number data is currently unavailable.
---
To update account management scripts based on the changes in the user journey
---
- [Account Management Performance Test Scenarios](https://govukverify.atlassian.net/wiki/spaces/DID/pages/3346661421/Performance+Test+Scenarios#Pod---Account)
> [QA-290]: Updated account management scripts

- deploy/scripts/src/accounts/test.ts
Added tags to Account management scenarios
Added tags to the HTTP requests of below scenarios
- Change Email
- Change Password
- Delete Account
---
To ensure k6 doesn't treat each URL (with unique data) as unique time series. This results in resource contention at load generator.
> [QA-302]: Added tags to account management script

- deploy/scripts/src/accounts/test.ts
Update load profile of Account Management Script
For Change Password, Change Email and Delete Account, change the following:
- Increase the maximum virtual users to 3000
- Increase the target to 100 iterations per second
---
To conduct a load test for account management scenarios at increased target load
---
> [QA-304]: Updated load profile of Account Management script

- deploy/scripts/src/authentication/test.ts
Added tags to groups and requests of Auth scenarios
-Added tags to groups and requests of `signUp` and `signIn` scenarios in the Auth script.
---
Without tags, k6 sends unique time-series record for each URL with a unique value. This results in load injector issues at high volumes. Tags are being added to prevent this.
> [QA-308]: Added tags to groups and requests of Auth scenarios

- deploy/scripts/src/accounts/test.ts
Updated load profile for Accounts - Change Phone scenario
For the Change Phone scenario:
- Increase the maximum virtual users to 3000
- Increase the target to 100 iterations per second
---
To conduct a load test for the Account Management - Change Phone scenario at increased target load
---
> [QA-309]: Updated load profile for Change Phone scenario

- deploy/scripts/src/common/unit-tests.ts
Adding unit tests for JavaScript library utility functions
- Added unit tests for the following files
- `/utils/jslib/aws-sqs`
- `AWSConfig` class
- `SQSClient` class
- `/utils/jslib/index`
- `findBetween()`
- `normalDistributionStages()`
- `randomIntBetween()`
- `randomItem()`
- `randomString()`
- `uuidv4()`
- `/utils/jslib/url`
- `URL` class
- `URLSearchParams` class
---
This is to ensure that the jslib files and functions are working as intended, and to ensure they exbhibit the expected properties when called in scripts
---
- [k6 jslib Documentation](https://k6.io/docs/javascript-api/jslib/)
- [Mozilla `URL` Documentation](https://developer.mozilla.org/en-US/docs/Web/API/URL)
- [Mozilla `URLSearchParams` Documentation](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)
> [QA-254] Unit tests for JavaScript library functions

- deploy/scripts/package-lock.json
Update npm packages
```
npm update --save-dev
npm audit fix
```
Output
> ```
> added 3 packages, removed 11 packages, changed 35 packages, and audited 265 packages in 16s
> up to date, audited 265 packages in 679ms
> ```
---
Periodic fixing of npm package dependencies, to keep project up to date
> [QA-211] Update npm package dependencies

- deploy/scripts/src/ipv-core/data/drivingLicenceData.ts
- deploy/scripts/src/ipv-core/data/passportData.ts
Updated the payloads used in IPV core happy path journey
- Updated the payloads in the stub calls in IPV core happy path journey (both Passport and Driving Licence scenarios)
---
To fix the script error (HTTP-500 error on the Orchestrator stub call).
> [QA-340] : Updated IPV core stub data  payloads

- deploy/scripts/src/cri-kiwi/ipvr.ts
- deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts
- deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
Updated IPVR script according to updated payloads
- Added `F2F_DOCUMENT_UPLOADED` event payload
- Updated `F2F_YOTI_START` and `IPV_F2F_CRI_VC_CONSUMED` payloads with new fields
---
Team Kiwi has made changes to these payloads so our scripts need to be updated accordingly
---
> Updated IPVR script with updated payloads

- deploy/scripts/src/common/unit-tests.ts
- deploy/scripts/src/common/utils/custom_metric/counter.ts
- deploy/scripts/src/ipv-core/test.ts
Custom metric to track number of iterations in a test
- Added custom metrics Iterations_Started and Iterations_Completed in the IPV core script.
- Added a value to the Iterations_Started metric before the start of the first transaction.
- Added a value to the Iterations_Completed metric after the check of the last transaction.
---
To track the number of iterations started and completed in a test.
> [QA-268]: Added custom metric to track iterations

- deploy/scripts/src/accounts/id-reuse.ts
- deploy/scripts/src/accounts/test.ts
- deploy/scripts/src/authentication/test.ts
- deploy/scripts/src/btm/test.ts
- deploy/scripts/src/cri-kiwi/f2f-cic.ts
- deploy/scripts/src/cri-kiwi/ipvr.ts
- deploy/scripts/src/cri-lime/test.ts
- deploy/scripts/src/cri-orange/address.ts
- deploy/scripts/src/cri-orange/kbv.ts
- deploy/scripts/src/spot/test.ts
- deploy/scripts/src/txma/test.ts
added in custom metrics to track iteration count of all scripts.
[deploy/scripts/src/accounts/id-reuse.ts]
[deploy/scripts/src/accounts/test.ts]
[deploy/scripts/src/authentication/test.ts]
[deploy/scripts/src/btm/test.ts]
[deploy/scripts/src/cri-kiwi/f2f-cic.ts]
[deploy/scripts/src/cri-kiwi/ipvr.ts]
[deploy/scripts/src/cri-lime/test.ts]
[deploy/scripts/src/cri-orange/address.ts]
[deploy/scripts/src/cri-orange/kbv.ts]
[deploy/scripts/src/spot/test.ts]
[deploy/scripts/src/txma/test.ts]
Added actions to count iterations_started and iterations_completed by scenario.
---
to track the number of iterations completed in the tests.
---
> Added changes to track iteration count in all scripts

- deploy/reporting/create-summary.sh
Enhancements in the reporting utility to filter results by time
- Added time filter for each action in the utility.
- Added actions to count `iterations_started` and `iterations_completed` by scenario.
- Added action to count total number of requests (passed + failed)
---
To add further details in the analysis of the performance test results.
> [QA-362]: Reporting Utility Enhancements

- deploy/scripts/src/cri-lime/data/passportData.csv
edited the passportData.csv to contain new test data.
[deploy/scripts/src/cri-lime/data/passportData.csv]
changed test data to 
```
passportNumber,surname,firstName,middleNames,birthDay,birthMonth,birthYear,expiryDay,expiryMonth,expiryYear
321654987,DECERQUEIRA,KENNETH,,08,07,1965,01,01,2030
```
---
to enable successful completion of the user journey in the test scenario.
---
> [QA-365]: Edited test data is passportData.csv test file

- deploy/scripts/src/authentication/test.ts
Corrected the custom metric of iterations_completed in the auth test script.
[deploy/scripts/src/authentication/test.ts]
• Moved the custom metric of iterations_completed to the correct position in the signUp scenario of authentication/test.ts
---
to ensure the number of iterations completed and started are counted correctly.
---
> [QA-370] Corrected iterations_completed metric

- deploy/scripts/src/cimit/test.ts
Add load profiles for CIMIT scenarios
- Added low volume test and load test profiles for all 3 CIMIT scenarios (putContraIndicators, getContraIndicatorCredentials, postMitigations)
---
To conduct volume tests for CIMIT scenarios.
> [QA-372]: Add load profiles for CIMIT scenarios

- deploy/scripts/src/ipv-core/data/idReuseTestData.csv
- deploy/scripts/src/ipv-core/test.ts
Added ID reuse happy path scenario in core
- Added ID reuse happy path scenario in core.
---
To conduct performance tests for ID reuse scenario in core.
---
- `[Scenario Details](https://govukverify.atlassian.net/wiki/spaces/DID/pages/3346661421/Performance+Test+Scenarios#IPV-Core---ID-Reuse-Scenario)`
> [QA-380] : Added ID reuse scenario for core

- deploy/scripts/src/ipv-core/test.ts
Update IPV core script based on latest changes in user journey.
- Added test email address input in stub calls for both DL and Passport scenarios.
---
To validate script post changes in the user journey.
> [QA-394] : Update IPV core script based on latest changes

- deploy/scripts/src/accounts/test.ts
Added scenario for Contacts Page in OLH script.
- Added scenario for Contacts Page in OLH script.
---
To re-test/validate an incident.
> [QA-395] : Add contacts page scenario in OLH script

- deploy/scripts/src/authentication/test.ts
Updated low volume profile for Auth scenarios
- Update low volume profile for sign up to 30 journeys/sec and sign in to 8 journeys/sec with a ramp up of 15 minutes and steady state of 30 minutes.
---
To conduct a combined low volume test for both scenarios.
> [QA-404]: Updated low volume profile for Auth test

- deploy/reporting/create-summary.sh
Removed unnecessary report creation from the utility.
- Removed the report creation for entire test (without time filter)
---
To speed up the reporting utility
> [QA-420]: Removed duplicate report for request count

- deploy/scripts/src/ais/test.ts
Updated page content for the Retrieve IV check.
- Corrected the text check for Retrieve IV GET request
---
Test script validation
> [QA-408]: Updated page content for validation in Retrieve IV

- deploy/scripts/src/accounts/test.ts
Updated all scenarios except `changeEmail` to use `formSelector` 
- Added formSelector in each submitForm() call
- Modified the sign-out to a submitForm()
- did this for: `changePassword`, `changePhone`, `deleteAccount`, and `validateUser` scenarios.
---
sign-out is now a form so the response of each page contains this additional form. We need to use formSelector to accurately call the correct form for each page and make the script work.
> [QA-433] Update all scenarios in OLH script with formSelector

- deploy/scripts/src/authentication/test.ts
- removes the RP Stub check
- remove rpStubCheck boolean
- edit `B02_SignIn_05_AuthMFA_EnterTOTP POST` and `B02_SignIn_07_SMSMFA_EnterOTP POST` steps, to an `if > else` statement to only check for terms and conditions update, and remove the RP stub checks.
---
- to run a successful Authentication signIn journey
> [QA-447] Removing RP-stub check in Auth sign-in journey

- deploy/scripts/src/txma/test.ts
Updated TxMA load profiles to match NFR
- Updated target load in load and stress test profiles
- Removed redundant load profiles
---
To run the first TxMA tests for Shared Signals in line with the new NFR values
---
> [QA-449] TxMA - Updated load profiles to reflect new NFR value

- deploy/scripts/src/examples/dev-platform.ts
- deploy/template.yaml
Update the example script for testing the demo node app
- `deploy/scripts/src/examples/dev-platform.ts`:
- Updated environment variable names
- Updated endpoint to point to `/toy`
- Added a 200/s stress test target load profile
- `deploy/template.yaml`:
- Added environment variables to the parameter store 
---
Testing the demo node app to explore front-end configuration changes
> [QA-455] Demo node app testing

- deploy/scripts/src/accounts/vc-storage.ts
VC storage - Added a debug statement for test data creation 
- Added a debug statement to print `subjectID` in the `persistVC` script. This `subjectID` will be used as a test data in `SummariseVC` script.
- The results output will be saved in the Test Results S3 bucket.
---
To create bulk test data for summarise VC
> [QA-456]: Added a debug statement for data creation

- deploy/scripts/src/accounts/vc-storage.ts
Removed debug statement that was added for data creation in VC storage script
- Removed debug statement that was added for data creation in VC storage script
---
Data creation for SummariseVC is complete so the debug statement is not needed
> [QA-456]: Remove debug statement in VC storage script

- deploy/reporting/create-summary.sh
Modifications to speed up reporting utility
- Removed the error section as we are already extracting HTTP requests by status (pass + fail). This was a sort of duplication.
- Removed `group` from the `http_req_duration` csv creation process. We already have a separate section for group response time.
---
To speed up the reporting utility
> [QA-428]: Speed up reporting utility

- deploy/scripts/src/ipv-core/data/passportData.ts
- deploy/scripts/src/ipv-core/test.ts
Updated IPV core scripts based on latest changes in the journey
- Updated the query parameters in the GET request to Orch stub in all 3 scenarios (Passport, DL and ID reuse).
- Updated the Passport stub data.
---
To ensure the script used for perf testing is up to date with the changes in the application
> [QA-463]: Updated IPV core scripts based on latest changes in the journey

- deploy/scripts/src/cri-kiwi/BAV.ts
Changing the account number used as there is now a specific one required
- Changed account number in the bank details step
---
Smoke test was failing on the last step due to changes made where there is a specific account number required for the test user
---
> BAV CRI - Changed account number

- deploy/scripts/src/accounts/test.ts
- deploy/scripts/src/accounts/vc-storage.ts
- deploy/scripts/src/ais/test.ts
- deploy/scripts/src/cimit/test.ts
- deploy/scripts/src/cri-kiwi/BAV.ts
- deploy/scripts/src/cri-kiwi/f2f-cic.ts
- deploy/scripts/src/cri-lime/test.ts
- deploy/scripts/src/cri-orange/address.ts
- deploy/scripts/src/cri-orange/kbv.ts
- deploy/scripts/src/cri-orange/nino-check.ts
- deploy/scripts/src/ipv-core/test.ts
Response time percentiles added for remaining scripts based on the work done in #528 
Response time percentile changes updated in below scripts
- OLH
- Bravo (VC Storage and AIS)
- CIMIT
- Lime
- Orange
- IPV Core
---
To ensure response time percentiles are recorded in the k6 end of test summary report.
---
- #528
> [QA-458]: Update response time changes in remaining scripts

- deploy/scripts/src/accounts/test.ts
Update OLH scripts to use pageContectCheck utility.
- Updated 5 OLH scenarios to use pageContectCheck utility.
---
To ensure consistency across scripts.
> [QA-473]: Update OLH script to use pageContentCheck utility

- deploy/scripts/src/cri-orange/address.ts
Split core stub and CRI call in Address scenario
- Split core stub and CRI call in Address scenario
- Corrected the scenario name in the `groupMap` object.
---
To report the response time of core stub call and CRI call separately.
> [QA-475]: Split core stub and CRI call in Address scenario

- .github/workflows/koa-stub-main.yaml
- koa-stub/template.yaml
Workflow broken sue to Environment var not being used in template.yaml
> Fix workflow to allow stub to deploy

- .github/workflows/koa-stub-main.yaml
Workflow running in wrong working dir.
> QA-480: Fixed github workflow

- .github/workflows/koa-stub-main.yaml
> QA-480 Fix SAM Deploy Workflow step

- deploy/template.yaml
Gives codebuild container permission to execute-api: on all API GWs.
> QA-481Permission to invoke api

- deploy/template.yaml
> QA-481 Added execute-api to PerfTester role

- .github/workflows/koa-stub-main.yaml
Used .aws-sam build dir for upload path.
> QA-480 Fix workflow for SAM upload

- deploy/template.yaml
> QA-480 Add execute-api to policy, not role.

- deploy/scripts/src/ipv-core/test.ts
IPV Core - Changed a value in one of the steps to reflect the changes
- Changed a field for one of the steps to reflect the new value
---
The passport journey was failing due to a value of a field being changed. This PR fixes that.
---
> IPV Core - Fixed script due to recent changes

- deploy/scripts/src/ipv-core/test.ts
IPV Core Driving Licence journey - Changed a value in one of the steps to reflect the changes
- Changed a field for one of the steps to reflect the new value
---
The Driving Licence journey was failing due to a value of a field being changed
---
> IPV Core - Fixed Driving Licence script due to recent changes

- deploy/scripts/src/cri-orange/nino-check.ts
NiNO script updates to fix issues and optimise calls
- Fix the content check in `B02_Nino_02_AddUser` step
- Fix the `groupMap` name
- Remove additional call to core stub.
- Split the calls to core stub and NiNO CRI
---
To fix existing issues and reduce calls to core stub.
> [QA-498]: NiNO CRI script changes

- deploy/scripts/src/authentication/test.ts
Updated Auth load profile to run next test at target 1000
- Changed load profile for Sign In to target 1000
---
The next Auth Sign In test will be run at 1000 j/s (after the last Sign In test ran at target 500j/s achieved 490j/s)
> Auth - Update script to run Sign In script at target 1000

- deploy/scripts/src/accounts/vc-storage.ts
Added script for update VC scenario
- Modified the function for create VC script.
- Added a new function for update VC call.
- Added the script for update VC scenario.
---
To conduct performance tests for update VC
> [QA-511]: Update VC script

- deploy/scripts/src/accounts/vc-storage.ts
Remove page content check from update VC transaction
- Removed page content check from update VC transaction as the response status is HTTP-204 No Content.
---
To fix the check error for Update VC script.
> [QA-511]: Remove page content check from update VC transaction

- deploy/scripts/src/ipv-core/test.ts
Updated IPV core script based on the latest changes in the user journey
- Modified the body of a POST request to `/ipv/page/page-ipv-identity-document-start`
- Modified the page content for the request `/ipv/page/page-multiple-doc-check`
Changes have been done for both `Passport` and `Driving Licence` scenarios.
---
To fix the scripts for both `Passport` and `Driving Licence` scenarios.
> [QA-515]: Updated IPV core script based on the latest changes in the user journey

- deploy/scripts/src/ipv-core/test.ts
Added a scenario for isolated test for orchestrator stub
- Added a scenario for isolated test for orchestrator stub
---
To validate that the orch stub is not slow when executed in isolation at the NFR load.
> [QA-521] : Scenario for isolated orch stub test

- deploy/scripts/src/accounts/vc-storage.ts
Add debug statement in persist VC script
- Add debug statement in persist VC script after the completion of the iteration.
---
To create bulk test data for SummariseVC in the pipeline. The debug statement will be removed post data creation.
> [QA-524]: Add debug statement in persist VC script

- deploy/scripts/src/cri-orange/otg.ts
- deploy/template.yaml
Creates a performance test script for HMRC OTG
- created `cri-orange/otg.ts` to performance test HMRC OTG
- updated `template.yaml` with the OTG URL env variable 
---
To performance test HMRC OTG
> [QA-526] Creating the OTG Perf Test Script

- deploy/scripts/src/authentication/test.ts
Updated Auth sign in scenario to correct the Terms & Conditions page request
- Corrected the Terms & Conditions page request
---
To fix Auth sign in script.
> [QA-541]: Updated Auth sign in scenario

- koa-stub/template.yaml
Updates to add access log settings to see what the API Gateway is responding with, as the lambda logs show no errors.
- Add API Gateway LogGroup
- Send access logs to LogGrou[
- Turn on API Gateway tracing.
---
---
> QA-536 Added access logs to help gauge performance issues

- koa-stub/src/app.js
- koa-stub/src/controllers/callback.controller.js
- koa-stub/src/controllers/logout.controller.js
- koa-stub/src/controllers/start.controller.js
- koa-stub/src/package-lock.json
- koa-stub/src/package.json
- koa-stub/src/router.js
- koa-stub/src/tests/__snapshots__/app.test.js.snap
- koa-stub/src/tests/app.test.js
- koa-stub/src/utils/onelogin.util.js
Adds a test to ensure if userInfo returns a 401, the userinfo call will be retried after a backoff period.
- Detail individual changes in bullet points
---
---
> QA-536 retry on 401 error for /callback userinfo call

- deploy/scripts/src/ipv-core/test.ts
Update IPV Core scripts scenario for dev environment validation
- Changes in IPV core script to validate the passport, driving licence and id reuse scenarios in dev environment.
---
To conduct performance tests in dev environment.
> [QA-545]: Update IPV Core scripts scenario for dev environment validation

- deploy/scripts/src/cri-lime/hmrc-kbv.ts
Add new test script for HMRC KBV testing
- `deploy/scripts/src/cri-lime/hmrc-kbv.ts`: Added new test script
---
To performance test new CRI
> [QA-548] Add HMRC KBV script

- deploy/scripts/src/authentication/test.ts
Ensure's that the uniqueness of virtualUser with userId.
Follows guidelines: https://community.grafana.com/t/unique-login-for-each-virtual-user/99596 
---
In the auth test, the logs showed the same user was passing through the journey concurrently, causing an increase in errors.  This change (to derive from vu) ensures that no vu has a duplicate id when running concurrently through the system.
---
> QA-553 Ensure unique user data for each test

- deploy/scripts/src/bravo/vc-storage.ts
Updated line 68 of the vc-storage script.
- The file path in line 68 of the vc-storage script was changed to ./data/summariseSubjectID.csv
---
The path of the summarise test data csv is wrong which meant tests made in the pipeline for vc-storage were failing.
> Updating line 68 for the vc-storage script

- deploy/scripts/src/ipv-core/test.ts
- deploy/template.yaml
Updated IPV core passport script based on latest changes in user journey
- Updated the page content after the DCMAW stub step.
- Updated CloudFormation template with path for env variable. The respective parameter has been created in SSM.
---
To fix the IPV core script.
> [QA-576]: IPV Core: Updated script based on latest changes in user journey

- deploy/scripts/src/authentication/test.ts
- deploy/template.yaml
Update Auth scripts based on latest changes
- Updated signUp and signIn scenarios to use the new orch stub.
---
Auth user journeys have a new stub as the entry point as part of latest changes. The script changes are to reflect these changes in the user journeys.
> [QA-579]: Update Auth scripts based on latest changes.

- deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts
- deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts
- deploy/scripts/src/txma/test.ts
Update TxMA script with new approach
- Added a `AUTH_CREATE_ACCOUNT` primer event in the `setup()` function.
- Added a new function `sendRegularEvent()` with `AUTH_LOG_IN_SUCCESS` event.
---
To align TxMA script with the new approach.
> [QA-582]: Update TxMA script with new approach

- deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqFormat.ts
- deploy/scripts/src/cri-kiwi/requestGenerator/ipvrReqGen.ts
- Updating the IPVR Backend Payloads to match the TxMA Event Catalog 
- Add missing values to IPVR Backend payloads
---
- To successfully run an IPVR Backend test
> [QA-585] Updating the IPVR Backend Payloads

- deploy/scripts/src/authentication/test.ts
Updated Auth sign in scenario
- Fix auth sign in scenario to handle updated terms and conditions scenario. 
---
To fix the failures for auth sign in scenario during load test.
> [QA-586]: Updated Auth sign in scenario

- deploy/scripts/src/olh/test.ts
The load profile for the OLH script
- changePassword & deleteAccount were changed from 15 to 30
---
To test OLH at 30 journeys per second
---
> Changed the j/s for load profiles

- deploy/scripts/src/cri-kiwi/f2f-cic.ts
Updates the `FaceToFace` scenario of the `cri-kiwi/f2f-cic.ts` script to reflect dev changes
- Fixes various fields to reflect correct id and value names
- Updates the expiry date values to fall within 2025 so they're not 'expired'
---
To run a successful performance test for the `FaceToFace` user journey.
> [QA-594] Updating the F2F CRI-KIWI scenario

- deploy/scripts/src/cri-kiwi/BAV.ts
Fix page content check in BAV script
- Fix page content check in BAV script
---
To run performance test for BAV
> [QA-603]: Fix page content check in BAV script

- deploy/scripts/src/authentication/test.ts
Fix auth script issues
- Corrected the usage of the iterations completed counter in sign in scenario.
- Corrected the volume for sign in scenario for March 2025 
---
To fix issues identified during the smoke test
> [QA-669]: Fix auth script issues

- deploy/scripts/src/ipv-core/test.ts
Added new profiles for March 2025 Volumes to the existing ipv-core script
- Added loadMar2025, soakMar2025, spikeNFR & spikeSudden profiles
---
For the March 2025 Volumes
> Update IPV Core profiles

- deploy/scripts/src/ipv-core/test.ts
Creates new test data for the IPV-Core ID Reuse scenario
- New test data in the `idReuseTestData.csv` file
---
To run an IPV-Core ID Reuse Performance Test
> [QA-663] New data for IPV-Core IDReuse Scenario

- deploy/scripts/src/cri-orange/address.ts
Update scenario name in spikeNFR profile
- Update scenario name to `address` in spikeNFR profile.
---
To fix the incorrect scenario name.
> [QA-686]: Update scenario name in spikeNFR profile

- deploy/scripts/src/cri-orange/address.ts
An initial script for the international address scenario
- Adds a `internationalAddress(`) function for international Address CRI 
- Adds internationalAddress scenarios to the LoadProfiles
- creates a groupMap for international Address
---
- To run performance tests for the international address CRI
> [QA-733] Initial draft script for international address CRI

- deploy/scripts/src/cri-orange/address.ts
Updates a `pageContentCheck` for the address scenario
- Updated the pageContentCheck for the `B02_Address_03_SelectAddress` step
---
To run a successful performance test for Address CRI
> [QA-741] Updating pageContentCheck of address CRI script

- deploy/scripts/src/cri-orange/address.ts
Added a scenario for isolated performance test of the core stub.
- Added the function `coreStubCall()` with the single GET request to the core stub.
- Added a `ramping-vus` load profile for 400 concurrent users with a ramp up of 5 minutes and steady state of 5 minutes.
---
To conduct isolated performance tests for the core stub.
> [QA-739]: IPV Core Stub isolated test scenario

- deploy/scripts/src/olh/test.ts
Added an iteration duration in the createScenario function call.
- changeEmail - added a duration of 32
- changePassword - added a duration of 28 
- changePhone - added a duration of 32
- deleteAccount - added a duration of 24
- validateUser - added a duration of 40
- contactsPage - added a duration of 4
---
> Update scenarios to include iteration duration

- README.md
- deploy/scripts/README.md
Update ReadMe to remove % from the commands
- Updated ReadMe to remove  % from the commands
---
To fix the commands added to the readme.
> [QA-751]: Update ReadMe to remove %

- deploy/scripts/src/ipv-core/test.ts
Add Test data for ID reuse and update identity script
- Added fresh test data for ID reuse
- Updated Identity scenario with the latest changes in the journey
---
To run a low volume performance test for IPV core scenarios.
> [QA-754]: Add Test data for ID reuse and update identity script

- deploy/scripts/src/cri-lime/test.ts
Fix page content check of DL script
- Update the page content check for landing page of DL CRI scenario.
---
To execute a low volume test for DL CRI
> [QA-758]: Fix page content check of DL script

- deploy/scripts/src/cri-orange/address.ts
Add a profile for Address PERF006 iteration 1
- Added a profile for PERF006 iteration 1 for Address CRI
---
To conduct performance test for Address CRI
> [QA-784]: Add a profile for Address PERF006 iteration 1

- deploy/scripts/src/olh/test.ts
Adds the `iterationsComplete` metric to the `landingPage` scenario
Adds `iterationsComplete.add(1)` metric to the `landingPage` scenario
---
To correctly record the number of successful iterations in a test
> [QA-782] Adding the iterationsComplete metric to OLH landingPage

- deploy/scripts/src/olh/test.ts
QA-786 - Updating the load profile for OLH Perf006 Iteration 1 Test
What?
Load profile has been updated for OLH Perf006 first iteration test
Changes: 
Landing Page - 90 Per min
Change email - 1 per min
Change password - 1 per min
Change phone - 1 per min
Delete Account - 1 per min
> QA-786 - Updating the load profile for OLH Perf006 Iteration 1 Test

- koa-stub/src/package-lock.json
- koa-stub/src/package.json
Reverts govuk-one-login/performance-testing#1111
> Revert "Bump openid-client from 5.7.0 to 6.3.3 in /koa-stub/src"

- deploy/scripts/src/olh/test.ts
changed the duration of the changePassword scenario
- duration of changePassword scenario changed from 21 to 22 
---
Spike test failed without this change
---
> changed duration for OLH changePass scenario

- deploy/scripts/src/txma/clientEnrichment.ts
- deploy/scripts/src/txma/requestGenerator/txmaReqFormat.ts
- deploy/scripts/src/txma/requestGenerator/txmaReqGen.ts
Creates a new script, `txma/clientEnrichment.ts` for the `sendRegularEventWithEnrichment` scenario. Fixes the `sendRegularEvent` and `sendSingleEvent` scenarios in the `txma/test.js` script.
- Add new functions to the TxMA Request Format and Generator scripts for the clientEnrichment scenario.
- Restores the functions from the request format and generator for the `txma/test.ts` script
- Restores the `txma/test.ts` script with just the `sendSingleEvent` and `sendRegularEvent` scenario. 
- Creates a new script, `txma/clientEnrichment.ts` with the `sendRegularEventWithEnrichment` scenario.
---
To enable all three scenarios/performance tests to function and run correctly.
> [QA-809] Fixing the TxMA Shared Signals Scripts

- deploy/scripts/src/bravo/vc-storage.ts
Based on the test data preparation steps, VC storage script has been updated.
Added a debug statement to print the subjectID in the persistVC scenario. 
---
To facilitate VC Storage test data preparation.
---
- https://govukverify.atlassian.net/browse/QA-456
> QA-819 : VC-Storage script updates for TestData Prep

- deploy/scripts/src/cri-orange/otg.ts
scenario name changed to otg for profile
otg: {
startRate: 1,
preAllocatedVUs: 100,
maxVUs: 400,
stages: [
{ target: 1, duration: '1s' },
{ target: 1, duration: '30m' }
],
exec: 'otg'
}
---
> QA-828-2 Testname change

- deploy/scripts/src/cri-kiwi/f2f-cic.ts
QA-841 correct scenario step names for CIC as  those were prefixed with BAV
CIC: [
'B01_CIC_01_IPVStubCall',
'B01_CIC_02_Authorize',
'B01_CIC_03_Continue',
'B01_CIC_04_BankDetails',
'B01_CIC_05_CheckDetails',
'B01_CIC_06_SendAuthorizationCode',
'B01_CIC_07_SendBearerToken'
---
CIC scenarios steps are  was named with BAV
---
> QA-841 correct scenario step names for CIC

- deploy/scripts/src/cri-kiwi/f2f-cic.ts
Below changes :
Expiry date is used in script is outdated. Changed to 5 year later value
BRP related Test steps are outdated. So Removed the steps
Script change for Additional Page is involved for select emailing options
Latest Expiry date
Removed BRP related steps and Corrected group mappings
Corrected Validation checks for groupmap
---
PERF006 IT2
---
> QA-844 F2F script changes as per the latest page changes

- .github/workflows/publish.yaml
- deploy/scripts/package-lock.json
- deploy/scripts/package.json
Reverts govuk-one-login/performance-testing#1189
> Revert "[QA-849]: Add data vocab dependency"

- .github/workflows/publish.yaml
- deploy/scripts/package-lock.json
- deploy/scripts/package.json
Add data vocab dependency in the perf test repo.
- Added the `data-vocab` package dependency.
- Update the `Docker Build and Push` github workflow to allow permissions to access the package
---
To use `data-vocab` package in the `performance-testing` scripts
> [QA-849]: Add data vocab dependency in perf test

- .github/workflows/publish.yaml
- deploy/scripts/package-lock.json
- deploy/scripts/package.json
Reverts govuk-one-login/performance-testing#1205
> Revert "[QA-849]: Add data vocab dependency in perf test"

- deploy/scripts/src/cri-kiwi/f2f-cic.ts
Updated F2F and CIC scripts to separate IPV stub calls and AUT calls
- Updated `B01_CIC_05_CheckDetails` step with separate requests for CIC call and IPV stub call
- Updated `B02_FaceToFace_12_CheckDetails` step with separate requests for F2F call and IPV stub call
---
To report response time of the AUT calls and stub calls separately.
> [QA-855]: Updated F2F and CIC scripts to separate IPV stub calls and AUT calls

- deploy/scripts/src/ipv-core/data/m1CData.ts
- deploy/scripts/src/ipv-core/test.ts
Add M1C profile test scenario in IPV core script
- Added a new scenario for M1C profile test in IPV core script.
- Added m1C test data file for JSON payload imports.
---
To performance test the M1C profile journey.
> [QA-886]: IPV core script update for M1C scenario

- deploy/scripts/src/cri-lime/test.ts
Updated Fraud script include M1C flag
- Added an environment variable `IDENTITY_FRAUD_M1C` environment variable.
- Updated Fraud scenario to work if above variable is true or false.
---
To test Fraud CRI M1C resilience scenario
> [QA-885]: Updated Fraud script to include M1C flag

- .github/workflows/publish.yaml
- deploy/Dockerfile
- deploy/scripts/package-lock.json
- deploy/scripts/package.json
Revert SPOT PR changes
- Removed data-vocab package dependencies from package.json
- Docker build and push action updated to include npm install.
- 
---
To unblock pipeline as these changes are blocking the pipeline.
---
- [QA-849](https://govukverify.atlassian.net/browse/QA-849)
[QA-849]: https://govukverify.atlassian.net/browse/QA-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-938]: Revert SPOT PR changes

- .github/workflows/publish.yaml
- deploy/Dockerfile
- deploy/scripts/package-lock.json
- deploy/scripts/package.json
Add data vocab package in perf test
- Add data vocab package in perf test in package.json
- Update Docker Build and Push action to include dependency installation
- Update Dockerfile to remove duplicate step for dependency installation
---
To use data-vocab package in performance-testing repo.
> [QA-849]: Add data vocab dependency in performance testing

- .github/workflows/pre-merge-checks.yml
- .github/workflows/publish.yaml
- deploy/Dockerfile
- deploy/scripts/package-lock.json
- deploy/scripts/package.json
Reverts govuk-one-login/performance-testing#1259
> Revert "[QA-849]: Add data-vocab dependency in performance-testing"

- .github/workflows/pre-merge-checks.yml
- .github/workflows/publish.yaml
- deploy/Dockerfile
- deploy/scripts/package-lock.json
- deploy/scripts/package.json
Reverts govuk-one-login/performance-testing#1261
> Revert "[QA-849]: Add data vocab dependency in performance testing"

- deploy/scripts/src/spot/request/generator.ts
- deploy/scripts/src/spot/request/types.ts
- deploy/scripts/src/spot/test.ts
Update SPOT scripts to remove data-vocab dependency
- Removed all the classes imported from the data-vocab package.
- Added custom payloads for Fraud, Passport and KBV.
---
To conduct performance tests for SPOT
> [QA-849]: Update SPOT scripts to remove data-vocab dependency

- deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
Update the test target for Mobile Combined journey to 12
- Test target updated to 12 j/s
- PreAllocated and MaxVU updated accordingly.
- Groupmap updated - Transaction name uncommented.
---
To run a performance test for mobile at 12 j/s
> [QA-973]: Update the test target for Mobile Combined journey to 12

- deploy/scripts/src/authentication/test.ts
Stress test profile for iteration3
Added profile for stress test
---
To execute the stress test in iteration3
---
> [QA-975] Authentication - Add StressTestProfile

- koa-stub/template.yaml
Fixes a conflict with the domain deploy
- Switch from ssm parameters to template outputs.
---
Allow the template to deploy successfully - tested against non-prod.
---
> QA-967 Fixed koa-stub template

- deploy/scripts/src/mobile/v2-mobile-backend-get-client-attestation.ts
Adding  Mobile Platform BE Peak load test profile for Iteration 4
- Mobile Platform BE Test Target peak Load is 45 J/sec
- Rampup Time is 451 Sec
- Iteration duration is 12
---
To perform PERF006 Iteration 4 testing
---
> [QA-1025]:  Mobile Platform BE Peak load test profile for I4

- deploy/scripts/src/olh/test.ts
Add Iteration 4 Peak load profiles for the OLH scenarios.
- Adds the `perf006Iteration4PeakTest` load profiles for each scenario in the `olh/test.js` script.
---
To run an iteration 4 OLH peak test.
---
> [QA-1027] Adding OLH Iteration 4 peak load profiles.

- deploy/scripts/src/mobile/fe-be-combine-e2e.test.ts
Update the test target for Mobile Combined journey to 15 for I3 Peak Test.
- Test target updated to 15 j/s
- PreAllocated and MaxVU updated accordingly.
---
To run an Iteration 3 peak performance test for mobile at 15 j/s
---
> [QA-1053]:Update the test target for Mobile Combined journey to 15 for I3 Peak Test.

- deploy/scripts/src/spot/test.ts
Update the name of the peak test profile for SPOT in Perf006 Iteration 4.
- Update the test type in the profile name i.e. perf006Iteration4PeakTest
---
To execute Iteration 4 Peak test.
> [QA-1065]:Updated Profile name-I4PeakTest

- deploy/scripts/src/fraud/ticf.ts
Fix TICF CRI script issue
- Add `timestamp` variable used in signUpSuccess scenario
---
To fix a script issue with TICF CRI scenario.
> [QA-1073]: Fix TICF CRI script issue

- deploy/scripts/src/cimit/test.ts
Fix CIMIT scripting issue
- CIMIT Key to sign JWT needs to be of type JWK
---
To fix the error we are facing with CIMIT script
> [QA-1074]: Fix CIMIT scripting issue

- deploy/scripts/src/common/utils/checks/assertions.ts
- deploy/scripts/src/fraud/ticf.ts
Update TICF CRI API calls
- Added a function to check response status code 202 - `deploy/scripts/src/common/utils/checks/assertions.ts`
- Added `groupMap()` function call for all the 4 API calls - `deploy/scripts/src/fraud/ticf.ts`
- Added TICF CRI API calls in the `timeGroup()` function call - `deploy/scripts/src/fraud/ticf.ts`
- Added an `ENVIRONMENT` environment variable property in the `env` object - `deploy/scripts/src/fraud/ticf.ts`
---
To conduct performance test for the TICF CRI scenarios.
> [QA-1075]: Update TICF CRI API calls

- deploy/scripts/src/cimit/request/generator.ts
- deploy/scripts/src/cimit/request/types.ts
- deploy/scripts/src/cimit/test.ts
CIMIT - Fix linting and other scripting issues
- Added types for `MitigatingCredentialClass`, `MitigationClass` and `ContraIndicatorClass`. Updated CIMIT payload to use these classes - `deploy/scripts/src/cimit/request/types.ts`
- Updated request generator functions as per the changes in the payload format - `deploy/scripts/src/cimit/request/generator.ts`
- Fixed linting and variable assignment issues in the script - `deploy/scripts/src/cimit/test.ts`
---
To resolve errors with the CIMIT script
> [QA-1076]: CIMIT - Fix linting and other scripting issues

- deploy/scripts/src/cimit/test.ts
Update request body for CIMIT POST requests
- Update request body for CIMIT POST requests to include JSON format.
---
To fix the smoke test errors seen in the smoke test of CIMIT scripts.
> [QA-1078]: Update request body for CIMIT POST requests

- deploy/scripts/src/common/requestGenerator/txmaReqFormat.ts
- deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
- deploy/scripts/src/fraud/ticf.ts
Updates the TxMA payloads used in the TiCF script to correctly reflect the event catalog schemas.
- Updated each TxMA event payload in `requestGenerator/txmaReqGen.ts` and `requestGenerator/txmaReqFormat.ts` use in the `fraud/ticf.ts` script to match the Event Catalog Schema.
---
To send correct TxMA events in the TiCF CRI performance test script.
> [QA563A] TiCF TxMA Payload Fixes

- deploy/scripts/src/ipv-core/test.ts
Update IPVCore script to use Orch stub with devperf 
- update environment constants to include PERF 
---
To enable using Orch stub (Perf) along with the dev - perf environment and support regression testing
---
> QA-1063 IPVcore script - use Orch stub + devperf

- deploy/scripts/src/cimit/test.ts
CIMIT - Update request body of Put Contra Indicator function
- Update request body of Put Contra Indicator as per the CIMIT API specification
---
To fix the issues identified in the smoke test.
> [QA-1085]: CIMIT - Update request body of Put Contra Indicator function

- deploy/scripts/src/cimit/request/generator.ts
- deploy/scripts/src/cimit/request/types.ts
- deploy/scripts/src/cimit/test.ts
Updated CIMIT payload and scripts
- Updated the types to just create payloads for Passport VC - `deploy/scripts/src/cimit/request/types.ts`
- Update request generator to generate a VC with CI and a VC for mitigations - `deploy/scripts/src/cimit/request/generator.ts`
- Updated the test file to include all 3 CIMIT API calls in the same function with a delay of 5 seconds in between each API call - `deploy/scripts/src/cimit/test.ts`
---
To address smoke test errors for CIMIT
> [QA-1087] - Updated CIMIT payload and scripts

- deploy/scripts/src/cri-kiwi/BAV.ts
- deploy/scripts/src/cri-kiwi/utils/authorization.ts
BAV scenario script updates It will add client_assertion_type and client_assertion params
- Added Test step 
- Added client_assertion_type and client_assertion
---
To update as per the latest changes
---
> [QA-1084]: BAV - Adding Client assertion params in BAV script 

- deploy/scripts/src/cimit/test.ts
CIMIT - Update the request body for post mitigations
- Updated the request body of the post mitigations API call to be an array.
---
To fix the smoke test errors
> [QA-1087]: CIMIT - Update the request body for post mitigations

- deploy/scripts/src/cimit/test.ts
CIMIT - Add I4 peak test profile
- Add I4 peak test profile (Target - 188 j/s, Ramp up 471s, Iteration duration - 19s)
---
To run a performance test for CIMIT
> [QA-1096]: CIMIT - Add I4 peak test profile

- deploy/scripts/src/fraud/ticf.ts
Edits the wait times in the `ticf` script, and therefore changes the iteration duration and the I4 peak and spike load profiles. 
- Removes all wait times between payload generation
- Decreases all other wait times to 3s
- increases the iteration duration parameter to 66s to account for wait time chamges
---
To optimise the `ticf` performance test scenario
> [QA-1109] Editing TiCF wait times.

- deploy/scripts/src/authentication/test.ts
Auth - Update RP stub function to use the new URL
- Updated the target URL in `deploy/scripts/src/authentication/test.ts`
- Updated the value of `ACCOUNT_RP_STUB` env var in in parameter store (Path -` /perfTest/account/authentication/rpStub`)
---
To update Auth scripts to use the new RP stub URL
> QA-1095: Auth - Update RP stub function to use the new URL

- deploy/scripts/src/common/requestGenerator/txmaReqGen.ts
- deploy/scripts/src/fraud/ticf.ts
- deploy/scripts/src/txma/clientEnrichment.ts
- deploy/scripts/src/txma/test.ts
created dynamic & unique `eventID` values for each TxMA event sent in the `ticf.ts` script.
- Adds the `eventID` value back into the TxMA Request Generator instead of passing it as a parameter, to ensure each value of `eventID` is unique for each TxMA event sent. 
---
To create a fully representative/real-world performance scenario.
> [QA-1130] Creating dynamic eventID values for TxMA events in the TiCF script.

- deploy/scripts/src/authentication/test.ts
Add Spike Test profile for Auth (Signup and SignIn)
- Sign up Target throughput - 113 J/sec
- SignIn Target Throughput - 129 J/Sec
---
To Perform PERF006-Iteration 4 testing
---
> [QA-1134]: I4 Authentication - Spike test profile

- deploy/template.yaml
Reverts govuk-one-login/performance-testing#1401
> Revert "[QA-1156]: Update assume role session duration to 5400 seconds"

- deploy/scripts/src/mobile/testSteps/frontend.ts
This pull request is to update the pageContentCheck text in postIphoneModel() step
- Changed the pageContentCheck argument to "Use your passport and an app to prove your identity"
---
To run Iteration 5 peak test
---
> QA-1200: DCMAW -Mobile (FE+BE) - Script changes to update 'pageContentCheck'

- deploy/scripts/src/govuk-app-backend/test.ts
Update GovUK App backend script
- Updated the correlation approach to remove findBetween
- Added load profiles for soak, stress and spike tests
---
To run the remaining performance tests for GovUK App backend
> [QA-1227] - Update GovUK App backend script

- deploy/scripts/src/authentication/test.ts
Update page content in the sign in scenario.
- Update page content in `B02_SignIn_02_ClickSignIn` step based on the latest changes.
---
To fix the page content check failure in Sign in script
> [QA-1250]: Auth - Fix page content issue in Sign In scenario

- deploy/scripts/src/ipv-core/test.ts
This Pull Request integrates new screens and steps into the existing performance test script for identity scenario, ensuring it accurately reflects the updated user journey.
-  Added new screens and their corresponding assertions within the `identity` function (`B01_Identity_04_SelectPhotoIDChoice` through `B01_Identity_07_SelectAnotherWayToProveIdentity`).
-  Updated `groupMap.identity` with descriptive names for all steps.
-  Re-indexed all `groupMap.identity` entries to reflect the insertion of new steps and the re-structuring of existing ones.
---
These changes are being made to:
-   Ensure the performance test script accurately simulates the most up-to-date user journey for identity verification.
-   Proceed with the iteration 6 performance tests.
---
> QA[1265] IPVCore:Added new steps to the  function
